% -------------------------------------------------------------------------
% B01_Registration_WithoutFlow_3DScale_WithMWF.m
%
% Generated by : Seyed Mohammadali Rahmati
% Affiliation  : Comparative Neuromechanics Lab,
%                School of Biological Sciences,
%                Georgia Institute of Technology, Atlanta, GA, USA
% Email        : smarahmati@gmail.com
%
% Purpose
% -------
% This script registers 3D bone models/STL meshes to tracked rat hindlimb
% landmarks over time.
%
% Main workflow
% -------------
% 1. Load marker trajectories, cycle events, bone landmarks, and STL meshes.
% 2. Filter the tracked 3D marker trajectories.
% 3. Swap coordinate axes to match the XMALab/export coordinate convention.
% 4. Register pelvis, femur, tibia, and foot STL models to tracked landmarks.
% 5. Apply Marker Weighting Factor (MWF) to give selected joint-axis points
%    stronger influence during the second registration pass.
%
% Notes
% -----
% - Units are centimeters unless otherwise stated.
% - The script assumes that the required .mat, .csv, and helper .m files are
%   in the MATLAB path or in the current working folder.
% - The output variables are kept in the workspace for downstream scripts
%   such as B03_Kinematics_3D_And_Cycles_R1_MLaxis.m.
% -------------------------------------------------------------------------

clear; clc;  % Clear workspace and command window.

%% User parameter: Marker Weighting Factor (MWF)
% MWF controls how strongly selected joint-axis points are weighted during
% the second registration pass.
%
% MWF = 1:
%   No extra weighting. Each selected point contributes one time.
%
% MWF > 1:
%   Some joint-axis/constraint points are repeated MWF times using
%   repeat_coordinates(). Repeating a point makes the registration fit that
%   point more strongly.
%
% In this B01 script:
%   MWF is set directly below.
%
% Normal run:
%   Keep MWF = 1.
%
% Manual test:
%   Change MWF below, for example:
%       MWF = 2;
%       MWF = 5;
%       MWF = 10;
%
% Automated MWF sensitivity analysis:
%   B10_Error_ROM_Sensitivity_to_MWF can test different MWF values using a
%   temporary B01 copy, while the original B01 file stays unchanged.

MWF = 1;

%% User parameters: trial information and input files
% Set this to true for automatic/reproducible runs using definput.
% Set this to false if you want MATLAB to open an input dialog.
useDefaultInputs = true;

% Trial/file information requested by the script:
% 1) category       : Experimental group or folder label.
% 2) rat_gender    : Sex of the rat.
% 3) rat_number    : Rat ID number.
% 4) procedure_time: Pre/Post surgery time point.
% 5) Speed         : Treadmill speed in m/min.
% 6) fileName      : 3D marker trajectory CSV file.
% 7) left events   : CSV file containing left gait-cycle events.
% 8) right events  : CSV file containing right gait-cycle events.
prompt = {'Enter category (Pilot, WR, Sus, Baseline):', ...
          'Enter rat gender:', ...
          'Enter rat number:', ...
          'Enter pre or post surgery (Pre, Post2W, Post4W, Post6W, Post8W):', ...
          'Enter speed (m/min) (24, 30, ...):', ...
          'File name:', ...
          'Left cycle events:', ...
          'Right cycle events:'};

dlgtitle = 'Input Required Information';
dims = repmat([1 70], numel(prompt), 1);  % One input box per prompt.

% Default example files. These make the script run without user clicks when
% useDefaultInputs = true.
definput = {'BaselineR1', 'Male', '14', 'Pre', '24', ...
'Sample_2024-09-03_15-41_Evt01-MM_flipped-3D.csv', ...
'Sample_L_CycleEvents_2024-09-03_15-41_Evt01-Camera2_flipped.csv', ...
'Sample_R_CycleEvents_2024-09-03_15-41_Evt01-Camera2_flipped.csv'};

if useDefaultInputs
    answer = definput';
else
    answer = inputdlg(prompt, dlgtitle, dims, definput);
    if isempty(answer)
        error('Input dialog was cancelled. Script stopped.');
    end
end

%% Extract and format trial parameters
category = answer{1};
rat_gender = answer{2};
rat_number = str2double(answer{3});  % Numeric rat ID.
procedure_time = answer{4};
Speed = str2double(answer{5});       % Treadmill speed in m/min.
fileName = answer{6};                % 3D marker trajectory CSV.

% fileName_Xray is a short tag used inside TrialName.
% The original dataset uses the first 22 characters as the event/time tag.
fileTagLength = min(22, numel(fileName));
fileName_Xray = strrep(fileName(1:fileTagLength), '-', '_');

% TrialName is used by downstream scripts to store results under one field.
TrialName = sprintf('%s_%s_Rat%d_%s_Speed%d_%s', ...
                    category, rat_gender, rat_number, ...
                    procedure_time, Speed, fileName_Xray);

% Display trial information
fprintf('Category: %s\nRat Sex: %s\nRat Number: %d\nProcedure Time: %s\nSpeed: %d\nFile Name (X-ray): %s\n', ...
        category, rat_gender, rat_number, procedure_time, Speed, fileName_Xray);

%% Load bone landmark files
% These MAT files contain manually defined anatomical landmarks on each bone.
% Example:
%   RFemurBoneMarks.RFH = right femoral head center
%   RTibiaBoneMarks.RTP = right tibia proximal landmark
%
% These landmarks are used as STL reference points during registration.
load('PelvisBoneMarks.mat');
load('RFemurBoneMarks.mat');
load('RTibiaBoneMarks.mat');
load('RFootBoneMarks.mat');
load('LFemurBoneMarks.mat');
load('LTibiaBoneMarks.mat');
load('LFootBoneMarks.mat');

tic; % Start timing execution

%% Load tracked 3D marker data
% fileName must be a CSV file containing marker columns such as:
%   FRH_X, FRH_Y, FRH_Z, ...
% where each marker has X, Y, and Z coordinates.
dataTable = readtable(fileName);

% Keep all rows. This line is left explicit so it is easy to edit if dark
% frames or unusable frames need to be removed later.
dataTable = dataTable(1:size(dataTable,1), :);

% Column headers are used to automatically detect marker names.
columnNames = dataTable.Properties.VariableNames;

%% User parameters: filtering
% sampleRate:
%   Marker sampling frequency in Hz. Here, the data were sampled at 100 Hz.
%
% cutoffFrequency:
%   Low-pass Butterworth cutoff frequency in Hz. A 10 Hz cutoff removes
%   high-frequency noise while preserving rat walking kinematics.
sampleRate = 100;
cutoffFrequency = 10;

% Normalize cutoff by Nyquist frequency, then create a 2nd-order filter.
normalizedCutoff = cutoffFrequency / (sampleRate / 2);
[b, a] = butter(2, normalizedCutoff);

%% Process and filter marker data
% This block creates two variables for each marker coordinate:
%   raw variable      : original coordinate from the CSV
%   filtered variable : same coordinate after low-pass filtering, with F_
%
% Example:
%   FRH   = raw femoral head coordinate data
%   F_FRH = filtered femoral head coordinate data
fullNames = cell(size(columnNames));
abbreviations = cell(size(columnNames));

for i = 1:length(columnNames)
    % Extract capital letters and underscores from column names
    abbreviatedName = columnNames{i}(isstrprop(columnNames{i}, 'upper') | columnNames{i} == '_');
    
    if isempty(abbreviatedName)
        warning('Skipping column %d due to lack of capital letters in header.', i);
        continue;
    end
    
    % Store names
    fullNames{i} = columnNames{i};
    abbreviations{i} = abbreviatedName;
    
    % Apply the Butterworth filter
    filteredData = filtfilt(b, a, dataTable.(columnNames{i}));
    
    % Assign variables dynamically
    eval([abbreviatedName ' = dataTable.' columnNames{i} ';']);
    eval(['F_' abbreviatedName ' = filteredData;']);
end

%% Extract Unique Marker Names
markers_abb = unique(cellfun(@(x) x(1:end-2), abbreviations, 'UniformOutput', false));
markers_full = unique(cellfun(@(x) x(1:end-2), columnNames, 'UniformOutput', false));

%% Process Markers into XYZ Matrices
for i = 1:length(markers_full)
    markerName_abb = markers_abb{i};
    markerName_full = markers_full{i};
    
    % Extract XYZ coordinates
    xyzData = [dataTable.([markerName_full '_X']), ...
               dataTable.([markerName_full '_Y']), ...
               dataTable.([markerName_full '_Z'])];
    
    % Apply filter to XYZ data
    xyzFilteredData = filtfilt(b, a, xyzData);
    
    % Assign filtered and unfiltered marker data
    eval([markerName_abb ' = xyzData;']);
    eval(['F_' markerName_abb ' = xyzFilteredData;']);
end

%% Store Name Mappings
nameMapping = table(fullNames', abbreviations', 'VariableNames', {'FullName', 'Abbreviation'});
nameMapping_markers = table(markers_full', markers_abb', 'VariableNames', {'FullName', 'Abbreviation'});

%% Define All Markers
AllMarkers = [CL, CR, FLC, FLH, FLT, FRC, FRH, FRT, ML, MR, PS, TLD, TLH, TLP, TRD, TRH, TRP];


%% Combine markers and swap coordinate axes
% XMALab/exported coordinates use a different axis order than the STL/model
% coordinate convention used in the rest of this script.
%
% Order = [3, 1, 2] means:
%   new X = old Z
%   new Y = old X
%   new Z = old Y
%
% Variables ending with _S are swapped-coordinate versions.
% Variables starting with F_ are filtered-coordinate versions.

%--------------------------------- Initialization ---------------------------------

% Determine the number of time steps from the size of the first marker matrix
n = size(F_FRH, 1);

% Combine all marker data into a single matrix
F_AllMarkers = [F_CL, F_CR, F_FLC, F_FLH, F_FLT, F_FRC, F_FRH, F_FRT, F_ML, F_MR, F_PS, ...
                F_TLD, F_TLH, F_TLP, F_TRD, F_TRH, F_TRP];
            
% Extract X, Y, and Z components separately
F_AllMarkers_X = F_AllMarkers(:, 1:3:end);
F_AllMarkers_Y = F_AllMarkers(:, 2:3:end);
F_AllMarkers_Z = F_AllMarkers(:, 3:3:end);

%--------------------------------- Marker Definitions ---------------------------------
% PS:  Pubic Symphysis
% FRH: Femur Right Head
% FRT: Femur Right Trochanter
% FRC: Femur Right Condyle
% TRP: Tibia Right Proximal Condyle
% TRH: Tibia Right Harp (distal fusion of the tibia and fibula)
% TRD: Tibia Right Distal Condyle (lateral malleolus of the tibia)
% CR:  Calcaneus Right
% MR:  Metatarsal Right

%--------------------------------- Swapping Data ---------------------------------
% Axis-swap order. Change only if the coordinate convention changes.
Order = [3, 1, 2];

% Swap coordinates for each marker
F_PS_S  = F_PS(:, Order);
F_FLH_S = F_FLH(:, Order);
F_FRH_S = F_FRH(:, Order);
F_TLP_S = F_TLP(:, Order);
F_TRP_S = F_TRP(:, Order);
F_FLT_S = F_FLT(:, Order);
F_FRT_S = F_FRT(:, Order);
F_ML_S  = F_ML(:, Order);
F_MR_S  = F_MR(:, Order);
F_FLC_S = F_FLC(:, Order);
F_FRC_S = F_FRC(:, Order);
F_TLD_S = F_TLD(:, Order);
F_TRD_S = F_TRD(:, Order);
F_TLH_S = F_TLH(:, Order);
F_TRH_S = F_TRH(:, Order);
F_CL_S  = F_CL(:, Order);
F_CR_S  = F_CR(:, Order);

% Combine swapped markers into a single matrix
F_AllMarkers_S = [F_CL_S, F_CR_S, F_FLC_S, F_FLH_S, F_FLT_S, F_FRC_S, F_FRH_S, F_FRT_S, F_ML_S, F_MR_S, F_PS_S, ...
                  F_TLD_S, F_TLH_S, F_TLP_S, F_TRD_S, F_TRH_S, F_TRP_S];
              
% Extract swapped X, Y, and Z components separately
F_AllMarkers_S_X = F_AllMarkers_S(:, 1:3:end);
F_AllMarkers_S_Y = F_AllMarkers_S(:, 2:3:end);
F_AllMarkers_S_Z = F_AllMarkers_S(:, 3:3:end);

%--------------------------------- Swapping Raw Data ---------------------------------
PS_S  = PS(:, Order);
FLH_S = FLH(:, Order);
FRH_S = FRH(:, Order);
TLP_S = TLP(:, Order);
TRP_S = TRP(:, Order);
FLT_S = FLT(:, Order);
FRT_S = FRT(:, Order);
ML_S  = ML(:, Order);
MR_S  = MR(:, Order);
FLC_S = FLC(:, Order);
FRC_S = FRC(:, Order);
TLD_S = TLD(:, Order);
TRD_S = TRD(:, Order);
TLH_S = TLH(:, Order);
TRH_S = TRH(:, Order);
CL_S  = CL(:, Order);
CR_S  = CR(:, Order);

% Combine swapped raw marker data
AllMarkers_S = [CL_S, CR_S, FLC_S, FLH_S, FLT_S, FRC_S, FRH_S, FRT_S, ML_S, MR_S, PS_S, ...
                TLD_S, TLH_S, TLP_S, TRD_S, TRH_S, TRP_S];
            
% Extract swapped raw X, Y, and Z components separately
AllMarkers_S_X = AllMarkers_S(:, 1:3:end);
AllMarkers_S_Y = AllMarkers_S(:, 2:3:end);
AllMarkers_S_Z = AllMarkers_S(:, 3:3:end);


%% Process gait-cycle event files
% TL_CycleEvents and TR_CycleEvents contain left and right gait events.
% Typical columns include initial stance, mid stance, terminal stance,
% mid swing, and terminal swing.
TL_CycleEvents = rmmissing(readtable(answer{7,1}));
TR_CycleEvents = rmmissing(readtable(answer{8,1}));

% Convert tables to matrices for easier numerical processing
MLCE = table2array(TL_CycleEvents); % Left cycle events (Matrix format)
MRCE = table2array(TR_CycleEvents); % Right cycle events (Matrix format)

% Flatten matrices into single column vectors
LCE = MLCE(:); % Left cycle events vector
RCE = MRCE(:); % Right cycle events vector

% Combine and sort all cycle events
CE = sort([LCE; RCE]);

%% Generate Step Sequences for Left and Right Cycles

% Function to generate a step sequence from cycle event data
generateStepSequence = @(M) sort(unique(cell2mat(arrayfun(@(i) (M(i, 1):M(i, end))', (1:size(M, 1))', 'UniformOutput', false))));

% Compute left cycle steps (LCS) and right cycle steps (RCS)
LCS = generateStepSequence(MLCE);
RCS = generateStepSequence(MRCE);

% CS = all frame indices that belong to accepted gait cycles.
% Later, the analysis keeps only these cycle frames.
CS = sort(unique([LCS; RCS]));


%% Time calculation
% Hz must match sampleRate above unless the time base is intentionally
% different.
Hz = 100;          % Sampling rate in Hz.
dt = 1 / Hz;       % Time step in seconds per frame.

% Compute time vector based on the number of frames in F_PS_S
time = ((0:length(F_PS_S) - 1) * dt)';

%% Extract cycle-specific marker data
% These combined marker matrices are reduced to only the frames in CS.
% The individual marker variables are kept at their original full length,
% because later registration loops index them by original frame number.
F_AllMarkers_S   = F_AllMarkers_S(CS, :);
F_AllMarkers_S_X = F_AllMarkers_S_X(CS, :);
F_AllMarkers_S_Y = F_AllMarkers_S_Y(CS, :);
F_AllMarkers_S_Z = F_AllMarkers_S_Z(CS, :);

AllMarkers_S   = AllMarkers_S(CS, :);
AllMarkers_S_X = AllMarkers_S_X(CS, :);
AllMarkers_S_Y = AllMarkers_S_Y(CS, :);
AllMarkers_S_Z = AllMarkers_S_Z(CS, :);

%% Read STL mesh files
% Each *_STL.mat file is expected to contain a structure with:
%   .Points           = STL vertices
%   .ConnectivityList = STL faces
%
% Example:
%   RFemur_STL.Points
%   RFemur_STL.ConnectivityList
loadSTL = @(filename) deal(load(filename).(replace(filename, '.mat', '')).Points, ...
                           load(filename).(replace(filename, '.mat', '')).ConnectivityList);

% Load STL data for different anatomical structures
[V_RFemur, F_RFemur] = loadSTL('RFemur_STL.mat');  % Right Femur
[V_LFemur, F_LFemur] = loadSTL('LFemur_STL.mat');  % Left Femur
[V_Pelvis, F_Pelvis] = loadSTL('Pelvis_STL.mat');  % Pelvis
[V_RTibia, F_RTibia] = loadSTL('RTibia_STL.mat');  % Right Tibia
[V_LTibia, F_LTibia] = loadSTL('LTibia_STL.mat');  % Left Tibia
[V_RFoot,  F_RFoot]  = loadSTL('RFoot_STL.mat');   % Right Foot
[V_LFoot,  F_LFoot]  = loadSTL('LFoot_STL.mat');   % Left Foot


%% Assign bone landmark points
% computeClosestPoint() finds the STL vertex closest to a manually defined
% anatomical landmark. The index is later used to track that same anatomical
% location after the whole mesh is transformed.
computeClosestPoint = @(V, marker) findClosestSTLPoint(V, marker);

%% Right Femur STL
% (Femur head, greater trochanter, epicondyle, hip, knee)
RFH = RFemurBoneMarks.RFH;
RFT = RFemurBoneMarks.RFT;
RFE = RFemurBoneMarks.RFE;
RFKne = RFemurBoneMarks.RFKne;
RFEL = RFemurBoneMarks.RFEL;
RFEM = RFemurBoneMarks.RFEM;

RFemurSTLpoints = [RFH; RFT; RFE];

[min_RFH, I_RFH] = computeClosestPoint(V_RFemur, RFH);
[min_RFT, I_RFT] = computeClosestPoint(V_RFemur, RFT);
[min_RFE, I_RFE] = computeClosestPoint(V_RFemur, RFE);
[min_RFKne, I_RFKne] = computeClosestPoint(V_RFemur, RFKne);
[min_RFEL, I_RFEL] = computeClosestPoint(V_RFemur, RFEL);
[min_RFEM, I_RFEM] = computeClosestPoint(V_RFemur, RFEM);

%% Left Femur STL
% (Femur head, greater trochanter, epicondyle, hip, knee)
LFH = LFemurBoneMarks.LFH;
LFT = LFemurBoneMarks.LFT;
LFE = LFemurBoneMarks.LFE;
LFKne = LFemurBoneMarks.LFKne;
LFEL = LFemurBoneMarks.LFEL;
LFEM = LFemurBoneMarks.LFEM;

LFemurSTLpoints = [LFH; LFT; LFE];

[min_LFH, I_LFH] = computeClosestPoint(V_LFemur, LFH);
[min_LFT, I_LFT] = computeClosestPoint(V_LFemur, LFT);
[min_LFE, I_LFE] = computeClosestPoint(V_LFemur, LFE);
[min_LFKne, I_LFKne] = computeClosestPoint(V_LFemur, LFKne);
[min_LFEL, I_LFEL] = computeClosestPoint(V_LFemur, LFEL);
[min_LFEM, I_LFEM] = computeClosestPoint(V_LFemur, LFEM);

%% Pelvis STL
% (Right hip, left hip, pubic symphysis)
RPHip = PelvisBoneMarks.RPHip;
LPHip = PelvisBoneMarks.LPHip;
RASI = PelvisBoneMarks.RASI;
LASI = PelvisBoneMarks.LASI;
PS = PelvisBoneMarks.PS;

PelvisSTLpoints = [RPHip; LPHip; PS];

[min_RPHip, I_RPHip] = computeClosestPoint(V_Pelvis, RPHip);
[min_LPHip, I_LPHip] = computeClosestPoint(V_Pelvis, LPHip);
[min_RASI, I_RASI] = computeClosestPoint(V_Pelvis, RASI);
[min_LASI, I_LASI] = computeClosestPoint(V_Pelvis, LASI);
[min_PS, I_PS] = computeClosestPoint(V_Pelvis, PS);

%% Right Tibia STL
% (Proximal, harp, distal, foot contacts, knee, ankle, tibial plateau)
RTP = RTibiaBoneMarks.RTP;
RTH = RTibiaBoneMarks.RTH;
RTD = RTibiaBoneMarks.RTD;
RTMAM = RTibiaBoneMarks.RTMAM;
RTMAL = RTibiaBoneMarks.RTMAL;
RTKne = RTibiaBoneMarks.RTKne;
RTAnk = RTibiaBoneMarks.RTAnk;
RTPAL = RTibiaBoneMarks.RTPAL;
RTPAM = RTibiaBoneMarks.RTPAM;

RTibiaSTLpoints = [RTP; RTH; RTD; RTPAL; RTPAM];

[min_RTP, I_RTP] = computeClosestPoint(V_RTibia, RTP);
[min_RTH, I_RTH] = computeClosestPoint(V_RTibia, RTH);
[min_RTD, I_RTD] = computeClosestPoint(V_RTibia, RTD);
[min_RTMAM_T, I_RTMAM_T] = computeClosestPoint(V_RTibia, RTMAM);
[min_RTMAL_T, I_RTMAL_T] = computeClosestPoint(V_RTibia, RTMAL);
[min_RTKne, I_RTKne] = computeClosestPoint(V_RTibia, RTKne);
[min_RTAnk, I_RTAnk] = computeClosestPoint(V_RTibia, RTAnk);
[min_RTPAL, I_RTPAL] = computeClosestPoint(V_RTibia, RTPAL);
[min_RTPAM, I_RTPAM] = computeClosestPoint(V_RTibia, RTPAM);

%% Left Tibia STL
% (Proximal, harp, distal, foot contacts, knee, ankle, tibial plateau)
LTP = LTibiaBoneMarks.LTP;
LTH = LTibiaBoneMarks.LTH;
LTD = LTibiaBoneMarks.LTD;
LTMAM = LTibiaBoneMarks.LTMAM;
LTMAL = LTibiaBoneMarks.LTMAL;
LTKne = LTibiaBoneMarks.LTKne;
LTAnk = LTibiaBoneMarks.LTAnk;
LTPAL = LTibiaBoneMarks.LTPAL;
LTPAM = LTibiaBoneMarks.LTPAM;

LTibiaSTLpoints = [LTP; LTH; LTD; LTPAL; LTPAM];

[min_LTP, I_LTP] = computeClosestPoint(V_LTibia, LTP);
[min_LTH, I_LTH] = computeClosestPoint(V_LTibia, LTH);
[min_LTD, I_LTD] = computeClosestPoint(V_LTibia, LTD);
[min_LTMAM_T, I_LTMAM_T] = computeClosestPoint(V_LTibia, LTMAM);
[min_LTMAL_T, I_LTMAL_T] = computeClosestPoint(V_LTibia, LTMAL);
[min_LTKne, I_LTKne] = computeClosestPoint(V_LTibia, LTKne);
[min_LTAnk, I_LTAnk] = computeClosestPoint(V_LTibia, LTAnk);
[min_LTPAL, I_LTPAL] = computeClosestPoint(V_LTibia, LTPAL);
[min_LTPAM, I_LTPAM] = computeClosestPoint(V_LTibia, LTPAM);

%% Right Foot STL
% (Ankle, tibia foot contact, calcaneus, metatarsal)
RFAnk = RFootBoneMarks.RFAnk;
RCal = RFootBoneMarks.RCal;
RMet = RFootBoneMarks.RMet;

RFootSTLpoints = [RTMAM; RTMAL; RMet; RCal];

[min_RFAnk, I_RFAnk] = computeClosestPoint(V_RFoot, RFAnk);
[min_RTMAM_F, I_RTMAM_F] = computeClosestPoint(V_RFoot, RTMAM);
[min_RTMAL_F, I_RTMAL_F] = computeClosestPoint(V_RFoot, RTMAL);
[min_RCal, I_RCal] = computeClosestPoint(V_RFoot, RCal);
[min_RMet, I_RMet] = computeClosestPoint(V_RFoot, RMet);

%% Left Foot STL
% (Ankle, tibia foot contact, calcaneus, metatarsal)
LFAnk = LFootBoneMarks.LFAnk;
LCal = LFootBoneMarks.LCal;
LMet = LFootBoneMarks.LMet;

LFootSTLpoints = [LTMAM; LTMAL; LMet; LCal];

[min_LFAnk, I_LFAnk] = computeClosestPoint(V_LFoot, LFAnk);
[min_LTMAM_F, I_LTMAM_F] = computeClosestPoint(V_LFoot, LTMAM);
[min_LTMAL_F, I_LTMAL_F] = computeClosestPoint(V_LFoot, LTMAL);
[min_LCal, I_LCal] = computeClosestPoint(V_LFoot, LCal);
[min_LMet, I_LMet] = computeClosestPoint(V_LFoot, LMet);


%% Registration: Initialize Transformation Variables

% Number of frames (same as F_FRH_S length)
numFrames = length(F_FRH_S);

% Function to initialize cell arrays for transformations
initCellArray = @(n) cell(n, 1);
initNanArray = @(n) nan(n, 3);

%% Right Femur Transformations
RFemur_rotation = initCellArray(numFrames);
V_RFemur_transformed = initCellArray(numFrames);
RFemur_registered_STLpoints = initCellArray(numFrames);
RFemur_translation = initCellArray(numFrames);
RFemur_markerpoints = initCellArray(numFrames);
RFemur_scale = initCellArray(numFrames);
RFKne_transformed = initNanArray(numFrames);
RFEL_transformed = initNanArray(numFrames);
RFEM_transformed = initNanArray(numFrames);
RFemurSTLpoints2 = initCellArray(numFrames);
RFemur_markerpoints2 = initCellArray(numFrames);
RFH_transformed = initNanArray(numFrames);
RFT_transformed = initNanArray(numFrames);
RFE_transformed = initNanArray(numFrames);

%% Left Femur Transformations
LFemur_rotation = RFemur_rotation;
V_LFemur_transformed = V_RFemur_transformed;
LFemur_registered_STLpoints = RFemur_registered_STLpoints;
LFemur_translation = RFemur_translation;
LFemur_markerpoints = RFemur_markerpoints;
LFemur_scale = RFemur_scale;
LFKne_transformed = initNanArray(numFrames);
LFEL_transformed = initNanArray(numFrames);
LFEM_transformed = initNanArray(numFrames);
LFemurSTLpoints2 = initCellArray(numFrames);
LFemur_markerpoints2 = initCellArray(numFrames);
LFH_transformed = initNanArray(numFrames);
LFT_transformed = initNanArray(numFrames);
LFE_transformed = initNanArray(numFrames);

%% Pelvis Transformations
Pelvis_rotation = initCellArray(numFrames);
V_Pelvis_transformed = initCellArray(numFrames);
Pelvis_registered_STLpoints = initCellArray(numFrames);
Pelvis_translation = initCellArray(numFrames);
Pelvis_markerpoints = initCellArray(numFrames);
Pelvis_scale = initCellArray(numFrames);
RPHip_transformed = initNanArray(numFrames);
LPHip_transformed = initNanArray(numFrames);
RASI_transformed = initNanArray(numFrames);
LASI_transformed = initNanArray(numFrames);
PS_transformed = initNanArray(numFrames);

%% Right Tibia Transformations
RTibia_rotation = initCellArray(numFrames);
V_RTibia_transformed = initCellArray(numFrames);
RTibia_registered_STLpoints = initCellArray(numFrames);
RTibia_translation = initCellArray(numFrames);
RTibia_markerpoints = initCellArray(numFrames);
RTibia_scale = initCellArray(numFrames);
RTMAM_T_transformed = initNanArray(numFrames);
RTMAL_T_transformed = initNanArray(numFrames);
RTKne_transformed = initNanArray(numFrames);
RTAnk_transformed = initNanArray(numFrames);
RTPAL_transformed = initNanArray(numFrames);
RTPAM_transformed = initNanArray(numFrames);
RTP_transformed = initNanArray(numFrames);
RTH_transformed = initNanArray(numFrames);
RTD_transformed = initNanArray(numFrames);

%% Left Tibia Transformations
LTibia_rotation = RTibia_rotation;
V_LTibia_transformed = V_RTibia_transformed;
LTibia_registered_STLpoints = RTibia_registered_STLpoints;
LTibia_translation = RTibia_translation;
LTibia_markerpoints = RTibia_markerpoints;
LTibia_scale = RTibia_scale;
LTMAM_T_transformed = initNanArray(numFrames);
LTMAL_T_transformed = initNanArray(numFrames);
LTKne_transformed = initNanArray(numFrames);
LTAnk_transformed = initNanArray(numFrames);
LTPAL_transformed = initNanArray(numFrames);
LTPAM_transformed = initNanArray(numFrames);
LTP_transformed = initNanArray(numFrames);
LTH_transformed = initNanArray(numFrames);
LTD_transformed = initNanArray(numFrames);

%% Right Foot Transformations
RFoot_rotation = initCellArray(numFrames);
V_RFoot_transformed = initCellArray(numFrames);
RFoot_registered_STLpoints = initCellArray(numFrames);
RFoot_translation = initCellArray(numFrames);
RFoot_markerpoints = initCellArray(numFrames);
RFoot_scale = initCellArray(numFrames);
RFAnk_transformed = initNanArray(numFrames);
RCal_transformed = initNanArray(numFrames);
RTMAM_F_transformed = initNanArray(numFrames);
RTMAL_F_transformed = initNanArray(numFrames);
RMet_transformed = initNanArray(numFrames);

%% Left Foot Transformations
LFoot_rotation = initCellArray(numFrames);
V_LFoot_transformed = initCellArray(numFrames);
LFoot_registered_STLpoints = initCellArray(numFrames);
LFoot_translation = initCellArray(numFrames);
LFoot_markerpoints = initCellArray(numFrames);
LFoot_scale = initCellArray(numFrames);
LFAnk_transformed = initNanArray(numFrames);
LCal_transformed = initNanArray(numFrames);
LTMAM_F_transformed = initNanArray(numFrames);
LTMAL_F_transformed = initNanArray(numFrames);
LMet_transformed = initNanArray(numFrames);



%% Step 1: Pelvis Registration and Transformation

% Number of frames
numFrames = length(time);

% Compute mean STL points for normalization
meanPelvisSTLpoints = mean(PelvisSTLpoints);

% scaleMatrixArray stores the frame-by-frame 3D scale matrices.
% The average scale is later used so the bone mesh does not change size
% abruptly from frame to frame.
scaleMatrixArray = nan(3,3,numFrames);

% Perform 3D registration for the pelvis at each time step
for i = 1:numFrames
    % Define STL reference points for pelvis
    STLpoints = PelvisSTLpoints;

    % Reference marker points for pelvis (Femur Right Head, Femur Left Head, Pubic Symphysis)
    Pelvis_markerpoints{i,1} = [F_FRH_S(i,:); F_FLH_S(i,:); F_PS_S(i,:)];

    % Check if current frame index is in CS (cycle steps)
    if ismember(i, CS)
        % Registration with scale adjustment
        [Pelvis_rotation{i,1}, Pelvis_translation{i,1}, Pelvis_scale{i,1}] = ...
            rigid_transform_3D_MA(Pelvis_markerpoints{i,1}, STLpoints);
        scaleMatrixArray(:,:,i) = Pelvis_scale{i,1};
    else
        % Registration without scale adjustment
        [Pelvis_rotation{i,1}, Pelvis_translation{i,1}] = ...
            rigid_transform_3D_MA(Pelvis_markerpoints{i,1}, STLpoints);
    end
end

% Compute mean scale matrix from all transformations
scale = mean(scaleMatrixArray, 3, 'omitnan');

% Apply transformations to each frame
for i = 1:numFrames
    % Extract transformation parameters
    rotation = Pelvis_rotation{i,1};
    translation = Pelvis_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_Pelvis - meanPelvisSTLpoints) * scale' * rotation' + translation;
    V_Pelvis_transformed{i,1} = V_transformed;

    % Transform registered STL points
    Pelvis_registered_STLpoints{i,1} = (PelvisSTLpoints - meanPelvisSTLpoints) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RPHip_transformed(i,:) = V_transformed(I_RPHip,:);
    LPHip_transformed(i,:) = V_transformed(I_LPHip,:);
    RASI_transformed(i,:) = V_transformed(I_RASI,:);
    LASI_transformed(i,:) = V_transformed(I_LASI,:);
    PS_transformed(i,:) = V_transformed(I_PS,:);
end



%% Step 2: Femur Registration and Transformation

% Number of frames
numFrames = length(time);

% Perform 3D registration for femur at each time step
for i = 1:numFrames
    % Right femur marker points
    RFemur_markerpoints{i,1} = [F_FRH_S(i,:); F_FRT_S(i,:); F_FRC_S(i,:)];

    % Left femur marker points
    LFemur_markerpoints{i,1} = [F_FLH_S(i,:); F_FLT_S(i,:); F_FLC_S(i,:)];

    % Check if current frame index is in CS (cycle steps)
    if ismember(i, CS)
        % Registration with scale adjustment
        [RFemur_rotation{i,1}, RFemur_translation{i,1}, RFemur_scale{i,1}] = ...
            rigid_transform_3D_MA(RFemur_markerpoints{i,1}, RFemurSTLpoints);
        [LFemur_rotation{i,1}, LFemur_translation{i,1}, LFemur_scale{i,1}] = ...
            rigid_transform_3D_MA(LFemur_markerpoints{i,1}, LFemurSTLpoints);
    else
        % Registration without scale adjustment
        [RFemur_rotation{i,1}, RFemur_translation{i,1}] = ...
            rigid_transform_3D_MA(RFemur_markerpoints{i,1}, RFemurSTLpoints);
        [LFemur_rotation{i,1}, LFemur_translation{i,1}] = ...
            rigid_transform_3D_MA(LFemur_markerpoints{i,1}, LFemurSTLpoints);
    end
end

% Compute mean scale matrix from all transformations
Femur_scale = [RFemur_scale; LFemur_scale];
scaleMatrixArray = cat(3, Femur_scale{:});
scale = mean(scaleMatrixArray, 3, 'omitnan');

% Apply transformations to each frame
for i = 1:numFrames
    %--------------------- STL Registration for Right Femur------------------------
    rotation = RFemur_rotation{i,1};
    translation = RFemur_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_RFemur - mean(RFemurSTLpoints)) * scale' * rotation' + translation;
    V_RFemur_transformed{i,1} = V_transformed;

    % Transform registered STL points
    RFemur_registered_STLpoints{i,1} = (RFemurSTLpoints - mean(RFemurSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RFH_transformed(i,:) = V_transformed(I_RFH,:);
    RFT_transformed(i,:) = V_transformed(I_RFT,:);
    RFE_transformed(i,:) = V_transformed(I_RFE,:);
    RFKne_transformed(i,:) = V_transformed(I_RFKne,:);
    RFEL_transformed(i,:) = V_transformed(I_RFEL,:);
    RFEM_transformed(i,:) = V_transformed(I_RFEM,:);

    %--------------------- STL Registration for Left Femur------------------------
    rotation = LFemur_rotation{i,1};
    translation = LFemur_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_LFemur - mean(LFemurSTLpoints)) * scale' * rotation' + translation;
    V_LFemur_transformed{i,1} = V_transformed;

    % Transform registered STL points
    LFemur_registered_STLpoints{i,1} = (LFemurSTLpoints - mean(LFemurSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    LFH_transformed(i,:) = V_transformed(I_LFH,:);
    LFT_transformed(i,:) = V_transformed(I_LFT,:);
    LFE_transformed(i,:) = V_transformed(I_LFE,:);
    LFKne_transformed(i,:) = V_transformed(I_LFKne,:);
    LFEL_transformed(i,:) = V_transformed(I_LFEL,:);
    LFEM_transformed(i,:) = V_transformed(I_LFEM,:);
end




%% Step 3: Tibia Registration and Transformation

% Number of frames
numFrames = length(time);

% Perform 3D registration for tibia at each time step
for i = 1:numFrames
    % Right tibia marker points
    RTibia_markerpoints{i,1} = [F_TRP_S(i,:); F_TRH_S(i,:); F_TRD_S(i,:); RFEL_transformed(i,:); RFEM_transformed(i,:)];

    % Left tibia marker points
    LTibia_markerpoints{i,1} = [F_TLP_S(i,:); F_TLH_S(i,:); F_TLD_S(i,:); LFEL_transformed(i,:); LFEM_transformed(i,:)];

    % Check if current frame index is in CS (cycle steps)
    if ismember(i, CS)
        % Registration with scale adjustment
        [RTibia_rotation{i,1}, RTibia_translation{i,1}, RTibia_scale{i,1}] = ...
            rigid_transform_3D_MA(RTibia_markerpoints{i,1}, RTibiaSTLpoints);
        [LTibia_rotation{i,1}, LTibia_translation{i,1}, LTibia_scale{i,1}] = ...
            rigid_transform_3D_MA(LTibia_markerpoints{i,1}, LTibiaSTLpoints);
    else
        % Registration without scale adjustment
        [RTibia_rotation{i,1}, RTibia_translation{i,1}] = ...
            rigid_transform_3D_MA(RTibia_markerpoints{i,1}, RTibiaSTLpoints);
        [LTibia_rotation{i,1}, LTibia_translation{i,1}] = ...
            rigid_transform_3D_MA(LTibia_markerpoints{i,1}, LTibiaSTLpoints);
    end
end

% Compute mean scale matrix from all transformations
Tibia_scale = [RTibia_scale; LTibia_scale];
scaleMatrixArray = cat(3, Tibia_scale{:});
scale = mean(scaleMatrixArray, 3, 'omitnan');

% Apply transformations to each frame
for i = 1:numFrames
    %--------------------- STL Registration for Right Tibia------------------------
    rotation = RTibia_rotation{i,1};
    translation = RTibia_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_RTibia - mean(RTibiaSTLpoints)) * scale' * rotation' + translation;
    V_RTibia_transformed{i,1} = V_transformed;

    % Transform registered STL points
    RTibia_registered_STLpoints{i,1} = (RTibiaSTLpoints - mean(RTibiaSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RTP_transformed(i,:) = V_transformed(I_RTP,:);
    RTH_transformed(i,:) = V_transformed(I_RTH,:);
    RTD_transformed(i,:) = V_transformed(I_RTD,:);
    RTMAM_T_transformed(i,:) = V_transformed(I_RTMAM_T,:);
    RTMAL_T_transformed(i,:) = V_transformed(I_RTMAL_T,:);
    RTKne_transformed(i,:) = V_transformed(I_RTKne,:);
    RTAnk_transformed(i,:) = V_transformed(I_RTAnk,:);
    RTPAL_transformed(i,:) = V_transformed(I_RTPAL,:);
    RTPAM_transformed(i,:) = V_transformed(I_RTPAM,:);

    %--------------------- STL Registration for Left Tibia------------------------
    rotation = LTibia_rotation{i,1};
    translation = LTibia_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_LTibia - mean(LTibiaSTLpoints)) * scale' * rotation' + translation;
    V_LTibia_transformed{i,1} = V_transformed;

    % Transform registered STL points
    LTibia_registered_STLpoints{i,1} = (LTibiaSTLpoints - mean(LTibiaSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    LTP_transformed(i,:) = V_transformed(I_LTP,:);
    LTH_transformed(i,:) = V_transformed(I_LTH,:);
    LTD_transformed(i,:) = V_transformed(I_LTD,:);
    LTMAM_T_transformed(i,:) = V_transformed(I_LTMAM_T,:);
    LTMAL_T_transformed(i,:) = V_transformed(I_LTMAL_T,:);
    LTKne_transformed(i,:) = V_transformed(I_LTKne,:);
    LTAnk_transformed(i,:) = V_transformed(I_LTAnk,:);
    LTPAL_transformed(i,:) = V_transformed(I_LTPAL,:);
    LTPAM_transformed(i,:) = V_transformed(I_LTPAM,:);
end




%% Step 4: Foot Registration and Transformation

% Number of frames
numFrames = length(F_FRH_S);

% Perform 3D registration for foot at each time step
for i = 1:numFrames
    % Right foot marker points
    RFoot_markerpoints{i,1} = [RTMAM_T_transformed(i,:); RTMAL_T_transformed(i,:); F_MR_S(i,:); F_CR_S(i,:)];

    % Left foot marker points
    LFoot_markerpoints{i,1} = [LTMAM_T_transformed(i,:); LTMAL_T_transformed(i,:); F_ML_S(i,:); F_CL_S(i,:)];

    % Check if current frame index is in CS (cycle steps)
    if ismember(i, CS)
        % Registration with scale adjustment
        [RFoot_rotation{i,1}, RFoot_translation{i,1}, RFoot_scale{i,1}] = ...
            rigid_transform_3D_MA(RFoot_markerpoints{i,1}, RFootSTLpoints);
        [LFoot_rotation{i,1}, LFoot_translation{i,1}, LFoot_scale{i,1}] = ...
            rigid_transform_3D_MA(LFoot_markerpoints{i,1}, LFootSTLpoints);
    else
        % Registration without scale adjustment
        [RFoot_rotation{i,1}, RFoot_translation{i,1}] = ...
            rigid_transform_3D_MA(RFoot_markerpoints{i,1}, RFootSTLpoints);
        [LFoot_rotation{i,1}, LFoot_translation{i,1}] = ...
            rigid_transform_3D_MA(LFoot_markerpoints{i,1}, LFootSTLpoints);
    end
end

% Compute mean scale matrix from all transformations
Foot_scale = [RFoot_scale; LFoot_scale];
scaleMatrixArray = cat(3, Foot_scale{:});
scale = mean(scaleMatrixArray, 3, 'omitnan');

% Apply transformations to each frame
for i = 1:numFrames
    %--------------------- STL Registration for Right Foot------------------------
    rotation = RFoot_rotation{i,1};
    translation = RFoot_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_RFoot - mean(RFootSTLpoints)) * scale' * rotation' + translation;
    V_RFoot_transformed{i,1} = V_transformed;

    % Transform registered STL points
    RFoot_registered_STLpoints{i,1} = (RFootSTLpoints - mean(RFootSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RTMAM_F_transformed(i,:) = V_transformed(I_RTMAM_F,:);
    RTMAL_F_transformed(i,:) = V_transformed(I_RTMAL_F,:);
    RFAnk_transformed(i,:) = V_transformed(I_RFAnk,:);
    RCal_transformed(i,:) = V_transformed(I_RCal,:);
    RMet_transformed(i,:) = V_transformed(I_RMet,:);

    %--------------------- STL Registration for Left Foot------------------------
    rotation = LFoot_rotation{i,1};
    translation = LFoot_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_LFoot - mean(LFootSTLpoints)) * scale' * rotation' + translation;
    V_LFoot_transformed{i,1} = V_transformed;

    % Transform registered STL points
    LFoot_registered_STLpoints{i,1} = (LFootSTLpoints - mean(LFootSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    LTMAM_F_transformed(i,:) = V_transformed(I_LTMAM_F,:);
    LTMAL_F_transformed(i,:) = V_transformed(I_LTMAL_F,:);
    LFAnk_transformed(i,:) = V_transformed(I_LFAnk,:);
    LCal_transformed(i,:) = V_transformed(I_LCal,:);
    LMet_transformed(i,:) = V_transformed(I_LMet,:);
end




%% Step 5: Weight joint-axis points for femur registration
% This second pass improves joint-axis consistency.
%
% repeat_counts = [MWF, MWF, 1, 1, 1] means:
%   - The first two points are joint-axis points and are repeated MWF times.
%   - The remaining anatomical landmarks are used once.
%
% Larger MWF gives joint-axis points stronger influence during registration.
% MWF = 1 gives all points equal influence.

% Number of frames
numFrames = length(F_FRH_S);

for i = 1:numFrames
    %---------------------------------- 3D Points Registration for Right Femur -------------------------------------
    RSTLpoints = [RFEM_transformed(i,:); RFEL_transformed(i,:); ...
                  RFH_transformed(i,:); RFT_transformed(i,:); RFE_transformed(i,:)];

    % Define the repeat counts for each point
    repeat_counts = [MWF, MWF, 1, 1, 1]; % Repeat the first and second points MWF times, others once

    % Repeat the marker points based on the specified counts
    RFemur_markerpoints{i,1} = repeat_coordinates([RTPAM_transformed(i,:); RTPAL_transformed(i,:); ...
                                                   F_FRH_S(i,:); F_FRT_S(i,:); F_FRC_S(i,:)], repeat_counts);

    % Repeat the corresponding STL points
    RSTLpoints_repeated = repeat_coordinates(RSTLpoints, repeat_counts);

    % Perform the rigid transformation
    [RFemur_rotation{i,1}, RFemur_translation{i,1}] = ...
        rigid_transform_3D_MA(RFemur_markerpoints{i,1}, RSTLpoints_repeated);

    %---------------------------------- 3D Points Registration for Left Femur -------------------------------------
    LSTLpoints = [LFEM_transformed(i,:); LFEL_transformed(i,:); ...
                  LFH_transformed(i,:); LFT_transformed(i,:); LFE_transformed(i,:)];

    % Repeat the marker points based on the specified counts
    LFemur_markerpoints{i,1} = repeat_coordinates([LTPAM_transformed(i,:); LTPAL_transformed(i,:); ...
                                                   F_FLH_S(i,:); F_FLT_S(i,:); F_FLC_S(i,:)], repeat_counts);

    % Repeat the corresponding STL points
    LSTLpoints_repeated = repeat_coordinates(LSTLpoints, repeat_counts);

    % Perform the rigid transformation
    [LFemur_rotation{i,1}, LFemur_translation{i,1}] = ...
        rigid_transform_3D_MA(LFemur_markerpoints{i,1}, LSTLpoints_repeated);

    %---------------------------------- STL Registration for Right Femur -------------------------------------
    rotation = RFemur_rotation{i,1};
    translation = RFemur_translation{i,1};

    scale = eye(3); % Identity matrix for scale

    % Transform STL vertices
    V_transformed = (V_RFemur_transformed{i,:} - mean(RSTLpoints_repeated)) * scale' * rotation' + translation;
    V_RFemur_transformed{i,1} = V_transformed;

    % Transform registered STL points
    RFemur_registered_STLpoints{i,1} = (RFemur_registered_STLpoints{i,1} - mean(RSTLpoints_repeated)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RFH_transformed(i,:) = V_transformed(I_RFH,:);
    RFT_transformed(i,:) = V_transformed(I_RFT,:);
    RFE_transformed(i,:) = V_transformed(I_RFE,:);
    RFKne_transformed(i,:) = V_transformed(I_RFKne,:);
    RFEL_transformed(i,:) = V_transformed(I_RFEL,:);
    RFEM_transformed(i,:) = V_transformed(I_RFEM,:);

    %---------------------------------- STL Registration for Left Femur -------------------------------------
    rotation = LFemur_rotation{i,1};
    translation = LFemur_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_LFemur_transformed{i,:} - mean(LSTLpoints_repeated)) * scale' * rotation' + translation;
    V_LFemur_transformed{i,1} = V_transformed;

    % Transform registered STL points
    LFemur_registered_STLpoints{i,1} = (LFemur_registered_STLpoints{i,1} - mean(LFemurSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    LFH_transformed(i,:) = V_transformed(I_LFH,:);
    LFT_transformed(i,:) = V_transformed(I_LFT,:);
    LFE_transformed(i,:) = V_transformed(I_LFE,:);
    LFKne_transformed(i,:) = V_transformed(I_LFKne,:);
    LFEL_transformed(i,:) = V_transformed(I_LFEL,:);
    LFEM_transformed(i,:) = V_transformed(I_LFEM,:);
end


%% Step 6: Weight joint-axis points for tibia registration
% Same logic as Step 5. The first two repeated points represent the knee
% joint-axis relationship between femur and tibia.

% Number of frames
numFrames = length(F_FRH_S);

for i = 1:numFrames
    %---------------------------------- 3D Points Registration for Right Tibia -------------------------------------
    RSTLpoints = [RTPAM_transformed(i,:); RTPAL_transformed(i,:); RTP_transformed(i,:); 
                  RTH_transformed(i,:); RTD_transformed(i,:)];

    % Define the repeat counts for weighting
    repeat_counts = [MWF, MWF, 1, 1, 1];

    % Repeat the marker points based on the specified counts
    RTibia_markerpoints{i,1} = repeat_coordinates([RFEM_transformed(i,:); RFEL_transformed(i,:); 
                                                   F_TRP_S(i,:); F_TRH_S(i,:); F_TRD_S(i,:)], repeat_counts);

    % Repeat the corresponding STL points
    RSTLpoints_repeated = repeat_coordinates(RSTLpoints, repeat_counts);

    % Perform the rigid transformation
    [RTibia_rotation{i,1}, RTibia_translation{i,1}] = ...
        rigid_transform_3D_MA(RTibia_markerpoints{i,1}, RSTLpoints_repeated);

    %---------------------------------- 3D Points Registration for Left Tibia -------------------------------------
    LSTLpoints = [LTPAM_transformed(i,:); LTPAL_transformed(i,:); LTP_transformed(i,:); 
                  LTH_transformed(i,:); LTD_transformed(i,:)];

    % Repeat the marker points based on the specified counts
    LTibia_markerpoints{i,1} = repeat_coordinates([LFEM_transformed(i,:); LFEL_transformed(i,:); 
                                                   F_TLP_S(i,:); F_TLH_S(i,:); F_TLD_S(i,:)], repeat_counts);

    % Repeat the corresponding STL points
    LSTLpoints_repeated = repeat_coordinates(LSTLpoints, repeat_counts);

    % Perform the rigid transformation
    [LTibia_rotation{i,1}, LTibia_translation{i,1}] = ...
        rigid_transform_3D_MA(LTibia_markerpoints{i,1}, LSTLpoints_repeated);

    %---------------------------------- STL Registration for Right Tibia -------------------------------------
    rotation = RTibia_rotation{i,1};
    translation = RTibia_translation{i,1};
    scale = eye(3);

    % Transform STL vertices
    V_transformed = (V_RTibia_transformed{i,:} - mean(RSTLpoints_repeated)) * scale' * rotation' + translation;
    V_RTibia_transformed{i,1} = V_transformed;

    % Transform registered STL points
    RTibia_registered_STLpoints{i,1} = (RTibia_registered_STLpoints{i,1} - mean(RSTLpoints_repeated)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RTP_transformed(i,:) = V_transformed(I_RTP,:);
    RTH_transformed(i,:) = V_transformed(I_RTH,:);
    RTD_transformed(i,:) = V_transformed(I_RTD,:);
    RTMAM_T_transformed(i,:) = V_transformed(I_RTMAM_T,:);
    RTMAL_T_transformed(i,:) = V_transformed(I_RTMAL_T,:);
    RTKne_transformed(i,:) = V_transformed(I_RTKne,:);
    RTAnk_transformed(i,:) = V_transformed(I_RTAnk,:);
    RTPAL_transformed(i,:) = V_transformed(I_RTPAL,:);
    RTPAM_transformed(i,:) = V_transformed(I_RTPAM,:);

    %---------------------------------- STL Registration for Left Tibia -------------------------------------
    rotation = LTibia_rotation{i,1};
    translation = LTibia_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_LTibia_transformed{i,:} - mean(LSTLpoints_repeated)) * scale' * rotation' + translation;
    V_LTibia_transformed{i,1} = V_transformed;

    % Transform registered STL points
    LTibia_registered_STLpoints{i,1} = (LTibia_registered_STLpoints{i,1} - mean(LTibiaSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    LTP_transformed(i,:) = V_transformed(I_LTP,:);
    LTH_transformed(i,:) = V_transformed(I_LTH,:);
    LTD_transformed(i,:) = V_transformed(I_LTD,:);
    LTMAM_T_transformed(i,:) = V_transformed(I_LTMAM_T,:);
    LTMAL_T_transformed(i,:) = V_transformed(I_LTMAL_T,:);
    LTKne_transformed(i,:) = V_transformed(I_LTKne,:);
    LTAnk_transformed(i,:) = V_transformed(I_LTAnk,:);
    LTPAL_transformed(i,:) = V_transformed(I_LTPAL,:);
    LTPAM_transformed(i,:) = V_transformed(I_LTPAM,:);
end


%% Step 7: Weight joint-axis points for foot registration
% The first two repeated points represent the ankle/tibia-foot contact axis.
% repeat_counts = [MWF, MWF, 1, 1] weights those two axis points.

for i = 1:numFrames
    %---------------------------------- 3D Points Registration for Right Foot -------------------------------------
    RSTLpoints = [RTMAM_F_transformed(i,:); RTMAL_F_transformed(i,:); RMet_transformed(i,:); RCal_transformed(i,:)];

    % Define the repeat counts for weighting
    repeat_counts = [MWF, MWF, 1, 1];

    % Repeat the marker points based on the specified counts
    RFoot_markerpoints{i,1} = repeat_coordinates([RTMAM_T_transformed(i,:); RTMAL_T_transformed(i,:); 
                                                  F_MR_S(i,:); F_CR_S(i,:)], repeat_counts);

    % Repeat the corresponding STL points
    RSTLpoints_repeated = repeat_coordinates(RSTLpoints, repeat_counts);

    % Perform the rigid transformation
    [RFoot_rotation{i,1}, RFoot_translation{i,1}] = ...
        rigid_transform_3D_MA(RFoot_markerpoints{i,1}, RSTLpoints_repeated);

    %---------------------------------- 3D Points Registration for Left Foot -------------------------------------
    LSTLpoints = [LTMAM_F_transformed(i,:); LTMAL_F_transformed(i,:); LMet_transformed(i,:); LCal_transformed(i,:)];

    % Repeat the marker points based on the specified counts
    LFoot_markerpoints{i,1} = repeat_coordinates([LTMAM_T_transformed(i,:); LTMAL_T_transformed(i,:); 
                                                  F_ML_S(i,:); F_CL_S(i,:)], repeat_counts);

    % Repeat the corresponding STL points
    LSTLpoints_repeated = repeat_coordinates(LSTLpoints, repeat_counts);

    % Perform the rigid transformation
    [LFoot_rotation{i,1}, LFoot_translation{i,1}] = ...
        rigid_transform_3D_MA(LFoot_markerpoints{i,1}, LSTLpoints_repeated);

    %---------------------------------- STL Registration for Right Foot -------------------------------------
    rotation = RFoot_rotation{i,1};
    translation = RFoot_translation{i,1};
    scale = eye(3);

    % Transform STL vertices
    V_transformed = (V_RFoot_transformed{i,:} - mean(RSTLpoints_repeated)) * scale' * rotation' + translation;
    V_RFoot_transformed{i,1} = V_transformed;

    % Transform registered STL points
    RFoot_registered_STLpoints{i,1} = (RFoot_registered_STLpoints{i,1} - mean(RSTLpoints_repeated)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    RTMAM_F_transformed(i,:) = V_transformed(I_RTMAM_F,:);
    RTMAL_F_transformed(i,:) = V_transformed(I_RTMAL_F,:);
    RFAnk_transformed(i,:) = V_transformed(I_RFAnk,:);
    RCal_transformed(i,:) = V_transformed(I_RCal,:);
    RMet_transformed(i,:) = V_transformed(I_RMet,:);

    %---------------------------------- STL Registration for Left Foot -------------------------------------
    rotation = LFoot_rotation{i,1};
    translation = LFoot_translation{i,1};

    % Transform STL vertices
    V_transformed = (V_LFoot_transformed{i,:} - mean(LSTLpoints_repeated)) * scale' * rotation' + translation;
    V_LFoot_transformed{i,1} = V_transformed;

    % Transform registered STL points
    LFoot_registered_STLpoints{i,1} = (LFoot_registered_STLpoints{i,1} - mean(LFootSTLpoints)) * scale' * rotation' + translation;

    % Update transformed anatomical landmarks
    LTMAM_F_transformed(i,:) = V_transformed(I_LTMAM_F,:);
    LTMAL_F_transformed(i,:) = V_transformed(I_LTMAL_F,:);
    LFAnk_transformed(i,:) = V_transformed(I_LFAnk,:);
    LCal_transformed(i,:) = V_transformed(I_LCal,:);
    LMet_transformed(i,:) = V_transformed(I_LMet,:);
end


elapsedTime = toc; % End timing and compute elapsed time
fprintf('Elapsed Time: %f seconds\n', elapsedTime);


%% Local helper function
function [minDistance, closestIndex] = findClosestSTLPoint(vertices, marker)
%FINDCLOSESTSTLPOINT Find the closest STL vertex to one anatomical point.
%
% Inputs
% ------
% vertices : Nx3 matrix
%   STL mesh vertices.
%
% marker : 1x3 vector
%   Anatomical landmark coordinate.
%
% Outputs
% -------
% minDistance : scalar
%   Distance from marker to the closest STL vertex.
%
% closestIndex : scalar
%   Row index of the closest STL vertex in vertices.

    distances = sqrt(sum((vertices - marker).^2, 2));
    [minDistance, closestIndex] = min(distances);
end
