% -------------------------------------------------------------------------
% B02_Plot_Filtered_Vs_Raw.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   This script compares raw and filtered 3D marker trajectories.
%   It creates one figure per marker, with three panels for X, Y, and Z.
%
% Expected workspace variables:
%   AllMarkers_S   : Raw marker coordinates after axis swapping.
%                    Size = number of frames x 3*number of markers.
%   F_AllMarkers_S : Filtered marker coordinates after axis swapping.
%                    Size must match AllMarkers_S.
%
% Typical use:
%   Run B01_Registration_WithoutFlow_3DScale_WithMWF.m first, then run this
%   script from the same MATLAB workspace.
% -------------------------------------------------------------------------

%% -------------------------- User parameters -----------------------------

% Marker names in the same order used when AllMarkers_S and F_AllMarkers_S
% were built in B01. Each marker has 3 columns: X, Y, and Z.
markerNames = {'CL', 'CR', 'FLC', 'FLH', 'FLT', 'FRC', 'FRH', 'FRT', ...
               'ML', 'MR', 'PS', 'TLD', 'TLH', 'TLP', 'TRD', 'TRH', 'TRP'};

coordinateNames = {'X', 'Y', 'Z'};       % Coordinate labels
coordinateUnit  = 'cm';                  % Coordinate unit used in the plots

useTimeIfAvailable = true;               % true: use variable time if it exists
closeExistingFigures = false;            % true: close all figures before plotting
saveFigures = false;                     % true: save each marker figure
outputFolder = 'B02_Filtered_vs_Raw';     % Folder for saved figures
saveFormat = 'png';                      % Options: 'png', 'fig', or 'pdf'

figurePosition = [100 100 900 700];      % [left bottom width height]
rawLineStyle = 'b-';                     % Raw data line style
filteredLineStyle = 'r-';                % Filtered data line style
lineWidth = 1.2;                         % Plot line width

%% ----------------------------- Checks -----------------------------------

% This script is designed to be run after B01, so these variables should
% already be present in the MATLAB workspace.
if ~exist('AllMarkers_S', 'var')
    error('AllMarkers_S was not found. Run B01 before this script.');
end

if ~exist('F_AllMarkers_S', 'var')
    error('F_AllMarkers_S was not found. Run B01 before this script.');
end

rawData = AllMarkers_S;
filteredData = F_AllMarkers_S;

if ~isequal(size(rawData), size(filteredData))
    error('AllMarkers_S and F_AllMarkers_S must have the same size.');
end

numFrames = size(rawData, 1);
numColumns = size(rawData, 2);
numMarkers = numel(markerNames);

if numColumns ~= 3*numMarkers
    error(['The number of columns in AllMarkers_S does not match markerNames. ', ...
           'Expected %d columns, but found %d.'], 3*numMarkers, numColumns);
end

% Use time on the x-axis if a valid time vector exists; otherwise use sample
% number. This keeps the script useful for both quick checks and final plots.
if useTimeIfAvailable && exist('time', 'var') && numel(time) == numFrames
    xData = time(:);
    xLabelText = 'Time, s';
else
    xData = (1:numFrames)';
    xLabelText = 'Sample number';
end

if closeExistingFigures
    close all;
end

if saveFigures && ~exist(outputFolder, 'dir')
    mkdir(outputFolder);
end

%% ----------------------------- Plotting ---------------------------------

for markerIdx = 1:numMarkers

    markerName = markerNames{markerIdx};

    % Column indices for the current marker: [X, Y, Z].
    colStart = (markerIdx - 1)*3 + 1;
    markerCols = colStart:(colStart + 2);

    hFig = figure('Name', markerName, ...
                  'Color', 'w', ...
                  'Position', figurePosition);

    for coordIdx = 1:3

        subplot(3, 1, coordIdx);
        hold on;

        plot(xData, rawData(:, markerCols(coordIdx)), ...
             rawLineStyle, 'LineWidth', lineWidth, 'DisplayName', 'Raw');

        plot(xData, filteredData(:, markerCols(coordIdx)), ...
             filteredLineStyle, 'LineWidth', lineWidth, 'DisplayName', 'Filtered');

        hold off;
        grid on;
        box on;

        ylabel(sprintf('%s, %s', coordinateNames{coordIdx}, coordinateUnit));

        if coordIdx == 1
            title(sprintf('%s: Raw vs. Filtered', markerName), ...
                  'Interpreter', 'none');
            legend('Location', 'best');
        end

        if coordIdx == 3
            xlabel(xLabelText);
        end
    end

    %% Save figure if requested
    if saveFigures
        outputName = sprintf('%s_raw_vs_filtered.%s', markerName, saveFormat);
        outputPath = fullfile(outputFolder, outputName);

        switch lower(saveFormat)
            case 'fig'
                savefig(hFig, outputPath);
            case 'pdf'
                exportgraphics(hFig, outputPath, 'ContentType', 'vector');
            otherwise
                exportgraphics(hFig, outputPath, 'Resolution', 300);
        end
    end
end

fprintf('Done. Plotted raw vs. filtered trajectories for %d markers.\n', numMarkers);
