% -------------------------------------------------------------------------
% B02_Animation.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Creates an MP4 animation of the registered rat skeletal model.
%   This script is designed to run after:
%       B01_Registration_WithoutFlow_3DScale_WithMWF.m
%
% Notes:
%   - Press "Stop and save" to stop the animation early.
%   - The figure stays open after pressing Stop.
%   - The video is saved up to the last completed frame.
%   - The Stop button is not written into the video because only the axes
%     are captured.
% -------------------------------------------------------------------------

%% -------------------------- User parameters -----------------------------

videoFileName = 'rat_walking_animation.mp4';   % Output animation name
videoQuality  = 100;                           % MPEG-4 quality: 0 to 100
videoFrameRate = 25;                           % Frames per second in saved video

figurePosition = [0 0 1920 1080];              % [left bottom width height]
figureColor    = 'w';                          % White figure background

frameStride = 1;                               % 1 = use every frame in CS; 5 = every 5th frame
saveFramesAsImages = false;                    % true saves each video frame as JPG
frameImageFolder   = 'B02_Animation_Frames';   % Folder for JPG frames if enabled
frameImageQuality  = 100;                      % JPG quality: 0 to 100

boneColor = [0.8 0.8 1.0];                     % Light blue-gray bone color
boneAlpha = 0.5;                               % Bone transparency: 1 = solid, 0 = invisible

markerSizeSTL      = 7;                        % STL anatomical landmark points
markerSizeTracked  = 10;                       % Tracked/labeled marker points
markerSizeJoint    = 10;                       % Joint-axis/constraint points
markerLineWidth    = 2;                        % Marker outline width

viewAzimuthDeg   = 90;                         % Camera azimuth angle
viewElevationDeg = 0;                          % Camera elevation angle
lightAzimuthDeg  = 0;                          % Light source azimuth
lightElevationDeg = viewElevationDeg;          % Light source elevation

axisPadXY_cm     = 0.5;                        % Padding around X/Y marker limits
axisPadZLow_cm   = 0.5;                        % Padding below Z marker limits
axisPadZHigh_cm  = 1.5;                        % Padding above Z marker limits

closeFigureAfterAnimation = false;             % Keep figure open after animation/Stop

%% -------------------------- Safety checks --------------------------------

requiredVars = {'CS', ...
    'V_RFemur_transformed','V_LFemur_transformed','V_Pelvis_transformed', ...
    'V_RTibia_transformed','V_LTibia_transformed','V_RFoot_transformed','V_LFoot_transformed', ...
    'F_RFemur','F_LFemur','F_Pelvis','F_RTibia','F_LTibia','F_RFoot','F_LFoot', ...
    'F_AllMarkers_S_X','F_AllMarkers_S_Y','F_AllMarkers_S_Z'};

for k = 1:numel(requiredVars)
    if ~exist(requiredVars{k}, 'var')
        error('Missing variable "%s". Run B01 before running B02_Animation.', requiredVars{k});
    end
end

frameStride = max(1, round(frameStride));
frameList = CS(1:frameStride:end);

if isempty(frameList)
    error('CS is empty. There are no frames to animate.');
end

if saveFramesAsImages && ~exist(frameImageFolder, 'dir')
    mkdir(frameImageFolder);
end

%% -------------------------- Figure setup --------------------------------

hFig = figure('Position', figurePosition, ...
              'Color', figureColor, ...
              'Name', 'B02 Animation', ...
              'NumberTitle', 'off', ...
              'Resize', 'off');

ax = axes('Parent', hFig);
hold(ax, 'on');
axis(ax, 'equal');
box(ax, 'on');
grid(ax, 'off');
xlabel(ax, 'X, cm');
ylabel(ax, 'Y, cm');
zlabel(ax, 'Z, cm');

% Stop flag. The button changes this flag, but does not close the figure.
setappdata(hFig, 'StopAnimation', false);

uicontrol('Parent', hFig, ...
          'Style', 'pushbutton', ...
          'String', 'Stop and save', ...
          'Units', 'normalized', ...
          'Position', [0.84 0.94 0.14 0.04], ...
          'FontSize', 11, ...
          'Callback', ['setappdata(gcbf,''StopAnimation'',true); ', ...
                       'set(gcbo,''String'',''Stopping...''); ', ...
                       'drawnow;']);

% If the user closes the window with X, stop the loop and delete the figure.
set(hFig, 'CloseRequestFcn', ['setappdata(gcbf,''StopAnimation'',true); ', ...
                              'delete(gcbf);']);

%% -------------------------- Video setup ---------------------------------

[videoFolder, videoBase, videoExt] = fileparts(videoFileName);

if isempty(videoFolder)
    videoFolder = pwd;
end

if isempty(videoExt)
    videoExt = '.mp4';
end

videoFilePath = fullfile(videoFolder, [videoBase, videoExt]);

% Do not overwrite an existing video. This avoids Permission Denied if the
% previous MP4 is open in another program.
if isfile(videoFilePath)
    videoFilePath = fullfile(videoFolder, sprintf('%s_%s%s', ...
        videoBase, datestr(now, 'yyyymmdd_HHMMSS'), videoExt));
end

try
    Video = VideoWriter(videoFilePath, 'MPEG-4');
    Video.Quality = videoQuality;
    Video.FrameRate = videoFrameRate;
    open(Video);
catch
    % If the current folder is not writable, use MATLAB's temporary folder.
    videoFilePath = fullfile(tempdir, sprintf('%s_%s%s', ...
        videoBase, datestr(now, 'yyyymmdd_HHMMSS'), videoExt));

    Video = VideoWriter(videoFilePath, 'MPEG-4');
    Video.Quality = videoQuality;
    Video.FrameRate = videoFrameRate;
    open(Video);
end

videoIsOpen = true;

fprintf('Saving animation to:\n%s\n\n', videoFilePath);
fprintf('Press "Stop and save" to stop early. The figure will stay open.\n\n');

%% -------------------------- Fixed axis limits ---------------------------

xLimits = [min(F_AllMarkers_S_X(:)) - axisPadXY_cm, ...
           max(F_AllMarkers_S_X(:)) + axisPadXY_cm];

yLimits = [min(F_AllMarkers_S_Y(:)) - axisPadXY_cm, ...
           max(F_AllMarkers_S_Y(:)) + axisPadXY_cm];

zLimits = [min(F_AllMarkers_S_Z(:)) - axisPadZLow_cm, ...
           max(F_AllMarkers_S_Z(:)) + axisPadZHigh_cm];

%% -------------------------- Animation loop ------------------------------

try
    for frameCounter = 1:numel(frameList)

        if ~ishandle(hFig) || getappdata(hFig, 'StopAnimation')
            fprintf('Animation stopped by user.\n');
            break;
        end

        t = frameList(frameCounter);
        fprintf('Frame %d of %d  |  frame number: %d\n', frameCounter, numel(frameList), t);

        cla(ax);
        hold(ax, 'on');
        axis(ax, 'equal');
        box(ax, 'on');
        grid(ax, 'off');

        axes(ax); %#ok<LAXES>
        camlight(lightAzimuthDeg, lightElevationDeg);
        lighting gouraud;

        %% --------------------- Plot pelvis ------------------------------
        V = V_Pelvis_transformed{t,1};
        F = F_Pelvis;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V(I_RPHip,1), V(I_RPHip,2), V(I_RPHip,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_LPHip,1), V(I_LPHip,2), V(I_LPHip,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_PS,1),    V(I_PS,2),    V(I_PS,3),    'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, Pelvis_markerpoints{t,1}(:,1), Pelvis_markerpoints{t,1}(:,2), Pelvis_markerpoints{t,1}(:,3), ...
            'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- Plot right femur -------------------------
        V = V_RFemur_transformed{t,1};
        F = F_RFemur;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V(I_RFH,1), V(I_RFH,2), V(I_RFH,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_RFT,1), V(I_RFT,2), V(I_RFT,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_RFE,1), V(I_RFE,2), V(I_RFE,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V([I_RFEL I_RFEM],1), V([I_RFEL I_RFEM],2), V([I_RFEL I_RFEM],3), ...
            'o', 'MarkerSize', markerSizeJoint, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'b', 'LineWidth', markerLineWidth);
        P = RFemur_markerpoints{t,1};
        nP = size(P, 1);
        P = P(max(1, nP-2):nP,:);
        plot3(ax, P(:,1), P(:,2), P(:,3), 'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- Plot left femur --------------------------
        V = V_LFemur_transformed{t,1};
        F = F_LFemur;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V(I_LFH,1), V(I_LFH,2), V(I_LFH,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_LFT,1), V(I_LFT,2), V(I_LFT,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_LFE,1), V(I_LFE,2), V(I_LFE,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V([I_LFEL I_LFEM],1), V([I_LFEL I_LFEM],2), V([I_LFEL I_LFEM],3), ...
            'o', 'MarkerSize', markerSizeJoint, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'b', 'LineWidth', markerLineWidth);
        P = LFemur_markerpoints{t,1};
        nP = size(P, 1);
        P = P(max(1, nP-2):nP,:);
        plot3(ax, P(:,1), P(:,2), P(:,3), 'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- Plot right tibia -------------------------
        V = V_RTibia_transformed{t,1};
        F = F_RTibia;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V(I_RTP,1), V(I_RTP,2), V(I_RTP,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_RTH,1), V(I_RTH,2), V(I_RTH,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_RTD,1), V(I_RTD,2), V(I_RTD,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V([I_RTPAL I_RTPAM],1), V([I_RTPAL I_RTPAM],2), V([I_RTPAL I_RTPAM],3), ...
            'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'b', 'MarkerEdgeColor', 'b');
        plot3(ax, V([I_RTMAM_T I_RTMAL_T],1), V([I_RTMAM_T I_RTMAL_T],2), V([I_RTMAM_T I_RTMAL_T],3), ...
            'o', 'MarkerSize', markerSizeJoint, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'b', 'LineWidth', markerLineWidth);
        P = RTibia_markerpoints{t,1};
        nP = size(P, 1);
        P = P(max(1, nP-2):nP,:);
        plot3(ax, P(:,1), P(:,2), P(:,3), 'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- Plot left tibia --------------------------
        V = V_LTibia_transformed{t,1};
        F = F_LTibia;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V(I_LTP,1), V(I_LTP,2), V(I_LTP,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_LTH,1), V(I_LTH,2), V(I_LTH,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V(I_LTD,1), V(I_LTD,2), V(I_LTD,3), 'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V([I_LTPAL I_LTPAM],1), V([I_LTPAL I_LTPAM],2), V([I_LTPAL I_LTPAM],3), ...
            'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'b', 'MarkerEdgeColor', 'b');
        plot3(ax, V([I_LTMAM_T I_LTMAL_T],1), V([I_LTMAM_T I_LTMAL_T],2), V([I_LTMAM_T I_LTMAL_T],3), ...
            'o', 'MarkerSize', markerSizeJoint, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'b', 'LineWidth', markerLineWidth);
        P = LTibia_markerpoints{t,1};
        nP = size(P, 1);
        P = P(max(1, nP-2):nP,:);
        plot3(ax, P(:,1), P(:,2), P(:,3), 'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- Plot right foot --------------------------
        V = V_RFoot_transformed{t,1};
        F = F_RFoot;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V([I_RCal I_RMet],1), V([I_RCal I_RMet],2), V([I_RCal I_RMet],3), ...
            'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V([I_RTMAM_F I_RTMAL_F],1), V([I_RTMAM_F I_RTMAL_F],2), V([I_RTMAM_F I_RTMAL_F],3), ...
            'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'b', 'MarkerEdgeColor', 'b');
        P = RFoot_markerpoints{t,1};
        nP = size(P, 1);
        P = P(max(1, nP-1):nP,:);
        plot3(ax, P(:,1), P(:,2), P(:,3), 'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- Plot left foot ---------------------------
        V = V_LFoot_transformed{t,1};
        F = F_LFoot;
        patch(ax, 'Faces', F, 'Vertices', V, 'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);
        plot3(ax, V([I_LCal I_LMet],1), V([I_LCal I_LMet],2), V([I_LCal I_LMet],3), ...
            'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'r');
        plot3(ax, V([I_LTMAM_F I_LTMAL_F],1), V([I_LTMAM_F I_LTMAL_F],2), V([I_LTMAM_F I_LTMAL_F],3), ...
            'o', 'MarkerSize', markerSizeSTL, 'MarkerFaceColor', 'b', 'MarkerEdgeColor', 'b');
        P = LFoot_markerpoints{t,1};
        nP = size(P, 1);
        P = P(max(1, nP-1):nP,:);
        plot3(ax, P(:,1), P(:,2), P(:,3), 'o', 'MarkerSize', markerSizeTracked, 'MarkerFaceColor', 'none', 'MarkerEdgeColor', 'k', 'LineWidth', markerLineWidth);

        %% --------------------- View and save frame ----------------------
        xlabel(ax, 'X, cm');
        ylabel(ax, 'Y, cm');
        zlabel(ax, 'Z, cm');
        title(ax, ['Frame: ', num2str(t)]);

        view(ax, viewAzimuthDeg, viewElevationDeg);
        xlim(ax, xLimits);
        ylim(ax, yLimits);
        zlim(ax, zLimits);

        drawnow;

        if ~ishandle(hFig) || getappdata(hFig, 'StopAnimation')
            fprintf('Animation stopped before writing frame %d.\n', t);
            break;
        end

        % Capture only the axes, not the Stop button.
        frame = getframe(ax);
        writeVideo(Video, frame);

        if saveFramesAsImages
            img = frame2im(frame);
            frameFileName = fullfile(frameImageFolder, sprintf('frame_%04d.jpg', t));
            imwrite(img, frameFileName, 'jpg', 'Quality', frameImageQuality);
        end
    end

catch ME
    if exist('Video', 'var') && videoIsOpen
        try
            close(Video);
            videoIsOpen = false;
        catch
        end
    end

    if ishandle(hFig)
        set(hFig, 'CloseRequestFcn', 'closereq');
    end

    rethrow(ME);
end

%% -------------------------- Finish --------------------------------------

if exist('Video', 'var') && videoIsOpen
    close(Video);
    videoIsOpen = false;
end

if ishandle(hFig)
    set(hFig, 'CloseRequestFcn', 'closereq');
    set(hFig, 'Pointer', 'arrow');

    if closeFigureAfterAnimation
        delete(hFig);
    end
end

fprintf('\nAnimation saved successfully:\n%s\n', videoFilePath);
