% -------------------------------------------------------------------------
% B04_Stick_Animation_JointAxes_NotDotted.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Creates a stick-model animation of rat locomotion with local joint axes.
%
%   This script is designed to run after:
%       B01_Registration_WithoutFlow_3DScale_WithMWF.m
%       B03_Kinematics_3D_And_Cycles_R1_MLaxis.m
%
%   B01 provides the filtered marker trajectories.
%   B03 provides the pelvis, femur, tibia/leg, and foot local axes.
%
% Notes:
%   1. Press "Stop and save" to stop early and save the video up to the
%      last completed frame.
%   2. Closing the figure window also stops the animation and safely closes
%      the MP4 file.
%   3. If the MP4 already exists or is open/locked, a timestamped filename
%      is created automatically.
% -------------------------------------------------------------------------

%% -------------------------- User parameters -----------------------------

videoFileName  = 'rat_stick_joint_axes_animation.mp4';  % Output animation name
videoQuality   = 100;                                  % MPEG-4 quality: 0 to 100
videoFrameRate = 25;                                   % Frames per second in saved video

figurePosition = [0 0 1920 1080];                      % [left bottom width height]
figureColor    = 'w';                                  % White figure background

frameStride = 1;                                       % 1 = use every frame in CS; 5 = every 5th frame
saveFramesAsImages = false;                            % true saves each video frame as JPG
frameImageFolder   = 'B04_Stick_Animation_Frames';     % Folder for JPG frames if enabled
frameImageQuality  = 100;                              % JPG quality: 0 to 100

showStickModel = true;                                 % true = show triangular stick segments
showJointAxes  = true;                                 % true = show local i/j/k axes

stickAlpha = 0.85;                                     % Stick patch transparency
stickEdgeColor = [0.2 0.2 0.2];                        % Stick patch edge color
stickLineWidth = 0.75;                                 % Stick patch edge thickness

axisScalePelvis = 0.5;                                 % Pelvis local-axis length
axisScaleSegment = 1.0;                                % Limb local-axis length
axisLineWidth = 2;                                     % Local-axis line width

% Local-axis color convention:
%   i-axis = black
%   j-axis = red
%   k-axis = blue
axisColor_i = [0 0 0];
axisColor_j = [1 0 0];
axisColor_k = [0 0 1];

% Segment colors
colorPelvis = [1.0 0.6 0.6];                           % Light red
colorFemur  = [0.6784 0.8471 0.9020];                  % Light blue
colorLeg    = [0.6 1.0 0.6];                           % Light green
colorFoot   = [0.8784 1.0 1.0];                        % Light cyan

viewAzimuthDeg   = 60;                                 % Camera azimuth angle
viewElevationDeg = 30;                                 % Camera elevation angle

axisPadXY_cm    = 0.5;                                 % Padding around X/Y marker limits
axisPadZLow_cm  = 0.5;                                 % Padding below Z marker limits
axisPadZHigh_cm = 0.5;                                 % Padding above Z marker limits

showLegend = true;                                     % true = show i/j/k legend
legendLocation = 'northeast';                          % Fixed legend location. Avoid 'best' because it jumps during animation
pauseAfterFirstFrame_s = 0;                            % Optional pause after first frame

% File-handling options
overwriteExistingVideo = false;                        % false avoids permission errors
autoFallbackToTempFolder = true;                       % true saves in temp folder if needed
closeFigureAfterAnimation = true;                      % true closes figure at the end

%% -------------------------- Required variables --------------------------
% These variables must already be available in the MATLAB workspace.
% They are created by B01 and B03.

requiredVars = { ...
    'CS', ...
    'F_AllMarkers_S_X', 'F_AllMarkers_S_Y', 'F_AllMarkers_S_Z', ...
    'F_FRH_S', 'F_FLH_S', 'F_PS_S', ...
    'F_FRT_S', 'F_FRC_S', 'F_FLT_S', 'F_FLC_S', ...
    'F_TRP_S', 'F_TRH_S', 'F_TRD_S', ...
    'F_TLP_S', 'F_TLH_S', 'F_TLD_S', ...
    'F_MR_S', 'F_CR_S', 'F_ML_S', 'F_CL_S', ...
    'i_pelvis', 'j_pelvis', 'k_pelvis', ...
    'i_Rfemur', 'j_Rfemur', 'k_Rfemur', ...
    'i_Rleg', 'j_Rleg', 'k_Rleg', ...
    'i_Rfoot', 'j_Rfoot', 'k_Rfoot', ...
    'i_Lfemur', 'j_Lfemur', 'k_Lfemur', ...
    'i_Lleg', 'j_Lleg', 'k_Lleg', ...
    'i_Lfoot', 'j_Lfoot', 'k_Lfoot'};

for v = 1:numel(requiredVars)
    if ~exist(requiredVars{v}, 'var')
        error('Required variable "%s" is missing. Run B01 and B03 first.', requiredVars{v});
    end
end

%% -------------------------- Clear old video handle -----------------------
% If a previous run was interrupted, the old VideoWriter object may still be
% in the workspace and may keep the MP4 file locked.

if exist('cleanupObj', 'var')
    clear cleanupObj;
end

if exist('Video', 'var')
    try
        close(Video);
    catch
        % Ignore errors from an already-closed or invalid VideoWriter object.
    end
    clear Video;
end

if exist('V', 'var')
    try
        close(V);
    catch
        % Ignore errors from an already-closed or invalid VideoWriter object.
    end
    clear V;
end

%% -------------------------- Prepare output folders -----------------------

if saveFramesAsImages && ~exist(frameImageFolder, 'dir')
    mkdir(frameImageFolder);
end

[Video, actualVideoFileName] = createVideoWriterSafely( ...
    videoFileName, ...
    videoQuality, ...
    videoFrameRate, ...
    overwriteExistingVideo, ...
    autoFallbackToTempFolder);

cleanupObj = onCleanup(@() closeVideoSafely(Video));

fprintf('Saving stick-model animation to:\n%s\n\n', actualVideoFileName);

%% -------------------------- Prepare figure -------------------------------

hFig = figure( ...
    'Position', figurePosition, ...
    'Color', figureColor, ...
    'Name', 'B04 Stick Animation - Joint Axes', ...
    'NumberTitle', 'off', ...
    'CloseRequestFcn', @(src, event) requestCloseNow(src));

setappdata(hFig, 'StopAnimation', false);

uicontrol( ...
    'Parent', hFig, ...
    'Style', 'pushbutton', ...
    'String', 'Stop and save', ...
    'Units', 'normalized', ...
    'Position', [0.84 0.92 0.14 0.045], ...
    'FontSize', 11, ...
    'Callback', @(src, event) requestStopAndSave(hFig));

ax = axes('Parent', hFig);
hold(ax, 'on');
grid(ax, 'on');
box(ax, 'on');
axis(ax, 'equal');
xlabel(ax, 'X, cm');
ylabel(ax, 'Y, cm');
zlabel(ax, 'Z, cm');

xlim(ax, [min(F_AllMarkers_S_X(:)) - axisPadXY_cm, ...
          max(F_AllMarkers_S_X(:)) + axisPadXY_cm]);
ylim(ax, [min(F_AllMarkers_S_Y(:)) - axisPadXY_cm, ...
          max(F_AllMarkers_S_Y(:)) + axisPadXY_cm]);
zlim(ax, [min(F_AllMarkers_S_Z(:)) - axisPadZLow_cm, ...
          max(F_AllMarkers_S_Z(:)) + axisPadZHigh_cm]);

view(ax, viewAzimuthDeg, viewElevationDeg);

if showLegend
    makeAxisLegend(ax, axisColor_i, axisColor_j, axisColor_k, legendLocation);
end

%% -------------------------- Frame loop -----------------------------------

frameList = CS(1:frameStride:end);
numFramesToRender = numel(frameList);
lastCompletedFrame = NaN;

for frameCounter = 1:numFramesToRender

    if stopRequested(hFig)
        break;
    end

    t = frameList(frameCounter);
    lastCompletedFrame = t;

    fprintf('Rendering frame %d/%d    original frame = %d\n', ...
            frameCounter, numFramesToRender, t);

    if ~ishandle(hFig) || ~ishandle(ax)
        break;
    end

    cla(ax);
    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');
    axis(ax, 'equal');

    xlim(ax, [min(F_AllMarkers_S_X(:)) - axisPadXY_cm, ...
              max(F_AllMarkers_S_X(:)) + axisPadXY_cm]);
    ylim(ax, [min(F_AllMarkers_S_Y(:)) - axisPadXY_cm, ...
              max(F_AllMarkers_S_Y(:)) + axisPadXY_cm]);
    zlim(ax, [min(F_AllMarkers_S_Z(:)) - axisPadZLow_cm, ...
              max(F_AllMarkers_S_Z(:)) + axisPadZHigh_cm]);

    view(ax, viewAzimuthDeg, viewElevationDeg);

    xlabel(ax, 'X, cm');
    ylabel(ax, 'Y, cm');
    zlabel(ax, 'Z, cm');
    title(ax, sprintf('Frame: %d', t));

    if showStickModel
        plotStickModel(ax, t, ...
            colorPelvis, colorFemur, colorLeg, colorFoot, ...
            stickAlpha, stickEdgeColor, stickLineWidth);
    end

    if showJointAxes
        plotJointAxes(ax, t, ...
            axisScalePelvis, axisScaleSegment, ...
            axisColor_i, axisColor_j, axisColor_k, ...
            axisLineWidth);
    end

    if showLegend
        makeAxisLegend(ax, axisColor_i, axisColor_j, axisColor_k, legendLocation);
    end

    drawnow;

    if stopRequested(hFig)
        break;
    end

    try
        frame = getframe(hFig);
        writeVideo(Video, frame);

        if saveFramesAsImages
            imageFileName = fullfile(frameImageFolder, sprintf('frame_%04d.jpg', t));
            imwrite(frame2im(frame), imageFileName, 'jpg', 'Quality', frameImageQuality);
        end

    catch ME
        if isUserStopError(ME) || stopRequested(hFig)
            fprintf('Animation stopped by user while capturing frame.\n');
            break;
        else
            rethrow(ME);
        end
    end

    if frameCounter == 1 && pauseAfterFirstFrame_s > 0
        pause(pauseAfterFirstFrame_s);
    end
end

%% -------------------------- Finalize video -------------------------------

closeVideoSafely(Video);
clear cleanupObj;

if isnan(lastCompletedFrame)
    fprintf('Animation stopped before any frame was written.\n');
else
    fprintf('Animation saved through original frame %d.\n', lastCompletedFrame);
end

fprintf('Video file:\n%s\n', actualVideoFileName);

if closeFigureAfterAnimation && ishandle(hFig)
    delete(hFig);
end

%% =========================================================================
% Local helper functions
% =========================================================================

function plotStickModel(ax, t, colorPelvis, colorFemur, colorLeg, colorFoot, alphaValue, edgeColor, lineWidth)
% Plot triangular stick-model segments for pelvis, femurs, tibias, and feet.

    triFace = [1 2 3];

    % Pelvis
    v = [evalin('base', 'F_FRH_S(t,:)'); ...
         evalin('base', 'F_FLH_S(t,:)'); ...
         evalin('base', 'F_PS_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorPelvis, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);

    % Left femur
    v = [evalin('base', 'F_FLT_S(t,:)'); ...
         evalin('base', 'F_FLH_S(t,:)'); ...
         evalin('base', 'F_FLC_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorFemur, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);

    % Left tibia/leg
    v = [evalin('base', 'F_TLP_S(t,:)'); ...
         evalin('base', 'F_TLH_S(t,:)'); ...
         evalin('base', 'F_TLD_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorLeg, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);

    % Left foot
    v = [evalin('base', 'F_ML_S(t,:)'); ...
         evalin('base', 'F_CL_S(t,:)'); ...
         evalin('base', 'F_TLD_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorFoot, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);

    % Right femur
    v = [evalin('base', 'F_FRT_S(t,:)'); ...
         evalin('base', 'F_FRH_S(t,:)'); ...
         evalin('base', 'F_FRC_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorFemur, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);

    % Right tibia/leg
    v = [evalin('base', 'F_TRP_S(t,:)'); ...
         evalin('base', 'F_TRH_S(t,:)'); ...
         evalin('base', 'F_TRD_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorLeg, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);

    % Right foot
    v = [evalin('base', 'F_MR_S(t,:)'); ...
         evalin('base', 'F_CR_S(t,:)'); ...
         evalin('base', 'F_TRD_S(t,:)')];
    patch(ax, 'Faces', triFace, 'Vertices', v, ...
          'FaceColor', colorFoot, 'FaceAlpha', alphaValue, ...
          'EdgeColor', edgeColor, 'LineWidth', lineWidth);
end

function plotJointAxes(ax, t, axisScalePelvis, axisScaleSegment, color_i, color_j, color_k, lineWidth)
% Plot local i, j, k axes for pelvis and each limb segment.

    % Pelvis origin
    F_FRH_S = evalin('base', 'F_FRH_S');
    F_FLH_S = evalin('base', 'F_FLH_S');
    origin = (F_FRH_S(t,:) + F_FLH_S(t,:)) / 2;
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_pelvis(t,:)'), ...
        evalin('base', 'j_pelvis(t,:)'), ...
        evalin('base', 'k_pelvis(t,:)'), ...
        axisScalePelvis, color_i, color_j, color_k, lineWidth);

    % Right femur origin
    origin = evalin('base', 'F_FRH_S(t,:)');
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_Rfemur(t,:)'), ...
        evalin('base', 'j_Rfemur(t,:)'), ...
        evalin('base', 'k_Rfemur(t,:)'), ...
        axisScaleSegment, color_i, color_j, color_k, lineWidth);

    % Right tibia/leg origin
    origin = evalin('base', 'F_TRP_S(t,:)');
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_Rleg(t,:)'), ...
        evalin('base', 'j_Rleg(t,:)'), ...
        evalin('base', 'k_Rleg(t,:)'), ...
        axisScaleSegment, color_i, color_j, color_k, lineWidth);

    % Right foot origin
    origin = evalin('base', 'F_TRD_S(t,:)');
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_Rfoot(t,:)'), ...
        evalin('base', 'j_Rfoot(t,:)'), ...
        evalin('base', 'k_Rfoot(t,:)'), ...
        axisScaleSegment, color_i, color_j, color_k, lineWidth);

    % Left femur origin
    origin = evalin('base', 'F_FLH_S(t,:)');
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_Lfemur(t,:)'), ...
        evalin('base', 'j_Lfemur(t,:)'), ...
        evalin('base', 'k_Lfemur(t,:)'), ...
        axisScaleSegment, color_i, color_j, color_k, lineWidth);

    % Left tibia/leg origin
    origin = evalin('base', 'F_TLP_S(t,:)');
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_Lleg(t,:)'), ...
        evalin('base', 'j_Lleg(t,:)'), ...
        evalin('base', 'k_Lleg(t,:)'), ...
        axisScaleSegment, color_i, color_j, color_k, lineWidth);

    % Left foot origin
    origin = evalin('base', 'F_TLD_S(t,:)');
    plotLocalFrame(ax, origin, ...
        evalin('base', 'i_Lfoot(t,:)'), ...
        evalin('base', 'j_Lfoot(t,:)'), ...
        evalin('base', 'k_Lfoot(t,:)'), ...
        axisScaleSegment, color_i, color_j, color_k, lineWidth);
end

function plotLocalFrame(ax, origin, iAxis, jAxis, kAxis, scaleValue, color_i, color_j, color_k, lineWidth)
% Plot one local coordinate frame.

    quiver3(ax, origin(1), origin(2), origin(3), ...
        iAxis(1), iAxis(2), iAxis(3), ...
        'AutoScale', 'on', 'AutoScaleFactor', scaleValue, ...
        'Color', color_i, 'LineWidth', lineWidth);

    quiver3(ax, origin(1), origin(2), origin(3), ...
        jAxis(1), jAxis(2), jAxis(3), ...
        'AutoScale', 'on', 'AutoScaleFactor', scaleValue, ...
        'Color', color_j, 'LineWidth', lineWidth);

    quiver3(ax, origin(1), origin(2), origin(3), ...
        kAxis(1), kAxis(2), kAxis(3), ...
        'AutoScale', 'on', 'AutoScaleFactor', scaleValue, ...
        'Color', color_k, 'LineWidth', lineWidth);
end

function makeAxisLegend(ax, color_i, color_j, color_k, legendLocation)
% Create a stable legend for the local axes.
% A fixed location is used because 'best' moves during animation.

    hold(ax, 'on');

    h_i = plot3(ax, NaN, NaN, NaN, '-', 'Color', color_i, 'LineWidth', 2);
    h_j = plot3(ax, NaN, NaN, NaN, '-', 'Color', color_j, 'LineWidth', 2);
    h_k = plot3(ax, NaN, NaN, NaN, '-', 'Color', color_k, 'LineWidth', 2);

    legend(ax, [h_i, h_j, h_k], {'i-axis', 'j-axis', 'k-axis'}, ...
        'Location', legendLocation, ...
        'AutoUpdate', 'off', ...
        'Box', 'on');
end

function requestStopAndSave(hFig)
% Request a safe stop from the Stop button.
    if ishandle(hFig)
        setappdata(hFig, 'StopAnimation', true);

        try
            set(hFig, 'Name', 'Stopping and saving video...', 'NumberTitle', 'off');
            set(hFig, 'Pointer', 'watch');
        catch
            % Ignore cosmetic update errors.
        end

        drawnow;
    end
end

function requestCloseNow(hFig)
% Close button behavior.
% Delete the figure immediately. The frame loop detects this and closes the
% MP4 file safely.
    if ishandle(hFig)
        try
            setappdata(hFig, 'StopAnimation', true);
            set(hFig, 'CloseRequestFcn', 'closereq');
            delete(hFig);
        catch
            % If the figure is already closing, do nothing.
        end
    end
end

function tf = stopRequested(hFig)
% Check if the user pressed Stop or closed the figure.
    if ~ishandle(hFig)
        tf = true;
    else
        tf = logical(getappdata(hFig, 'StopAnimation'));
    end
end

function tf = isUserStopError(ME)
% Detect the common MATLAB error raised when getframe is interrupted.
    msg = ME.message;
    tf = contains(msg, 'Operation terminated by user') || ...
         contains(msg, 'terminated by user') || ...
         contains(msg, 'Invalid or deleted object');
end

function [videoObj, fileNameOut] = createVideoWriterSafely(fileNameIn, qualityValue, frameRateValue, overwriteExisting, fallbackToTemp)
% Create and open a VideoWriter object without crashing on locked files.

    [folderPath, baseName, ext] = fileparts(fileNameIn);

    if isempty(folderPath)
        folderPath = pwd;
    end

    if isempty(ext)
        ext = '.mp4';
    end

    requestedFile = fullfile(folderPath, [baseName, ext]);

    if isfile(requestedFile)
        if overwriteExisting
            try
                delete(requestedFile);
            catch
                warning('Could not delete existing video. A timestamped file will be used instead.');
                requestedFile = makeTimestampedVideoName(requestedFile);
            end
        else
            requestedFile = makeTimestampedVideoName(requestedFile);
        end
    end

    [videoObj, fileNameOut, ok] = tryOpenVideoWriter(requestedFile, qualityValue, frameRateValue);

    if ok
        return;
    end

    if fallbackToTemp
        tempFile = fullfile(tempdir, [baseName, '_', datestr(now, 'yyyymmdd_HHMMSS'), ext]);
        warning('Using MATLAB temporary folder for the video:\n%s', tempFile);

        [videoObj, fileNameOut, ok] = tryOpenVideoWriter(tempFile, qualityValue, frameRateValue);

        if ok
            return;
        end
    end

    error('Could not create a writable video file. Close any open MP4 viewer or choose another folder.');
end

function [videoObj, fileNameOut, ok] = tryOpenVideoWriter(fileNameIn, qualityValue, frameRateValue)
% Try to create and open a VideoWriter object.
    ok = false;
    fileNameOut = fileNameIn;
    videoObj = [];

    try
        folderPath = fileparts(fileNameIn);

        if ~exist(folderPath, 'dir')
            mkdir(folderPath);
        end

        testFolderWritePermission(folderPath);

        videoObj = VideoWriter(fileNameIn, 'MPEG-4');
        videoObj.Quality = qualityValue;
        videoObj.FrameRate = frameRateValue;
        open(videoObj);

        ok = true;
    catch ME
        warning('Could not create video file:\n%s\nReason: %s', fileNameIn, ME.message);

        try
            close(videoObj);
        catch
            % Ignore close errors for failed VideoWriter creation.
        end
    end
end

function testFolderWritePermission(folderPath)
% Check whether MATLAB can write to the selected output folder.
    testFile = [tempname(folderPath), '.tmp'];

    fid = fopen(testFile, 'w');

    if fid < 0
        error('Folder is not writable: %s', folderPath);
    end

    fclose(fid);
    delete(testFile);
end

function fileNameOut = makeTimestampedVideoName(fileNameIn)
% Add a timestamp to a video filename.
    [folderPath, baseName, ext] = fileparts(fileNameIn);

    if isempty(folderPath)
        folderPath = pwd;
    end

    if isempty(ext)
        ext = '.mp4';
    end

    timeStamp = datestr(now, 'yyyymmdd_HHMMSS');
    fileNameOut = fullfile(folderPath, sprintf('%s_%s%s', baseName, timeStamp, ext));
end

function closeVideoSafely(videoObj)
% Close VideoWriter without throwing an error if it is already closed.
    try
        close(videoObj);
    catch
        % Do nothing. This only prevents cleanup errors.
    end
end
