% -------------------------------------------------------------------------
% B04_Animation_JointAxes.m
%
% Generated by : Seyed Mohammadali Rahmati
% Affiliation  : Comparative Neuromechanics Lab,
%                School of Biological Sciences,
%                Georgia Institute of Technology, Atlanta, GA, USA
% Email        : smarahmati@gmail.com
%
% Purpose:
%   Animate registered 3D rat bone models together with local anatomical
%   joint/segment axes. Markers can also be shown or hidden.
%
% Required before running:
%   Run B01_Registration_WithoutFlow_3DScale_WithMWF.m first.
%   Run B03_Kinematics_3D_And_Cycles_R1_MLaxis.m second.
%
% Main idea:
%   - STL bone models come from B01.
%   - Local segment axes come from B03.
%   - Solid axes show each segment's own local coordinate frame.
%   - Dashed axes, if enabled, show the parent/proximal segment axes copied
%     to the distal joint. This makes the relative joint rotation easier to
%     see visually.
%   - Markers, if enabled, use the same color convention as B02_Animation.
%
% Axis colors:
%   i-axis = black
%   j-axis = red
%   k-axis = blue
%
% Marker colors, same as B02_Animation:
%   red filled circles      = STL anatomical landmarks used for registration
%   black open circles     = tracked/labeled marker points
%   blue open/filled circles = joint-axis or constraint points
% -------------------------------------------------------------------------

%% -------------------------- User parameters -----------------------------

% Video settings
createVideo     = true;                          % true saves MP4 video
videoFileName   = 'rat_walking_joint_axes_animation.mp4';
videoQuality    = 100;                           % MPEG-4 quality: 0 to 100
videoFrameRate  = 20;                            % Frames per second
useTimestampedVideoName = true;                  % Avoid overwrite / permission errors

% Figure settings
figurePosition = [0 0 1920 1080];                % [left bottom width height]
figureColor    = 'w';                            % White background

% Frame settings
frameStride = 1;                                 % 1 = every CS frame; 5 = every 5th CS frame
saveFramesAsImages = false;                      % true saves each frame as JPG
frameImageFolder   = 'B04_JointAxes_Frames';     % Folder for JPG frames
frameImageQuality  = 100;                        % JPG quality: 0 to 100

% Plot modes
axisPlotMode   = 'with_dashed';                  % 'with_dashed' or 'without_dashed'
markerPlotMode = 'with_markers';                 % 'with_markers' or 'without_markers'

% Bone appearance
boneColor = [0.8 0.8 1.0];                       % Light blue-gray bone color
boneAlpha = 0.5;                                 % 1 = solid, 0 = invisible

% Marker appearance, matched to B02_Animation
markerSizeSTL      = 7;                          % STL landmark points
markerSizeTracked  = 10;                         % tracked/labeled marker points
markerSizeJoint    = 10;                         % joint-axis/constraint points
markerLineWidth    = 2;                          % marker outline width

% Solid segment axes
solidAxisScale     = 1.0;                        % Length scale for solid axes
pelvisAxisScale    = 0.5;                        % Pelvis axes are drawn shorter
solidAxisLineWidth = 2;

% Dashed helper axes
dashedAxisScale     = 1.0;                       % Length scale for dashed axes
dashedAxisLineWidth = 1.5;
dashedAxisLineStyle = '--';

% View and lighting
viewAzimuthDeg    = 90;                          % Camera azimuth angle
viewElevationDeg  = 0;                           % Camera elevation angle
lightAzimuthDeg   = -140;                        % Light source azimuth
lightElevationDeg = 30;                          % Light source elevation

% Axis limits
axisPadXY_cm    = 3.0;                           % Padding around X/Y marker limits
axisPadZLow_cm  = 0.5;                           % Padding below Z marker limit
axisPadZHigh_cm = 3.0;                           % Padding above Z marker limit


%% -------------------------- Input checks --------------------------------

requiredVars = { ...
    'CS', 'F_AllMarkers_S_X', 'F_AllMarkers_S_Y', 'F_AllMarkers_S_Z', ...
    'V_RFemur_transformed', 'V_LFemur_transformed', 'V_Pelvis_transformed', ...
    'V_RTibia_transformed', 'V_LTibia_transformed', ...
    'V_RFoot_transformed', 'V_LFoot_transformed', ...
    'F_RFemur', 'F_LFemur', 'F_Pelvis', ...
    'F_RTibia', 'F_LTibia', 'F_RFoot', 'F_LFoot', ...
    'RPHip_transformed', 'LPHip_transformed', ...
    'RFH_transformed', 'RTKne_transformed', 'RFAnk_transformed', ...
    'LFH_transformed', 'LTKne_transformed', 'LFAnk_transformed', ...
    'i_pelvis', 'j_pelvis', 'k_pelvis', ...
    'i_Rfemur', 'j_Rfemur', 'k_Rfemur', ...
    'i_Rleg', 'j_Rleg', 'k_Rleg', ...
    'i_Rfoot', 'j_Rfoot', 'k_Rfoot', ...
    'i_Lfemur', 'j_Lfemur', 'k_Lfemur', ...
    'i_Lleg', 'j_Lleg', 'k_Lleg', ...
    'i_Lfoot', 'j_Lfoot', 'k_Lfoot' ...
};

missingVars = {};
for q = 1:numel(requiredVars)
    if ~exist(requiredVars{q}, 'var')
        missingVars{end+1} = requiredVars{q}; %#ok<SAGROW>
    end
end

if ~isempty(missingVars)
    error(['Missing required variables. Run B01 and B03 first. Missing: ', ...
           strjoin(missingVars, ', ')]);
end

if ~strcmpi(axisPlotMode, 'with_dashed') && ~strcmpi(axisPlotMode, 'without_dashed')
    error('axisPlotMode must be either ''with_dashed'' or ''without_dashed''.');
end

if ~strcmpi(markerPlotMode, 'with_markers') && ~strcmpi(markerPlotMode, 'without_markers')
    error('markerPlotMode must be either ''with_markers'' or ''without_markers''.');
end

showDashedAxes = strcmpi(axisPlotMode, 'with_dashed');
showMarkers    = strcmpi(markerPlotMode, 'with_markers');

if showMarkers
    markerVars = { ...
        'Pelvis_markerpoints', 'RFemur_markerpoints', 'LFemur_markerpoints', ...
        'RTibia_markerpoints', 'LTibia_markerpoints', 'RFoot_markerpoints', 'LFoot_markerpoints', ...
        'I_RPHip', 'I_LPHip', 'I_PS', ...
        'I_RFH', 'I_RFT', 'I_RFE', 'I_RFEL', 'I_RFEM', ...
        'I_LFH', 'I_LFT', 'I_LFE', 'I_LFEL', 'I_LFEM', ...
        'I_RTP', 'I_RTH', 'I_RTD', 'I_RTPAL', 'I_RTPAM', 'I_RTMAM_T', 'I_RTMAL_T', ...
        'I_LTP', 'I_LTH', 'I_LTD', 'I_LTPAL', 'I_LTPAM', 'I_LTMAM_T', 'I_LTMAL_T', ...
        'I_RCal', 'I_RMet', 'I_RTMAM_F', 'I_RTMAL_F', ...
        'I_LCal', 'I_LMet', 'I_LTMAM_F', 'I_LTMAL_F' ...
    };

    missingMarkerVars = {};
    for q = 1:numel(markerVars)
        if ~exist(markerVars{q}, 'var')
            missingMarkerVars{end+1} = markerVars{q}; %#ok<SAGROW>
        end
    end

    if ~isempty(missingMarkerVars)
        error(['markerPlotMode is ''with_markers'', but these marker variables are missing. ', ...
               'Run B01 first. Missing: ', strjoin(missingMarkerVars, ', ')]);
    end
end

if frameStride < 1 || floor(frameStride) ~= frameStride
    error('frameStride must be a positive integer.');
end

frameList = CS(1:frameStride:end);
numFramesToRender = numel(frameList);


%% -------------------------- Video setup ---------------------------------

% Close a leftover Video object from an interrupted previous run, if present.
if exist('Video', 'var')
    try
        close(Video);
    catch
    end
    clear Video
end

Video = [];
outputVideoFile = '';

if createVideo
    [Video, outputVideoFile] = localCreateVideoWriter( ...
        videoFileName, videoQuality, videoFrameRate, useTimestampedVideoName);

    % This protects the video file if the user stops the script early.
    videoCleanup = onCleanup(@() localSafeCloseVideo(Video)); %#ok<NASGU>

    fprintf('Saving video to:\n%s\n\n', outputVideoFile);
end

if saveFramesAsImages && ~exist(frameImageFolder, 'dir')
    mkdir(frameImageFolder);
end


%% -------------------------- Figure setup --------------------------------

hFig = figure( ...
    'Name', 'B04 Joint-Axis Animation', ...
    'Color', figureColor, ...
    'Position', figurePosition, ...
    'CloseRequestFcn', @localCloseFigureImmediately);

setappdata(hFig, 'stopRequested', false);

uicontrol(hFig, ...
    'Style', 'pushbutton', ...
    'String', 'Stop and save', ...
    'Units', 'normalized', ...
    'Position', [0.84 0.91 0.14 0.05], ...
    'FontSize', 11, ...
    'Callback', @localRequestStop);

ax = axes('Parent', hFig);
hold(ax, 'on');
grid(ax, 'off');
box(ax, 'on');
axis(ax, 'equal');

xlabel(ax, 'X, cm');
ylabel(ax, 'Y, cm');
zlabel(ax, 'Z, cm');

% Fixed axis limits make the animation stable and prevent zooming per frame.
xLimits = [min(F_AllMarkers_S_X(:)) - axisPadXY_cm, ...
           max(F_AllMarkers_S_X(:)) + axisPadXY_cm];

yLimits = [min(F_AllMarkers_S_Y(:)) - axisPadXY_cm, ...
           max(F_AllMarkers_S_Y(:)) + axisPadXY_cm];

zLimits = [min(F_AllMarkers_S_Z(:)) - axisPadZLow_cm, ...
           max(F_AllMarkers_S_Z(:)) + axisPadZHigh_cm];


%% -------------------------- Animation loop ------------------------------

for iFrame = 1:numFramesToRender

    if localStopRequested(hFig)
        fprintf('Animation stopped by user before frame %d.\n', iFrame);
        break;
    end

    t = frameList(iFrame);

    fprintf('Rendering frame %d/%d   original frame = %d\n', ...
            iFrame, numFramesToRender, t);

    % Clear only the axes contents. The figure and stop button stay alive.
    cla(ax);
    hold(ax, 'on');
    grid(ax, 'off');
    box(ax, 'on');
    axis(ax, 'equal');

    xlabel(ax, 'X, cm');
    ylabel(ax, 'Y, cm');
    zlabel(ax, 'Z, cm');
    title(ax, sprintf('Frame: %d', t));

    xlim(ax, xLimits);
    ylim(ax, yLimits);
    zlim(ax, zLimits);
    view(ax, viewAzimuthDeg, viewElevationDeg);

    %% Plot transformed STL bones
    patch(ax, 'Faces', F_Pelvis,  'Vertices', V_Pelvis_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);

    patch(ax, 'Faces', F_RFemur,  'Vertices', V_RFemur_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);

    patch(ax, 'Faces', F_LFemur,  'Vertices', V_LFemur_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);

    patch(ax, 'Faces', F_RTibia,  'Vertices', V_RTibia_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);

    patch(ax, 'Faces', F_LTibia,  'Vertices', V_LTibia_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);

    patch(ax, 'Faces', F_RFoot,   'Vertices', V_RFoot_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);

    patch(ax, 'Faces', F_LFoot,   'Vertices', V_LFoot_transformed{t,1}, ...
        'FaceColor', boneColor, 'EdgeColor', 'none', 'FaceAlpha', boneAlpha);


    %% Optional marker overlay
    % Marker color convention matches B02_Animation:
    %   red filled circles       = STL anatomical landmarks
    %   black open circles      = tracked/labeled marker points
    %   blue open/filled circles = joint-axis or constraint points

    if showMarkers

        % Pelvis
        localPlotSTLPoints(ax, V_Pelvis_transformed{t,1}, ...
            [I_RPHip I_LPHip I_PS], markerSizeSTL, 'r');
        localPlotTrackedPoints(ax, Pelvis_markerpoints{t,1}, ...
            markerSizeTracked, markerLineWidth);

        % Right femur
        localPlotSTLPoints(ax, V_RFemur_transformed{t,1}, ...
            [I_RFH I_RFT I_RFE], markerSizeSTL, 'r');
        localPlotJointPoints(ax, V_RFemur_transformed{t,1}, ...
            [I_RFEL I_RFEM], markerSizeJoint, markerLineWidth);
        localPlotTrackedPoints(ax, localGetLastRows(RFemur_markerpoints{t,1}, 3), ...
            markerSizeTracked, markerLineWidth);

        % Left femur
        localPlotSTLPoints(ax, V_LFemur_transformed{t,1}, ...
            [I_LFH I_LFT I_LFE], markerSizeSTL, 'r');
        localPlotJointPoints(ax, V_LFemur_transformed{t,1}, ...
            [I_LFEL I_LFEM], markerSizeJoint, markerLineWidth);
        localPlotTrackedPoints(ax, localGetLastRows(LFemur_markerpoints{t,1}, 3), ...
            markerSizeTracked, markerLineWidth);

        % Right tibia
        localPlotSTLPoints(ax, V_RTibia_transformed{t,1}, ...
            [I_RTP I_RTH I_RTD], markerSizeSTL, 'r');
        localPlotSTLPoints(ax, V_RTibia_transformed{t,1}, ...
            [I_RTPAL I_RTPAM], markerSizeSTL, 'b');
        localPlotJointPoints(ax, V_RTibia_transformed{t,1}, ...
            [I_RTMAM_T I_RTMAL_T], markerSizeJoint, markerLineWidth);
        localPlotTrackedPoints(ax, localGetLastRows(RTibia_markerpoints{t,1}, 3), ...
            markerSizeTracked, markerLineWidth);

        % Left tibia
        localPlotSTLPoints(ax, V_LTibia_transformed{t,1}, ...
            [I_LTP I_LTH I_LTD], markerSizeSTL, 'r');
        localPlotSTLPoints(ax, V_LTibia_transformed{t,1}, ...
            [I_LTPAL I_LTPAM], markerSizeSTL, 'b');
        localPlotJointPoints(ax, V_LTibia_transformed{t,1}, ...
            [I_LTMAM_T I_LTMAL_T], markerSizeJoint, markerLineWidth);
        localPlotTrackedPoints(ax, localGetLastRows(LTibia_markerpoints{t,1}, 3), ...
            markerSizeTracked, markerLineWidth);

        % Right foot
        localPlotSTLPoints(ax, V_RFoot_transformed{t,1}, ...
            [I_RCal I_RMet], markerSizeSTL, 'r');
        localPlotSTLPoints(ax, V_RFoot_transformed{t,1}, ...
            [I_RTMAM_F I_RTMAL_F], markerSizeSTL, 'b');
        localPlotTrackedPoints(ax, localGetLastRows(RFoot_markerpoints{t,1}, 2), ...
            markerSizeTracked, markerLineWidth);

        % Left foot
        localPlotSTLPoints(ax, V_LFoot_transformed{t,1}, ...
            [I_LCal I_LMet], markerSizeSTL, 'r');
        localPlotSTLPoints(ax, V_LFoot_transformed{t,1}, ...
            [I_LTMAM_F I_LTMAL_F], markerSizeSTL, 'b');
        localPlotTrackedPoints(ax, localGetLastRows(LFoot_markerpoints{t,1}, 2), ...
            markerSizeTracked, markerLineWidth);
    end


    %% Plot solid local axes at their anatomical origins

    pelvisOrigin = (RPHip_transformed(t,:) + LPHip_transformed(t,:)) / 2;

    localPlotAxes(ax, pelvisOrigin, ...
        i_pelvis(t,:), j_pelvis(t,:), k_pelvis(t,:), ...
        pelvisAxisScale, '-', solidAxisLineWidth);

    localPlotAxes(ax, RFH_transformed(t,:), ...
        i_Rfemur(t,:), j_Rfemur(t,:), k_Rfemur(t,:), ...
        solidAxisScale, '-', solidAxisLineWidth);

    localPlotAxes(ax, RTKne_transformed(t,:), ...
        i_Rleg(t,:), j_Rleg(t,:), k_Rleg(t,:), ...
        solidAxisScale, '-', solidAxisLineWidth);

    localPlotAxes(ax, RFAnk_transformed(t,:), ...
        i_Rfoot(t,:), j_Rfoot(t,:), k_Rfoot(t,:), ...
        solidAxisScale, '-', solidAxisLineWidth);

    localPlotAxes(ax, LFH_transformed(t,:), ...
        i_Lfemur(t,:), j_Lfemur(t,:), k_Lfemur(t,:), ...
        solidAxisScale, '-', solidAxisLineWidth);

    localPlotAxes(ax, LTKne_transformed(t,:), ...
        i_Lleg(t,:), j_Lleg(t,:), k_Lleg(t,:), ...
        solidAxisScale, '-', solidAxisLineWidth);

    localPlotAxes(ax, LFAnk_transformed(t,:), ...
        i_Lfoot(t,:), j_Lfoot(t,:), k_Lfoot(t,:), ...
        solidAxisScale, '-', solidAxisLineWidth);


    %% Optional dashed helper axes
    % Dashed axes are not new calculations. They re-plot the proximal frame
    % at the next joint center, which helps visually compare adjacent frames.
    %
    % Examples:
    %   - pelvis axes at the hip joint
    %   - femur axes at the knee joint
    %   - tibia axes at the ankle joint

    if showDashedAxes

        % Pelvis frame copied to both hip joints
        localPlotAxes(ax, RFH_transformed(t,:), ...
            i_pelvis(t,:), j_pelvis(t,:), k_pelvis(t,:), ...
            dashedAxisScale, dashedAxisLineStyle, dashedAxisLineWidth);

        localPlotAxes(ax, LFH_transformed(t,:), ...
            i_pelvis(t,:), j_pelvis(t,:), k_pelvis(t,:), ...
            dashedAxisScale, dashedAxisLineStyle, dashedAxisLineWidth);

        % Femur frames copied to the knee joints
        localPlotAxes(ax, RTKne_transformed(t,:), ...
            i_Rfemur(t,:), j_Rfemur(t,:), k_Rfemur(t,:), ...
            dashedAxisScale, dashedAxisLineStyle, dashedAxisLineWidth);

        localPlotAxes(ax, LTKne_transformed(t,:), ...
            i_Lfemur(t,:), j_Lfemur(t,:), k_Lfemur(t,:), ...
            dashedAxisScale, dashedAxisLineStyle, dashedAxisLineWidth);

        % Tibia/leg frames copied to the ankle joints
        localPlotAxes(ax, RFAnk_transformed(t,:), ...
            i_Rleg(t,:), j_Rleg(t,:), k_Rleg(t,:), ...
            dashedAxisScale, dashedAxisLineStyle, dashedAxisLineWidth);

        localPlotAxes(ax, LFAnk_transformed(t,:), ...
            i_Lleg(t,:), j_Lleg(t,:), k_Lleg(t,:), ...
            dashedAxisScale, dashedAxisLineStyle, dashedAxisLineWidth);
    end

    camlight(ax, lightAzimuthDeg, lightElevationDeg);
    lighting(ax, 'gouraud');

    drawnow;

    if localStopRequested(hFig)
        fprintf('Animation stopped by user after rendering frame %d.\n', t);
        break;
    end

    %% Save video frame and optional JPG frame
    if createVideo
        try
            frame = getframe(hFig);
            writeVideo(Video, frame);
        catch ME
            fprintf('\nStopping animation while saving frame %d.\n', t);
            fprintf('Reason: %s\n', ME.message);
            break;
        end
    end

    if saveFramesAsImages && ishghandle(hFig)
        frameImage = getframe(hFig);
        imageFile = fullfile(frameImageFolder, sprintf('frame_%04d.jpg', t));
        imwrite(frame2im(frameImage), imageFile, 'jpg', 'Quality', frameImageQuality);
    end
end


%% -------------------------- Finish safely --------------------------------

if createVideo
    localSafeCloseVideo(Video);
    clear videoCleanup
    fprintf('\nVideo saved successfully:\n%s\n', outputVideoFile);
end

if ishghandle(hFig)
    set(hFig, 'Name', 'B04 Joint-Axis Animation - Done');
end


%% ========================================================================
% Local helper functions
% ========================================================================

function localPlotAxes(ax, origin, iAxis, jAxis, kAxis, axisScale, lineStyle, lineWidth)
%LOCALPLOTAXES Plot i, j, k local coordinate axes.
%
%   i-axis = black
%   j-axis = red
%   k-axis = blue

    quiver3(ax, origin(1), origin(2), origin(3), ...
        iAxis(1), iAxis(2), iAxis(3), ...
        'AutoScale', 'on', 'AutoScaleFactor', axisScale, ...
        'Color', 'k', 'LineStyle', lineStyle, 'LineWidth', lineWidth);

    quiver3(ax, origin(1), origin(2), origin(3), ...
        jAxis(1), jAxis(2), jAxis(3), ...
        'AutoScale', 'on', 'AutoScaleFactor', axisScale, ...
        'Color', 'r', 'LineStyle', lineStyle, 'LineWidth', lineWidth);

    quiver3(ax, origin(1), origin(2), origin(3), ...
        kAxis(1), kAxis(2), kAxis(3), ...
        'AutoScale', 'on', 'AutoScaleFactor', axisScale, ...
        'Color', 'b', 'LineStyle', lineStyle, 'LineWidth', lineWidth);
end


function localPlotSTLPoints(ax, vertices, pointIdx, markerSize, colorCode)
%LOCALPLOTSTLPOINTS Plot STL landmark points by vertex index.

    pointIdx = pointIdx(:)';

    plot3(ax, vertices(pointIdx,1), vertices(pointIdx,2), vertices(pointIdx,3), 'o', ...
        'MarkerSize', markerSize, ...
        'MarkerFaceColor', colorCode, ...
        'MarkerEdgeColor', colorCode);
end


function localPlotJointPoints(ax, vertices, pointIdx, markerSize, lineWidth)
%LOCALPLOTJOINTPOINTS Plot joint-axis/constraint points as blue open circles.

    pointIdx = pointIdx(:)';

    plot3(ax, vertices(pointIdx,1), vertices(pointIdx,2), vertices(pointIdx,3), 'o', ...
        'MarkerSize', markerSize, ...
        'MarkerFaceColor', 'none', ...
        'MarkerEdgeColor', 'b', ...
        'LineWidth', lineWidth);
end


function localPlotTrackedPoints(ax, points, markerSize, lineWidth)
%LOCALPLOTTRACKEDPOINTS Plot tracked/labeled points as black open circles.

    if isempty(points)
        return;
    end

    plot3(ax, points(:,1), points(:,2), points(:,3), 'o', ...
        'MarkerSize', markerSize, ...
        'MarkerFaceColor', 'none', ...
        'MarkerEdgeColor', 'k', ...
        'LineWidth', lineWidth);
end


function rows = localGetLastRows(matrixData, nRows)
%LOCALGETLASTROWS Return the last n rows from marker arrays.
%
%   This is useful when MWF > 1. The weighted repeated points are placed
%   before the true tracked marker rows, so the last rows are the original
%   tracked/labeled marker points.

    nRows = min(nRows, size(matrixData, 1));
    rows = matrixData(end-nRows+1:end, :);
end


function localRequestStop(src, ~)
%LOCALREQUESTSTOP Stop after the current frame and close the video safely.

    fig = ancestor(src, 'figure');

    if ishghandle(fig)
        setappdata(fig, 'stopRequested', true);
        set(fig, 'Name', 'Stopping and saving video...');
    end
end


function localCloseFigureImmediately(fig, ~)
%LOCALCLOSEFIGUREIMMEDIATELY Close the figure and request safe video stop.
%
%   The figure closes immediately. The script detects this and closes the
%   VideoWriter file before exiting.

    if ishghandle(fig)
        setappdata(fig, 'stopRequested', true);
        delete(fig);
    end
end


function tf = localStopRequested(fig)
%LOCALSTOPREQUESTED Return true if user requested stop or closed the figure.

    tf = true;

    if ishghandle(fig)
        if isappdata(fig, 'stopRequested')
            tf = getappdata(fig, 'stopRequested');
        else
            tf = false;
        end
    end
end


function [Video, outputVideoFile] = localCreateVideoWriter(videoFileName, qualityValue, frameRateValue, useTimestamp)
%LOCALCREATEVIDEOWRITER Create VideoWriter without overwrite/lock errors.

    [videoFolder, baseName, extName] = fileparts(videoFileName);

    if isempty(videoFolder)
        videoFolder = pwd;
    end

    if isempty(extName)
        extName = '.mp4';
    end

    if ~exist(videoFolder, 'dir')
        mkdir(videoFolder);
    end

    if ~localFolderIsWritable(videoFolder)
        warning('The selected folder is not writable. Using tempdir instead.');
        videoFolder = tempdir;
    end

    if useTimestamp || exist(fullfile(videoFolder, [baseName, extName]), 'file')
        outputVideoFile = localTimestampedFile(videoFolder, baseName, extName);
    else
        outputVideoFile = fullfile(videoFolder, [baseName, extName]);
    end

    try
        Video = VideoWriter(outputVideoFile, 'MPEG-4');
        Video.Quality = qualityValue;
        Video.FrameRate = frameRateValue;
        open(Video);
    catch ME
        warning('Could not create video in requested folder: %s', ME.message);
        outputVideoFile = localTimestampedFile(tempdir, baseName, extName);

        Video = VideoWriter(outputVideoFile, 'MPEG-4');
        Video.Quality = qualityValue;
        Video.FrameRate = frameRateValue;
        open(Video);
    end
end


function outputFile = localTimestampedFile(folderName, baseName, extName)
%LOCALTIMESTAMPEDFILE Return a unique timestamped filename.

    timeStamp = datestr(now, 'yyyymmdd_HHMMSS');
    outputFile = fullfile(folderName, sprintf('%s_%s%s', baseName, timeStamp, extName));

    counter = 1;
    while exist(outputFile, 'file')
        outputFile = fullfile(folderName, ...
            sprintf('%s_%s_%03d%s', baseName, timeStamp, counter, extName));
        counter = counter + 1;
    end
end


function tf = localFolderIsWritable(folderName)
%LOCALFOLDERISWRITABLE Check whether MATLAB can write to a folder.

    testFile = tempname(folderName);
    [fid, ~] = fopen(testFile, 'w');

    if fid < 0
        tf = false;
        return;
    end

    fclose(fid);
    delete(testFile);
    tf = true;
end


function localSafeCloseVideo(Video)
%LOCALSAFECLOSEVIDEO Close VideoWriter without throwing extra errors.

    try
        close(Video);
    catch
    end
end
