% -------------------------------------------------------------------------
% B06_STLWrite.m
%
% Generated by : Seyed Mohammadali Rahmati
% Affiliation  : Comparative Neuromechanics Lab,
%                School of Biological Sciences,
%                Georgia Institute of Technology, Atlanta, GA, USA
% Email        : smarahmati@gmail.com
%
% Description:
%   Writes the transformed bone meshes from B01 as STL files.
%
%   This script should be run after:
%       B01_Registration_WithoutFlow_3DScale_WithMWF.m
%
%   Required variables from B01:
%       CS                          : frame numbers to export
%       V_*_transformed             : transformed STL vertices for each frame
%       F_*                         : STL face connectivity for each bone
%
%   Output folder structure:
%       STLFiles/
%           frame_number/
%               Pelvis_frameNumber.stl
%               RFemur_frameNumber.stl
%               RTibia_frameNumber.stl
%               RFoot_frameNumber.stl
%               LFemur_frameNumber.stl
%               LTibia_frameNumber.stl
%               LFoot_frameNumber.stl
%
% Notes:
%   Some STL files include extra landmark vertices added at the end of the
%   mesh in earlier scripts. By default, these extra vertices are removed
%   before writing the STL files.
% -------------------------------------------------------------------------

%% -------------------------- User parameters -----------------------------

outputFolderName = 'STLFiles';   % Main output folder for all STL frames
frameStride      = 1;            % 1 = export every frame in CS; 5 = every 5th frame
overwriteFiles   = true;         % true = replace old STL files if they already exist
printProgress    = true;         % true = print frame progress in the command window

% Choose which bones to export
writePelvis = true;
writeRFemur = true;
writeRTibia = true;
writeRFoot  = true;
writeLFemur = true;
writeLTibia = true;
writeLFoot  = true;

% Remove artificial landmark vertices added at the end of each STL mesh.
% These values match the original script:
%   Pelvis: last 1 vertex removed
%   Femur : last 3 vertices removed
%   Tibia : last 3 vertices removed
%   Foot  : last 2 vertices removed
removeExtraLandmarkVertices = true;

% Remove vertices that are not used by any triangle before calling triangulation().
% This prevents repeated MATLAB warnings such as:
%   "Some input points are not referenced by the triangulation."
% These unused vertices do not affect the visible STL surface, so removing
% them is safe for STL export.
removeUnreferencedVertices = true;

extraVertices.Pelvis = 1;
extraVertices.Femur  = 3;
extraVertices.Tibia  = 3;
extraVertices.Foot   = 2;


%% -------------------------- Check inputs --------------------------------

requiredVars = { ...
    'CS', ...
    'V_Pelvis_transformed', 'F_Pelvis', ...
    'V_RFemur_transformed', 'F_RFemur', ...
    'V_RTibia_transformed', 'F_RTibia', ...
    'V_RFoot_transformed',  'F_RFoot', ...
    'V_LFemur_transformed', 'F_LFemur', ...
    'V_LTibia_transformed', 'F_LTibia', ...
    'V_LFoot_transformed',  'F_LFoot'};

for k = 1:numel(requiredVars)
    if ~exist(requiredVars{k}, 'var')
        error('Missing required variable "%s". Run B01 before running B06.', requiredVars{k});
    end
end

if frameStride < 1 || mod(frameStride, 1) ~= 0
    error('frameStride must be a positive integer.');
end


%% -------------------------- Prepare output ------------------------------

mainFolderPath = fullfile(pwd, outputFolderName);

if ~exist(mainFolderPath, 'dir')
    mkdir(mainFolderPath);
end

framesToWrite = CS(:);
framesToWrite = framesToWrite(1:frameStride:end);

numFramesToWrite = numel(framesToWrite);
numFilesWritten  = 0;
numFilesSkipped  = 0;

fprintf('\nWriting STL files to:\n%s\n\n', mainFolderPath);


%% -------------------------- Write STL files -----------------------------

for i = 1:numFramesToWrite

    frameNumber = framesToWrite(i);

    if printProgress
        fprintf('Frame %d of %d  |  frame number: %d\n', ...
                i, numFramesToWrite, frameNumber);
    end

    % Each frame gets its own folder.
    frameFolder = fullfile(mainFolderPath, sprintf('%d', frameNumber));

    if ~exist(frameFolder, 'dir')
        mkdir(frameFolder);
    end

    % Pelvis
    if writePelvis
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_Pelvis_transformed, F_Pelvis, frameNumber, frameFolder, ...
            'Pelvis', extraVertices.Pelvis, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'pelvis_half_reverse', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end

    % Right side
    if writeRFemur
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_RFemur_transformed, F_RFemur, frameNumber, frameFolder, ...
            'RFemur', extraVertices.Femur, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'none', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end

    if writeRTibia
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_RTibia_transformed, F_RTibia, frameNumber, frameFolder, ...
            'RTibia', extraVertices.Tibia, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'none', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end

    if writeRFoot
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_RFoot_transformed, F_RFoot, frameNumber, frameFolder, ...
            'RFoot', extraVertices.Foot, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'none', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end

    % Left side
    % The left bones were mirrored, so the face order is reversed to keep
    % the surface normals consistent.
    if writeLFemur
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_LFemur_transformed, F_LFemur, frameNumber, frameFolder, ...
            'LFemur', extraVertices.Femur, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'reverse_all', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end

    if writeLTibia
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_LTibia_transformed, F_LTibia, frameNumber, frameFolder, ...
            'LTibia', extraVertices.Tibia, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'reverse_all', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end

    if writeLFoot
        [nWritten, nSkipped] = writeBoneSTL( ...
            V_LFoot_transformed, F_LFoot, frameNumber, frameFolder, ...
            'LFoot', extraVertices.Foot, removeExtraLandmarkVertices, removeUnreferencedVertices, ...
            'reverse_all', overwriteFiles);
        numFilesWritten = numFilesWritten + nWritten;
        numFilesSkipped = numFilesSkipped + nSkipped;
    end
end


%% -------------------------- Summary -------------------------------------

fprintf('\nSTL export finished.\n');
fprintf('Files written : %d\n', numFilesWritten);
fprintf('Files skipped : %d\n', numFilesSkipped);
fprintf('Output folder : %s\n\n', mainFolderPath);


%% -------------------------- Local function ------------------------------
function [numWritten, numSkipped] = writeBoneSTL(verticesCell, facesIn, frameNumber, ...
                                                frameFolder, boneName, ...
                                                extraVertexCount, ...
                                                removeExtraVertices, ...
                                                removeUnreferencedVertices, ...
                                                faceMode, overwriteFiles)
%WRITEBONESTL Write one transformed bone mesh as an STL file.

    numWritten = 0;
    numSkipped = 0;

    vertices = verticesCell{frameNumber, 1};
    faces    = facesIn;

    % Remove extra artificial landmark vertices/faces added to the mesh.
    if removeExtraVertices && extraVertexCount > 0

        if size(vertices, 1) <= extraVertexCount
            error('%s frame %d has too few vertices to trim.', boneName, frameNumber);
        end

        if size(faces, 1) <= extraVertexCount
            error('%s frame %d has too few faces to trim.', boneName, frameNumber);
        end

        vertices = vertices(1:end-extraVertexCount, :);
        faces    = faces(1:end-extraVertexCount, :);
    end

    % Correct face orientation when needed.
    switch lower(faceMode)

        case 'none'
            % Keep original face direction.

        case 'reverse_all'
            faces = faces(:, [3 2 1]);

        case 'pelvis_half_reverse'
            % This preserves the original pelvis-specific face correction.
            splitIndex = round(size(faces, 1) / 2);
            facesRev = faces(splitIndex:end, [3 2 1]);
            faces = [faces(1:splitIndex, :); facesRev];

        otherwise
            error('Unknown faceMode: %s', faceMode);
    end


    % Remove invalid, degenerate, or unreferenced vertices/faces before STL export.
    % This keeps the STL surface unchanged but avoids triangulation warnings.
    faces = round(faces);

    validFaceRows = all(isfinite(faces), 2) & ...
                    all(faces >= 1, 2) & ...
                    all(faces <= size(vertices, 1), 2) & ...
                    faces(:,1) ~= faces(:,2) & ...
                    faces(:,1) ~= faces(:,3) & ...
                    faces(:,2) ~= faces(:,3);

    faces = faces(validFaceRows, :);

    if isempty(faces)
        error('%s frame %d has no valid faces after cleaning.', boneName, frameNumber);
    end

    if removeUnreferencedVertices
        usedVertexIds = unique(faces(:));
        oldToNew = zeros(size(vertices, 1), 1);
        oldToNew(usedVertexIds) = 1:numel(usedVertexIds);

        vertices = vertices(usedVertexIds, :);
        faces = oldToNew(faces);
    end

    outputFile = fullfile(frameFolder, sprintf('%s_%d.stl', boneName, frameNumber));

    if exist(outputFile, 'file') && ~overwriteFiles
        numSkipped = 1;
        return;
    end

    try
        tr = triangulation(faces, vertices);
        stlwrite(tr, outputFile);
        numWritten = 1;

    catch ME
        warning('Could not write %s frame %d.\nReason: %s', ...
                boneName, frameNumber, ME.message);
    end
end
