% -------------------------------------------------------------------------
% B07_Visualize_STLFiles.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Visualizes STL files exported by B06_STLWrite.m.
%   Each frame is expected to be inside one folder, for example:
%
%       STLFiles/71/Pelvis_71.stl
%       STLFiles/71/RFemur_71.stl
%       STLFiles/71/RTibia_71.stl
%
%   The code can show one frame or animate all STL frames.
% -------------------------------------------------------------------------

clear; clc; close all;

%% -------------------------- User parameters -----------------------------

mainSTLFolder = 'STLFiles';     % Main folder created by B06_STLWrite.m

mode = 'animate';               % 'single_frame' or 'animate'
singleFrameNumber = 71;         % Used only when mode = 'single_frame'

frameStride = 1;                % 1 = show every frame; 5 = every 5th frame
pauseTime = 0.03;               % Pause between frames during animation

figurePosition = [0 0 1600 900];

boneAlpha = 0.65;               % STL transparency
edgeColor = 'none';             % 'none' is cleaner; use [0.3 0.3 0.3] to show mesh edges

viewAzimuthDeg = 90;
viewElevationDeg = 0;

axisPad_cm = 1.0;               % Extra padding around the STL limits

% Bone colors
colorPelvis = [0.85 0.85 0.85];
colorRight  = [0.80 0.80 1.00];
colorLeft   = [0.70 0.90 1.00];

% Names expected from B06_STLWrite.m
boneNames = {'Pelvis', ...
             'RFemur', 'RTibia', 'RFoot', ...
             'LFemur', 'LTibia', 'LFoot'};

%% -------------------------- Select STL folder ---------------------------

if ~isfolder(mainSTLFolder)
    selectedFolder = uigetdir(pwd, 'Select STLFiles folder');
    if isequal(selectedFolder, 0)
        error('No STL folder selected.');
    end
    mainSTLFolder = selectedFolder;
end

fprintf('Using STL folder:\n%s\n\n', mainSTLFolder);

%% -------------------------- Find frame folders --------------------------

folderInfo = dir(mainSTLFolder);
folderInfo = folderInfo([folderInfo.isdir]);

% Remove "." and ".."
folderInfo = folderInfo(~ismember({folderInfo.name}, {'.', '..'}));

% Keep only folders with numeric names
frameNumbers = [];
frameFolders = {};

for i = 1:numel(folderInfo)
    frameNum = str2double(folderInfo(i).name);

    if ~isnan(frameNum)
        frameNumbers(end+1, 1) = frameNum; %#ok<SAGROW>
        frameFolders{end+1, 1} = fullfile(mainSTLFolder, folderInfo(i).name); %#ok<SAGROW>
    end
end

if isempty(frameNumbers)
    error('No numeric frame folders were found inside:\n%s', mainSTLFolder);
end

% Sort frame folders by frame number
[frameNumbers, sortIdx] = sort(frameNumbers);
frameFolders = frameFolders(sortIdx);

%% -------------------------- Choose frames to plot ------------------------

if strcmpi(mode, 'single_frame')
    frameIdx = find(frameNumbers == singleFrameNumber, 1);

    if isempty(frameIdx)
        error('Frame folder "%d" was not found.', singleFrameNumber);
    end

    framesToPlot = frameIdx;

elseif strcmpi(mode, 'animate')
    framesToPlot = 1:frameStride:numel(frameNumbers);

else
    error('mode must be either "single_frame" or "animate".');
end

%% -------------------------- Create figure -------------------------------

hFig = figure('Position', figurePosition, 'Color', 'w');
axis equal;
grid on;
box on;
hold on;

xlabel('X, cm');
ylabel('Y, cm');
zlabel('Z, cm');

view(viewAzimuthDeg, viewElevationDeg);
camlight('headlight');
lighting gouraud;

%% -------------------------- Plot / animate ------------------------------

for k = framesToPlot

    if ~isvalid(hFig)
        disp('Figure was closed. Stopping visualization.');
        break;
    end

    cla;
    hold on;

    frameNum = frameNumbers(k);
    frameFolder = frameFolders{k};

    fprintf('Showing frame %d\n', frameNum);

    allVertices = [];

    for b = 1:numel(boneNames)

        boneName = boneNames{b};

        stlFile = fullfile(frameFolder, sprintf('%s_%d.stl', boneName, frameNum));

        if ~isfile(stlFile)
            warning('Missing STL file:\n%s', stlFile);
            continue;
        end

        [faces, vertices] = readSTLAsFacesVertices(stlFile);

        if isempty(faces) || isempty(vertices)
            warning('Could not read STL file:\n%s', stlFile);
            continue;
        end

        % Choose color
        if strcmpi(boneName, 'Pelvis')
            boneColor = colorPelvis;
        elseif startsWith(boneName, 'R')
            boneColor = colorRight;
        elseif startsWith(boneName, 'L')
            boneColor = colorLeft;
        else
            boneColor = [0.8 0.8 0.8];
        end

        patch('Faces', faces, ...
              'Vertices', vertices, ...
              'FaceColor', boneColor, ...
              'EdgeColor', edgeColor, ...
              'FaceAlpha', boneAlpha);

        allVertices = [allVertices; vertices]; %#ok<AGROW>
    end

    % Set tight fixed-looking limits for the current frame
    if ~isempty(allVertices)
        xlim([min(allVertices(:,1)) - axisPad_cm, max(allVertices(:,1)) + axisPad_cm]);
        ylim([min(allVertices(:,2)) - axisPad_cm, max(allVertices(:,2)) + axisPad_cm]);
        zlim([min(allVertices(:,3)) - axisPad_cm, max(allVertices(:,3)) + axisPad_cm]);
    end

    title(sprintf('STL frame: %d', frameNum));

    drawnow;

    if strcmpi(mode, 'animate')
        pause(pauseTime);
    end
end

%% -------------------------- Helper function -----------------------------
function [faces, vertices] = readSTLAsFacesVertices(stlFile)
%READSTLASFACESVERTICES Read STL file as faces and vertices.
%
% This helper supports different MATLAB stlread output formats:
%   1) triangulation object
%   2) structure with Points and ConnectivityList
%   3) old format with [faces, vertices] output

    faces = [];
    vertices = [];

    try
        stlData = stlread(stlFile);

        if isa(stlData, 'triangulation')
            faces = stlData.ConnectivityList;
            vertices = stlData.Points;

        elseif isstruct(stlData)
            if isfield(stlData, 'ConnectivityList') && isfield(stlData, 'Points')
                faces = stlData.ConnectivityList;
                vertices = stlData.Points;
            elseif isfield(stlData, 'faces') && isfield(stlData, 'vertices')
                faces = stlData.faces;
                vertices = stlData.vertices;
            end
        end

    catch
        try
            [faces, vertices] = stlread(stlFile);
        catch
            faces = [];
            vertices = [];
        end
    end
end