% -------------------------------------------------------------------------
% B08_EulerCheck.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Diagnostic script for checking Euler-angle decomposition at one frame.
%
%   This script visualizes:
%       1) the moving/distal segment frame,
%       2) the target/proximal segment frame,
%       3) optional intermediate frames after each Euler rotation,
%       4) optional angle patches for the three Euler-angle components,
%       5) optional transformed STL bone meshes from B01.
%
% Required workspace variables:
%   Run B01 and B03 before this script.
%
%   B01 provides transformed anatomical points and bone meshes:
%       RFH_transformed, RTKne_transformed, RFAnk_transformed, etc.
%       V_RFemur_transformed, V_RTibia_transformed, V_RFoot_transformed, etc.
%
%   B03 provides segment axes:
%       i_pelvis, j_pelvis, k_pelvis
%       i_Rfemur, j_Rfemur, k_Rfemur
%       i_Rleg,   j_Rleg,   k_Rleg
%       i_Rfoot,  j_Rfoot,  k_Rfoot
%
% Local anatomical-axis convention used in this repository:
%   Local X-axis = i-axis = longitudinal segment axis.
%       Example: femur head to knee, knee to ankle, calcaneus to metatarsal.
%
%   Local Z-axis = k-axis = medio-lateral segment axis.
%       Example: medial-to-lateral anatomical landmarks.
%
%   Local Y-axis = j-axis = cross-product axis.
%       This is computed from the other two axes to complete a right-handed
%       orthonormal coordinate system.
%
% Euler sequence meaning:
%   EulerSeq = 'ZYX'
%       Rotation 1: about local Z/k-axis -> flexion-extension
%       Rotation 2: about local Y/j-axis -> abduction-adduction
%       Rotation 3: about local X/i-axis -> internal-external rotation
%
%   EulerSeq = 'XYZ'
%       Rotation 1: about local X/i-axis -> internal-external rotation
%       Rotation 2: about local Y/j-axis -> abduction-adduction
%       Rotation 3: about local Z/k-axis -> flexion-extension
%
% Notes:
%   sideToCheck controls both the joint-angle check and the STL bones:
%       'right' -> plot right hip/knee/ankle checks and right-side bones
%       'left'  -> plot left hip/knee/ankle checks and left-side bones
%       'both'  -> plot both sides and both sets of bones
%
%   showSTLBones is the only STL display switch. If true, the bones shown
%   follow sideToCheck. If false, no STL bones are plotted.
%
%   The script does not recompute full kinematics. It only checks one frame.
%   It is useful for verifying the geometric meaning of rotm2eul().
% -------------------------------------------------------------------------

%% -------------------------- User parameters -----------------------------

sideToCheck = 'both';           % 'right', 'left', or 'both'

frameSelectionMode = 'cycle_index';
% 'cycle_index'  : selectedCycleIndex is used as an index into CS
% 'frame_number' : selectedFrameNumber is used directly as the frame number

selectedCycleIndex  = 70;       % Used when frameSelectionMode = 'cycle_index'
selectedFrameNumber = 70;       % Used when frameSelectionMode = 'frame_number'

EulerSeq = 'ZYX';               % 'ZYX' or 'XYZ'

showIntermediateFrames = true;  % Show frames after each Euler rotation
showAnglePatches       = true;  % Show angle-sector patches
showJointOrigins       = true;  % Show hip/knee/ankle origin points

% STL bone display mode.
%   true  : plot pelvis + bones for sideToCheck
%           sideToCheck = 'right' -> pelvis + right femur/tibia/foot
%           sideToCheck = 'left'  -> pelvis + left femur/tibia/foot
%           sideToCheck = 'both'  -> pelvis + both sides
%   false : do not plot STL bones
showSTLBones = true;

axisLength = 1.0;               % Length of plotted local axes
patchRadius = 0.70;             % Radius of angle patches; smaller = cleaner/thinner
numPatchPoints = 100;           % Resolution of angle patches
patchFaceAlpha = 0.28;          % Patch transparency; lower = lighter/less dominant

% Bone visual settings used when showSTLBones = true
pelvisBoneColor = [0.85 0.85 0.85];
rightBoneColor  = [0.80 0.80 1.00];
leftBoneColor   = [0.70 0.88 1.00];
boneFaceAlpha   = 0.28;
boneEdgeColor   = 'none';

figurePosition = [100 100 1350 900];
viewAzimuthDeg = 60;
viewElevationDeg = 20;

% Axis colors: local X=i, Y=j, Z=k
xAxisColor = [0 0 0];           % Black
yAxisColor = [1 0 0];           % Red
zAxisColor = [0 0 1];           % Blue

% Angle colors. The patches use the same colors as the axes, but the
% patchFaceAlpha value above makes them transparent and less visually heavy.
flexExtColor = [0 0 0];         % alpha, flexion-extension
abdAddColor  = [1 0 0];         % beta, abduction-adduction
intExtColor  = [0 0 1];         % gamma, internal-external rotation

movingFrameLineStyle = '-';     % Distal/moving segment frame
targetFrameLineStyle = '--';    % Proximal/target segment frame
intermediateLineStyle = ':';    % Intermediate Euler-step frames

mainAxisLineWidth = 1.8;        % Solid/dashed frame-axis line width
intermediateLineWidth = 0.9;    % Thin intermediate-frame line width

%% -------------------------- Input checks --------------------------------

validSides = {'right', 'left', 'both'};
if ~any(strcmpi(sideToCheck, validSides))
    error('sideToCheck must be ''right'', ''left'', or ''both''.');
end

plotRightSide = strcmpi(sideToCheck, 'right') || strcmpi(sideToCheck, 'both');
plotLeftSide  = strcmpi(sideToCheck, 'left')  || strcmpi(sideToCheck, 'both');

requiredVars = { ...
    'CS', ...
    'i_pelvis', 'j_pelvis', 'k_pelvis'};

if plotRightSide
    requiredVars = [requiredVars, { ...
        'i_Rfemur', 'j_Rfemur', 'k_Rfemur', ...
        'i_Rleg',   'j_Rleg',   'k_Rleg', ...
        'i_Rfoot',  'j_Rfoot',  'k_Rfoot', ...
        'RFH_transformed', 'RTKne_transformed', 'RFAnk_transformed'}];
end

if plotLeftSide
    requiredVars = [requiredVars, { ...
        'i_Lfemur', 'j_Lfemur', 'k_Lfemur', ...
        'i_Lleg',   'j_Lleg',   'k_Lleg', ...
        'i_Lfoot',  'j_Lfoot',  'k_Lfoot', ...
        'LFH_transformed', 'LTKne_transformed', 'LFAnk_transformed'}];
end


% Optional STL bone variables.
% showSTLBones follows sideToCheck. For example, if sideToCheck = 'right',
% only pelvis + right femur/tibia/foot are required and plotted.
if showSTLBones
    boneRequiredVars = {'V_Pelvis_transformed', 'F_Pelvis'};

    if plotRightSide
        boneRequiredVars = [boneRequiredVars, { ...
            'V_RFemur_transformed', 'F_RFemur', ...
            'V_RTibia_transformed', 'F_RTibia', ...
            'V_RFoot_transformed',  'F_RFoot'}];
    end

    if plotLeftSide
        boneRequiredVars = [boneRequiredVars, { ...
            'V_LFemur_transformed', 'F_LFemur', ...
            'V_LTibia_transformed', 'F_LTibia', ...
            'V_LFoot_transformed',  'F_LFoot'}];
    end

    requiredVars = [requiredVars, boneRequiredVars];
end

for v = 1:numel(requiredVars)
    if ~evalin('base', sprintf('exist(''%s'', ''var'')', requiredVars{v}))
        error('Required variable "%s" is missing. Run B01 and B03 first.', requiredVars{v});
    end
end

if ~strcmpi(EulerSeq, 'ZYX') && ~strcmpi(EulerSeq, 'XYZ')
    error('EulerSeq must be either ''ZYX'' or ''XYZ''.');
end

if ~islogical(showSTLBones) || ~isscalar(showSTLBones)
    error('showSTLBones must be true or false.');
end

%% -------------------------- Choose frame --------------------------------

if strcmpi(frameSelectionMode, 'cycle_index')
    if selectedCycleIndex < 1 || selectedCycleIndex > numel(CS)
        error('selectedCycleIndex must be between 1 and length(CS).');
    end

    t = CS(selectedCycleIndex);

elseif strcmpi(frameSelectionMode, 'frame_number')
    t = selectedFrameNumber;

else
    error('frameSelectionMode must be ''cycle_index'' or ''frame_number''.');
end

fprintf('\nEuler check\n');
fprintf('  Side          : %s\n', sideToCheck);
fprintf('  Euler sequence: %s\n', EulerSeq);
fprintf('  Frame number  : %d\n\n', t);

%% -------------------------- Build segment frames -------------------------
% Frames are stored as 3-by-3 matrices:
%   column 1 = local X = i-axis
%   column 2 = local Y = j-axis
%   column 3 = local Z = k-axis

Frame_pelvis = makeFrame(i_pelvis(t,:), j_pelvis(t,:), k_pelvis(t,:));

sideList = {};
if plotRightSide
    sideList{end+1} = 'right'; %#ok<SAGROW>
end
if plotLeftSide
    sideList{end+1} = 'left'; %#ok<SAGROW>
end

SideData = struct();

for sIdx = 1:numel(sideList)
    sideName = sideList{sIdx};

    if strcmpi(sideName, 'right')
        Frame_femur = makeFrame(i_Rfemur(t,:), j_Rfemur(t,:), k_Rfemur(t,:));
        Frame_leg   = makeFrame(i_Rleg(t,:),   j_Rleg(t,:),   k_Rleg(t,:));
        Frame_foot  = makeFrame(i_Rfoot(t,:),  j_Rfoot(t,:),  k_Rfoot(t,:));

        origin_hip   = RFH_transformed(t,:)';
        origin_knee  = RTKne_transformed(t,:)';
        origin_ankle = RFAnk_transformed(t,:)';
    else
        Frame_femur = makeFrame(i_Lfemur(t,:), j_Lfemur(t,:), k_Lfemur(t,:));
        Frame_leg   = makeFrame(i_Lleg(t,:),   j_Lleg(t,:),   k_Lleg(t,:));
        Frame_foot  = makeFrame(i_Lfoot(t,:),  j_Lfoot(t,:),  k_Lfoot(t,:));

        origin_hip   = LFH_transformed(t,:)';
        origin_knee  = LTKne_transformed(t,:)';
        origin_ankle = LFAnk_transformed(t,:)';
    end

    %% ---------------------- Relative rotations -------------------------
    % Each relative rotation maps the distal/moving segment frame to the
    % proximal/target segment frame:
    %   Hip   : femur -> pelvis
    %   Knee  : leg   -> femur
    %   Ankle : foot  -> leg

    R_hip   = Frame_femur' * Frame_pelvis;
    R_knee  = Frame_leg'   * Frame_femur;
    R_ankle = Frame_foot'  * Frame_leg;

    angles_hip_rad   = rotm2eul(R_hip,   EulerSeq);
    angles_knee_rad  = rotm2eul(R_knee,  EulerSeq);
    angles_ankle_rad = rotm2eul(R_ankle, EulerSeq);

    angles_hip_deg   = rad2deg(angles_hip_rad);
    angles_knee_deg  = rad2deg(angles_knee_rad);
    angles_ankle_deg = rad2deg(angles_ankle_rad);

    % Store results using the same variable style used by B03.
    if strcmpi(sideName, 'right')
        R_Rhip{t,1}   = R_hip;   %#ok<SAGROW>
        R_Rknee{t,1}  = R_knee;  %#ok<SAGROW>
        R_Rankle{t,1} = R_ankle; %#ok<SAGROW>

        Joint_Angles_Rhip(t,:)   = angles_hip_rad;   %#ok<SAGROW>
        Joint_Angles_Rknee(t,:)  = angles_knee_rad;  %#ok<SAGROW>
        Joint_Angles_Rankle(t,:) = angles_ankle_rad; %#ok<SAGROW>

        Joint_Angles_Rhip_deg(t,:)   = angles_hip_deg;   %#ok<SAGROW>
        Joint_Angles_Rknee_deg(t,:)  = angles_knee_deg;  %#ok<SAGROW>
        Joint_Angles_Rankle_deg(t,:) = angles_ankle_deg; %#ok<SAGROW>
    else
        R_Lhip{t,1}   = R_hip;   %#ok<SAGROW>
        R_Lknee{t,1}  = R_knee;  %#ok<SAGROW>
        R_Lankle{t,1} = R_ankle; %#ok<SAGROW>

        Joint_Angles_Lhip(t,:)   = angles_hip_rad;   %#ok<SAGROW>
        Joint_Angles_Lknee(t,:)  = angles_knee_rad;  %#ok<SAGROW>
        Joint_Angles_Lankle(t,:) = angles_ankle_rad; %#ok<SAGROW>

        Joint_Angles_Lhip_deg(t,:)   = angles_hip_deg;   %#ok<SAGROW>
        Joint_Angles_Lknee_deg(t,:)  = angles_knee_deg;  %#ok<SAGROW>
        Joint_Angles_Lankle_deg(t,:) = angles_ankle_deg; %#ok<SAGROW>
    end

    SideData.(sideName).Frame_femur = Frame_femur;
    SideData.(sideName).Frame_leg = Frame_leg;
    SideData.(sideName).Frame_foot = Frame_foot;
    SideData.(sideName).origin_hip = origin_hip;
    SideData.(sideName).origin_knee = origin_knee;
    SideData.(sideName).origin_ankle = origin_ankle;
    SideData.(sideName).R_hip = R_hip;
    SideData.(sideName).R_knee = R_knee;
    SideData.(sideName).R_ankle = R_ankle;
    SideData.(sideName).angles_hip_deg = angles_hip_deg;
    SideData.(sideName).angles_knee_deg = angles_knee_deg;
    SideData.(sideName).angles_ankle_deg = angles_ankle_deg;
    SideData.(sideName).hipSteps = computeEulerStepFrames(Frame_femur, angles_hip_rad, EulerSeq);
    SideData.(sideName).kneeSteps = computeEulerStepFrames(Frame_leg, angles_knee_rad, EulerSeq);
    SideData.(sideName).ankleSteps = computeEulerStepFrames(Frame_foot, angles_ankle_rad, EulerSeq);
end

%% -------------------------- Print results -------------------------------

angleNames = getAngleNames(EulerSeq);

for sIdx = 1:numel(sideList)
    sideName = sideList{sIdx};

    fprintf('%s side:\n', upperFirst(sideName));
    printEulerAngles('Hip',   angleNames, SideData.(sideName).angles_hip_deg);
    printEulerAngles('Knee',  angleNames, SideData.(sideName).angles_knee_deg);
    printEulerAngles('Ankle', angleNames, SideData.(sideName).angles_ankle_deg);
end

%% -------------------------- Plot ----------------------------------------

figure('Position', figurePosition, 'Color', 'w');
hold on;
grid on;
box on;
axis equal;

xlabel('X, cm');
ylabel('Y, cm');
zlabel('Z, cm');
title(sprintf('%s side Euler check | frame %d | sequence %s', ...
      upperFirst(sideToCheck), t, EulerSeq));


% Optional transformed STL bones. Plot bones first so the axes and patches
% stay visible on top of the semi-transparent bone surfaces.
if showSTLBones

    % Pelvis is shown whenever STL bones are enabled.
    plotBoneMesh(V_Pelvis_transformed{t,1}, F_Pelvis, pelvisBoneColor, boneFaceAlpha, boneEdgeColor);

    % sideToCheck controls which limb bones are plotted.
    if plotRightSide
        plotBoneMesh(V_RFemur_transformed{t,1}, F_RFemur, rightBoneColor, boneFaceAlpha, boneEdgeColor);
        plotBoneMesh(V_RTibia_transformed{t,1}, F_RTibia, rightBoneColor, boneFaceAlpha, boneEdgeColor);
        plotBoneMesh(V_RFoot_transformed{t,1},  F_RFoot,  rightBoneColor, boneFaceAlpha, boneEdgeColor);
    end

    if plotLeftSide
        plotBoneMesh(V_LFemur_transformed{t,1}, F_LFemur, leftBoneColor, boneFaceAlpha, boneEdgeColor);
        plotBoneMesh(V_LTibia_transformed{t,1}, F_LTibia, leftBoneColor, boneFaceAlpha, boneEdgeColor);
        plotBoneMesh(V_LFoot_transformed{t,1},  F_LFoot,  leftBoneColor, boneFaceAlpha, boneEdgeColor);
    end
end

% Plot Euler-frame checks for the selected side(s).
for sIdx = 1:numel(sideList)
    sideName = sideList{sIdx};
    sideTitle = upperFirst(sideName);

    % Hip: femur frame should rotate to pelvis frame
    plotJointEulerCheck(SideData.(sideName).origin_hip, 'hip', ...
        SideData.(sideName).Frame_femur, Frame_pelvis, SideData.(sideName).hipSteps, ...
        [sideTitle, ' hip: femur -> pelvis'], axisLength, showIntermediateFrames, ...
        showAnglePatches, EulerSeq, patchRadius, numPatchPoints, patchFaceAlpha, ...
        movingFrameLineStyle, targetFrameLineStyle, intermediateLineStyle, ...
        xAxisColor, yAxisColor, zAxisColor, flexExtColor, abdAddColor, intExtColor, ...
        mainAxisLineWidth, intermediateLineWidth);

    % Knee: leg frame should rotate to femur frame
    plotJointEulerCheck(SideData.(sideName).origin_knee, 'knee', ...
        SideData.(sideName).Frame_leg, SideData.(sideName).Frame_femur, SideData.(sideName).kneeSteps, ...
        [sideTitle, ' knee: leg -> femur'], axisLength, showIntermediateFrames, ...
        showAnglePatches, EulerSeq, patchRadius, numPatchPoints, patchFaceAlpha, ...
        movingFrameLineStyle, targetFrameLineStyle, intermediateLineStyle, ...
        xAxisColor, yAxisColor, zAxisColor, flexExtColor, abdAddColor, intExtColor, ...
        mainAxisLineWidth, intermediateLineWidth);

    % Ankle: foot frame should rotate to leg frame
    plotJointEulerCheck(SideData.(sideName).origin_ankle, 'ankle', ...
        SideData.(sideName).Frame_foot, SideData.(sideName).Frame_leg, SideData.(sideName).ankleSteps, ...
        [sideTitle, ' ankle: foot -> leg'], axisLength, showIntermediateFrames, ...
        showAnglePatches, EulerSeq, patchRadius, numPatchPoints, patchFaceAlpha, ...
        movingFrameLineStyle, targetFrameLineStyle, intermediateLineStyle, ...
        xAxisColor, yAxisColor, zAxisColor, flexExtColor, abdAddColor, intExtColor, ...
        mainAxisLineWidth, intermediateLineWidth);
end

if showJointOrigins
    for sIdx = 1:numel(sideList)
        sideName = sideList{sIdx};
        plot3(SideData.(sideName).origin_hip(1), ...
              SideData.(sideName).origin_hip(2), ...
              SideData.(sideName).origin_hip(3), ...
              'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 5);
        plot3(SideData.(sideName).origin_knee(1), ...
              SideData.(sideName).origin_knee(2), ...
              SideData.(sideName).origin_knee(3), ...
              'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 5);
        plot3(SideData.(sideName).origin_ankle(1), ...
              SideData.(sideName).origin_ankle(2), ...
              SideData.(sideName).origin_ankle(3), ...
              'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 5);
    end
end

view(viewAzimuthDeg, viewElevationDeg);

% Dummy handles for a clean legend.
hX = plot3(nan, nan, nan, '-',  'Color', xAxisColor, 'LineWidth', mainAxisLineWidth);
hY = plot3(nan, nan, nan, '-',  'Color', yAxisColor, 'LineWidth', mainAxisLineWidth);
hZ = plot3(nan, nan, nan, '-',  'Color', zAxisColor, 'LineWidth', mainAxisLineWidth);
hMoving = plot3(nan, nan, nan, movingFrameLineStyle, 'Color', [0.3 0.3 0.3], 'LineWidth', mainAxisLineWidth);
hTarget = plot3(nan, nan, nan, targetFrameLineStyle, 'Color', [0.3 0.3 0.3], 'LineWidth', mainAxisLineWidth);

legendHandles = [hX, hY, hZ, hMoving, hTarget];
legendLabels = {'X/i: longitudinal', 'Y/j: cross-product', 'Z/k: medio-lateral', ...
                'Moving/distal frame', 'Target/proximal frame'};

if showSTLBones
    hPelvisBone = plot3(nan, nan, nan, 's', ...
                        'MarkerFaceColor', pelvisBoneColor, ...
                        'MarkerEdgeColor', [0.3 0.3 0.3], ...
                        'MarkerSize', 7);
    legendHandles = [legendHandles, hPelvisBone];
    legendLabels = [legendLabels, {'Pelvis mesh'}];

    if plotRightSide
        hRightBone = plot3(nan, nan, nan, 's', ...
                           'MarkerFaceColor', rightBoneColor, ...
                           'MarkerEdgeColor', [0.3 0.3 0.3], ...
                           'MarkerSize', 7);
        legendHandles = [legendHandles, hRightBone];
        legendLabels = [legendLabels, {'Right bone mesh'}];
    end

    if plotLeftSide
        hLeftBone = plot3(nan, nan, nan, 's', ...
                          'MarkerFaceColor', leftBoneColor, ...
                          'MarkerEdgeColor', [0.3 0.3 0.3], ...
                          'MarkerSize', 7);
        legendHandles = [legendHandles, hLeftBone];
        legendLabels = [legendLabels, {'Left bone mesh'}];
    end
end

legend(legendHandles, legendLabels, ...
       'Location', 'northeastoutside', ...
       'AutoUpdate', 'off');

%% -------------------------- Local functions -----------------------------

function Frame = makeFrame(iAxis, jAxis, kAxis)
%MAKEFRAME Build a 3-by-3 local coordinate frame.
%   Columns are local X=i, local Y=j, local Z=k.

    Frame = [unitVector(iAxis(:)), unitVector(jAxis(:)), unitVector(kAxis(:))];
end

function steps = computeEulerStepFrames(startFrame, eulAngles, EulerSeq)
%COMPUTEEULERSTEPFRAMES Apply Euler rotations one-by-one.
%   steps{1}: frame after first Euler rotation
%   steps{2}: frame after second Euler rotation
%   steps{3}: frame after third Euler rotation

    steps = cell(3,1);
    currentFrame = startFrame;

    for ii = 1:3
        switch upper(EulerSeq(ii))
            case 'X'
                Rstep = rotX(eulAngles(ii));
            case 'Y'
                Rstep = rotY(eulAngles(ii));
            case 'Z'
                Rstep = rotZ(eulAngles(ii));
            otherwise
                error('Unsupported Euler axis.');
        end

        currentFrame = currentFrame * Rstep;
        steps{ii} = currentFrame;
    end
end


function plotBoneMesh(vertices, faces, faceColor, faceAlpha, edgeColor)
%PLOTBONEMESH Plot one transformed STL bone mesh.
%   This keeps only valid faces so added landmark vertices that are not part
%   of the surface do not interfere with visualization.

    if isempty(vertices) || isempty(faces)
        return;
    end

    % Keep only triangular faces with valid vertex indices.
    validFaceRows = all(isfinite(faces), 2) & ...
                    all(faces >= 1, 2) & ...
                    all(faces <= size(vertices, 1), 2);

    faces = faces(validFaceRows, :);

    if isempty(faces)
        return;
    end

    patch('Faces', faces, ...
          'Vertices', vertices, ...
          'FaceColor', faceColor, ...
          'EdgeColor', edgeColor, ...
          'FaceAlpha', faceAlpha, ...
          'AmbientStrength', 0.7);
end

function plotJointEulerCheck(origin, jointName, movingFrame, targetFrame, stepFrames, labelText, ...
                             axisLength, showIntermediateFrames, showAnglePatches, ...
                             EulerSeq, patchRadius, numPatchPoints, patchFaceAlpha, ...
                             movingLineStyle, targetLineStyle, intermediateLineStyle, ...
                             xAxisColor, yAxisColor, zAxisColor, ...
                             flexExtColor, abdAddColor, intExtColor, ...
                             mainLineWidth, intermediateLineWidth)
%PLOTJOINTEULERCHECK Plot one joint frame pair and its Euler steps.

    % Moving/distal frame
    plotFrame(origin, movingFrame, axisLength, movingLineStyle, ...
              xAxisColor, yAxisColor, zAxisColor, mainLineWidth);

    % Target/proximal frame
    plotFrame(origin, targetFrame, axisLength, targetLineStyle, ...
              xAxisColor, yAxisColor, zAxisColor, mainLineWidth);

    if showIntermediateFrames
        for ii = 1:3
            plotFrame(origin, stepFrames{ii}, axisLength, intermediateLineStyle, ...
                      xAxisColor, yAxisColor, zAxisColor, intermediateLineWidth);
        end
    end

    if showAnglePatches
        % The angle-patch vectors below follow the original B07_EulerCheck
        % visual convention. This is intentionally not a generic Euler-step
        % patch, because the original code chose specific anatomical vectors
        % for each joint so that the colored sector appears on the expected
        % side of the joint.
        plotOriginalAnglePatches(origin, jointName, movingFrame, targetFrame, stepFrames, ...
            EulerSeq, patchRadius, numPatchPoints, patchFaceAlpha, ...
            flexExtColor, abdAddColor, intExtColor);
    end

    text(origin(1), origin(2), origin(3), ['  ', labelText], ...
         'FontSize', 9, 'FontWeight', 'normal', 'Color', [0.15 0.15 0.15]);
end

function plotFrame(origin, Frame, axisLength, lineStyle, xColor, yColor, zColor, lineWidth)
%PLOTFRAME Plot local X/i, Y/j, and Z/k axes.

    colors = {xColor, yColor, zColor};

    for ii = 1:3
        endpoint = origin + axisLength * Frame(:,ii);

        plot3([origin(1), endpoint(1)], ...
              [origin(2), endpoint(2)], ...
              [origin(3), endpoint(3)], ...
              'LineStyle', lineStyle, ...
              'Color', colors{ii}, ...
              'LineWidth', lineWidth);
    end
end

function plotOriginalAnglePatches(origin, jointName, movingFrame, targetFrame, stepFrames, ...
                                    EulerSeq, radius, nPts, faceAlpha, ...
                                    flexExtColor, abdAddColor, intExtColor)
%PLOTORIGINALANGLEPATCHES Plot angle patches using the original B07 geometry.
%
% The vectors are kept consistent with the original B07_EulerCheck.m script.
% This preserves the same colored side/orientation of the patches while the
% rest of the code is cleaner and easier to maintain.
%
% Color convention used in this repository:
%   alpha = flexion-extension          -> black
%   betha = abduction-adduction        -> red
%   gamma = internal-external rotation -> blue
%
% For EulerSeq = 'ZYX':
%   alpha is associated with the Z/k rotation, betha with Y/j, gamma with X/i.
%
% For EulerSeq = 'XYZ':
%   gamma patch is drawn in black, betha in red, and alpha in blue, matching
%   the original visual check script.

    jointName = lower(jointName);
    S1 = stepFrames{1};
    S2 = stepFrames{2};

    switch upper(EulerSeq)
        case 'ZYX'
            % -------------------- gamma patch: blue --------------------
            switch jointName
                case 'hip'
                    v1 = -S1(:,2);          % original: -R_step1_Rhip(:,2)
                    v2 = -movingFrame(:,1); % original: -Frame_Rfemur(:,1)
                case 'knee'
                    v1 = -S1(:,1);          % original: -R_step1_Rknee(:,1)
                    v2 = -movingFrame(:,1); % original: -Frame_Rleg(:,1)
                case 'ankle'
                    v1 = -S1(:,2);          % original: -R_step1_Rankle(:,2)
                    v2 = -movingFrame(:,1); % original: -Frame_Rfoot(:,1)
                otherwise
                    error('Unsupported joint name: %s', jointName);
            end
            drawAnglePatch(origin, v1, v2, radius, nPts, intExtColor, faceAlpha);

            % -------------------- betha patch: red ---------------------
            v1 = S1(:,1);
            v2 = S2(:,1);
            drawAnglePatch(origin, v1, v2, radius, nPts, abdAddColor, faceAlpha);

            % -------------------- alpha patch: black -------------------
            v1 = -S2(:,3);
            v2 = -targetFrame(:,3);
            drawAnglePatch(origin, v1, v2, radius, nPts, flexExtColor, faceAlpha);

        case 'XYZ'
            % -------------------- gamma patch: black -------------------
            v1 = S1(:,3);
            v2 = movingFrame(:,3);
            drawAnglePatch(origin, v1, v2, radius, nPts, flexExtColor, faceAlpha);

            % -------------------- betha patch: red ---------------------
            v1 = S1(:,1);
            v2 = S2(:,1);
            drawAnglePatch(origin, v1, v2, radius, nPts, abdAddColor, faceAlpha);

            % -------------------- alpha patch: blue --------------------
            v1 = -S2(:,1);

            switch jointName
                case 'hip'
                    v2 = -targetFrame(:,2); % original: -Frame_pelvis(:,2)
                case 'knee'
                    v2 = -targetFrame(:,1); % original: -Frame_Rfemur(:,1)
                case 'ankle'
                    v2 = -targetFrame(:,2); % original: -Frame_Rleg(:,2)
                otherwise
                    error('Unsupported joint name: %s', jointName);
            end

            drawAnglePatch(origin, v1, v2, radius, nPts, intExtColor, faceAlpha);

        otherwise
            error('EulerSeq must be either ''ZYX'' or ''XYZ''.');
    end
end

function drawAnglePatch(origin, v1, v2, radius, nPts, faceColor, faceAlpha)
%DRAWANGLEPATCH Draw a colored sector between two vectors.
%
% This uses the same Delaunay/convex-hull surface style as the original
% B07_EulerCheck.m code. That keeps the visible/colorful side of the patch
% consistent with the original figure.

    origin = origin(:)';
    v1 = unitVector(v1);
    v2 = unitVector(v2);

    if any(isnan(v1)) || any(isnan(v2))
        return;
    end

    pointsAlongArc = zeros(nPts, 3);

    for kk = 1:nPts
        s = (kk - 1) / (nPts - 1);
        v = (1 - s) * v1 + s * v2;

        if norm(v) < eps
            continue;
        end

        v = radius * unitVector(v);
        pointsAlongArc(kk,:) = origin + v(:)';
    end

    pointsAlongArc = pointsAlongArc(any(pointsAlongArc ~= 0, 2), :);

    if size(pointsAlongArc, 1) < 3
        return;
    end

    pointsSurface = [pointsAlongArc; origin];

    try
        DT = delaunayTriangulation(pointsSurface(:,1), pointsSurface(:,2), pointsSurface(:,3));

        if ~isempty(DT.ConnectivityList)
            [faces, ~] = convexHull(DT);

            patch('Faces', faces, ...
                  'Vertices', DT.Points, ...
                  'FaceColor', faceColor, ...
                  'EdgeColor', 'none', ...
                  'FaceAlpha', faceAlpha, ...
                  'AmbientStrength', 0.7);
            return;
        end
    catch
        % Fall back to a simple fan if convexHull fails for nearly planar points.
    end

    vertices = [origin; pointsAlongArc];
    faces = zeros(size(pointsAlongArc,1)-1, 3);

    for kk = 1:size(pointsAlongArc,1)-1
        faces(kk,:) = [1, kk+1, kk+2];
    end

    patch('Faces', faces, ...
          'Vertices', vertices, ...
          'FaceColor', faceColor, ...
          'EdgeColor', 'none', ...
          'FaceAlpha', faceAlpha);
end

function colors = getAngleColors(EulerSeq, flexExtColor, abdAddColor, intExtColor)
%GETANGLECOLORS Assign colors to the Euler rotations.

    colors = cell(1,3);

    for ii = 1:3
        switch upper(EulerSeq(ii))
            case 'Z'
                colors{ii} = flexExtColor;   % Flexion-extension
            case 'Y'
                colors{ii} = abdAddColor;    % Abduction-adduction
            case 'X'
                colors{ii} = intExtColor;    % Internal-external rotation
        end
    end
end

function names = getAngleNames(EulerSeq)
%GETANGLENAMES Human-readable angle names for printing.

    names = cell(1,3);

    for ii = 1:3
        switch upper(EulerSeq(ii))
            case 'Z'
                names{ii} = 'flexion-extension';
            case 'Y'
                names{ii} = 'abduction-adduction';
            case 'X'
                names{ii} = 'internal-external rotation';
        end
    end
end

function printEulerAngles(jointName, angleNames, angleDeg)
%PRINTEULERANGLES Print the three Euler-angle values.

    fprintf('%s angles:\n', jointName);

    for ii = 1:3
        fprintf('  %d) %-28s = %8.3f deg\n', ii, angleNames{ii}, angleDeg(ii));
    end

    fprintf('\n');
end

function v = unitVector(v)
%UNITVECTOR Normalize a vector safely.

    v = v(:);
    n = norm(v);

    if n < eps
        v = [nan; nan; nan];
    else
        v = v / n;
    end
end

function R = rotX(a)
%ROTX Rotation matrix about local X-axis.

    R = [1,       0,        0; ...
         0,  cos(a),  -sin(a); ...
         0,  sin(a),   cos(a)];
end

function R = rotY(a)
%ROTY Rotation matrix about local Y-axis.

    R = [ cos(a),  0,  sin(a); ...
               0,  1,       0; ...
         -sin(a),  0,  cos(a)];
end

function R = rotZ(a)
%ROTZ Rotation matrix about local Z-axis.

    R = [cos(a),  -sin(a),  0; ...
         sin(a),   cos(a),  0; ...
              0,        0,  1];
end

function txt = upperFirst(txt)
%UPPERFIRST Capitalize first character of a string.

    if isempty(txt)
        return;
    end

    txt = lower(txt);
    txt(1) = upper(txt(1));
end
