function B09_Error_ROM_Sensitivity_to_MWF()
% -------------------------------------------------------------------------
% B09_Error_ROM_Sensitivity_to_MWF.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Runs MWF sensitivity analysis without permanently changing B01.
%
%   The original B01 can stay in the normal/default form:
%
%       MWF = 1;
%
%   This script creates a temporary copy of B01, makes only the temporary
%   copy load a temporary MWF file, runs B01/B03/B05 for each MWF value,
%   and stores all outputs in one structure:
%
%       MWFResults
%
%   No separate MWF_TotalError_*.mat files are created.
%
%   The old B11 plotting logic is included here, but now it plots directly
%   from MWFResults instead of loading many separate .mat files.
% -------------------------------------------------------------------------

clc;

%% -------------------------- User parameters -----------------------------

MWF_values = 1:30;                         % MWF values to test

B01_fileName = 'B01_Registration_WithoutFlow_3DScale_WithMWF.m';
B03_script   = 'B03_Kinematics_3D_And_Cycles_R1_MLaxis';
B05_script   = 'B05_Error_Computation';

resultsFileName = 'MWF_SensitivityResults.mat';   % one output file only
saveAfterEachMWF = true;                          % protects progress
makePlotsAtEnd   = true;                          % show only the B11-style summary plots after the loop

% Set this to true when MWF_SensitivityResults.mat already exists and you
% only want to regenerate the plots without rerunning B01/B03/B05.
plotExistingResultsOnly = false;

deleteTemporaryB01    = true;                     % removes temporary B01 after run
deleteTemporaryMWFMat = true;                     % removes temporary MWF mat after run
stopIfOneMWFFails     = true;                     % true = stop on error

% If old separate MWF_TotalError_*.mat files are already present from
% previous versions, this can delete them to avoid confusion.
deleteOldSeparateMWFFiles = false;

% Store detailed B03/B05 variables inside MWFResults.Runs(i).Details.
% This is useful for future analysis, but makes MWF_SensitivityResults.mat
% larger.
storeDetailedVariables = true;

% Plot settings used by the built-in B11-style summary plots.
plotFontSize = 12;
plotLineWidth = 1.5;
plotColor = [0.45 0.55 0.95];                 % soft blue

%% -------------------------- Locate B01 and use its folder ----------------

B01_originalPath = findScriptFile(B01_fileName);
B01_folder       = fileparts(B01_originalPath);

% B01 uses relative paths such as load('PelvisBoneMarks.mat'). Therefore,
% run the whole sensitivity analysis from the B01 folder.
originalFolder = pwd;
cd(B01_folder);
cleanupFolder = onCleanup(@() cd(originalFolder)); %#ok<NASGU>

resultsMatPath = fullfile(B01_folder, resultsFileName);
MWF_tempMatPath = fullfile(B01_folder, 'B10_MWF_TEMP.mat');

%% -------------------------- Plot-only mode ------------------------------

if plotExistingResultsOnly
    if ~isfile(resultsMatPath)
        error('Could not find existing MWF result file:\n%s', resultsMatPath);
    end

    loadedData = load(resultsMatPath, 'MWFResults');
    MWFResults = loadedData.MWFResults;

    assignin('base', 'MWFResults', MWFResults);
    assignB11CompatibleTablesToBase(MWFResults);

    plotMWFSensitivityResults(MWFResults, plotFontSize, plotLineWidth, plotColor);

    fprintf('Plotted existing MWFResults from:\n%s\n', resultsMatPath);
    return;
end

%% -------------------------- Optional cleanup ----------------------------

if deleteOldSeparateMWFFiles
    deleteOldMWFResultFiles();
end

%% -------------------------- Create temporary B01 ------------------------

B01_tempPath = fullfile(B01_folder, ...
    'B01_Registration_WithoutFlow_3DScale_WithMWF_TEMP_FOR_B10.m');

createTemporaryB01(B01_originalPath, B01_tempPath);

if deleteTemporaryB01
    cleanupTempB01 = onCleanup(@() deleteFileIfItExists(B01_tempPath)); %#ok<NASGU>
end

if deleteTemporaryMWFMat
    cleanupTempMWF = onCleanup(@() deleteFileIfItExists(MWF_tempMatPath)); %#ok<NASGU>
end

fprintf('Original B01 file is unchanged:\n%s\n\n', B01_originalPath);
fprintf('Temporary B01 file used by B10:\n%s\n\n', B01_tempPath);
fprintf('Temporary MWF file used by B10:\n%s\n\n', MWF_tempMatPath);
fprintf('One output structure file:\n%s\n\n', resultsMatPath);

%% -------------------------- Initialize result structure -----------------

summaryNames = {'alpha_hip',   'betha_hip',   'gamma_hip', ...
                'alpha_knee',  'betha_knee',  'gamma_knee', ...
                'alpha_ankle', 'betha_ankle', 'gamma_ankle'};

summaryLabels = {'alpha hip',   'betha hip',   'gamma hip', ...
                 'alpha knee',  'betha knee',  'gamma knee', ...
                 'alpha ankle', 'betha ankle', 'gamma ankle'};

summaryHeaders = {'WeightFactor', 'meanTotalError', 'maxTotalError', ...
                  'ROM', 'max', 'min', 'mean'};

summaryMatrices = struct();
for iSummary = 1:numel(summaryNames)
    summaryMatrices.(summaryNames{iSummary}) = nan(numel(MWF_values), numel(summaryHeaders));
end

MWFResults = struct();
MWFResults.Metadata.createdBy = 'B10_Error_ROM_Sensitivity_to_MWF';
MWFResults.Metadata.createdOn = char(datetime('now'));
MWFResults.Metadata.originalB01 = B01_originalPath;
MWFResults.Metadata.temporaryB01 = B01_tempPath;
MWFResults.Metadata.B03_script = B03_script;
MWFResults.Metadata.B05_script = B05_script;
MWFResults.Metadata.note = ['Original B01 is not edited. ', ...
                            'All MWF outputs are stored in this single structure.'];

MWFResults.Parameters.MWF_values = MWF_values;
MWFResults.Parameters.storeDetailedVariables = storeDetailedVariables;
MWFResults.Parameters.resultsFileName = resultsFileName;

MWFResults.SummaryHeaders = summaryHeaders;
MWFResults.SummaryLabels  = summaryLabels;
MWFResults.Runs = cell(numel(MWF_values), 1);
MWFResults.Tables = struct();
MWFResults.B11Compatible = struct();

%% -------------------------- Main MWF loop -------------------------------

for iMWF = 1:numel(MWF_values)

    MWF = MWF_values(iMWF);

    fprintf('\n============================================================\n');
    fprintf('Running MWF sensitivity: %d of %d | MWF = %g\n', ...
            iMWF, numel(MWF_values), MWF);
    fprintf('============================================================\n\n');

    % Save the MWF value for the temporary B01 file.
    save(MWF_tempMatPath, 'MWF');

    try
        % Run B01 in the base workspace. B01 contains "clear; clc;", so it
        % should not be run inside this B10 function workspace.
        evalin('base', sprintf('run(''%s'');', escapePathForEval(B01_tempPath)));

        % Confirm that the temporary B01 actually used this MWF.
        MWF_usedByB01 = evalin('base', 'MWF');
        fprintf('MWF confirmed after temporary B01 run = %g\n', MWF_usedByB01);

        if ~isequal(MWF_usedByB01, MWF)
            warning('Requested MWF = %g, but temporary B01 used MWF = %g.', ...
                    MWF, MWF_usedByB01);
        end

        % Run kinematics and error scripts.
        evalin('base', [B03_script ';']);
        evalin('base', [B05_script ';']);

        % B03 computes ROM variables. This helper computes extra stance
        % max/min/mean values needed by the old B11-style plots.
        computeStanceSummaryVariablesInBase();

        % Collect one run into a structure.
        runData = collectCurrentRunData(iMWF, MWF, storeDetailedVariables);
        runData.Status.success = true;
        runData.Status.message = 'Completed';

        % Fill summary matrices used for B11-style plots.
        summaryMatrices = fillSummaryMatrices(summaryMatrices, iMWF, MWF, runData);

    catch ME
        runData = struct();
        runData.MWF = MWF;
        runData.Index = iMWF;
        runData.Status.success = false;
        runData.Status.message = ME.message;
        runData.Status.report = getReport(ME, 'extended', 'hyperlinks', 'off');

        fprintf(2, '\nMWF = %g failed:\n%s\n\n', MWF, ME.message);

        if stopIfOneMWFFails
            MWFResults.Runs{iMWF} = runData;
            MWFResults.SummaryMatrices = summaryMatrices;
            MWFResults = updateResultTables(MWFResults, summaryMatrices, summaryHeaders);
            save(resultsMatPath, 'MWFResults', '-v7.3');
            rethrow(ME);
        end
    end

    MWFResults.Runs{iMWF} = runData;
    MWFResults.SummaryMatrices = summaryMatrices;
    MWFResults = updateResultTables(MWFResults, summaryMatrices, summaryHeaders);

    % Save one big structure after every MWF value.
    if saveAfterEachMWF
        save(resultsMatPath, 'MWFResults', '-v7.3');
        fprintf('Intermediate MWFResults saved to:\n%s\n', resultsMatPath);
    end
end

%% -------------------------- Final save and plots ------------------------

MWFResults.Metadata.finishedOn = char(datetime('now'));
MWFResults.SummaryMatrices = summaryMatrices;
MWFResults = updateResultTables(MWFResults, summaryMatrices, summaryHeaders);

save(resultsMatPath, 'MWFResults', '-v7.3');

assignin('base', 'MWFResults', MWFResults);
assignB11CompatibleTablesToBase(MWFResults);

if makePlotsAtEnd
    plotMWFSensitivityResults(MWFResults, plotFontSize, plotLineWidth, plotColor);
end

fprintf('\nDone. Original B01 was not permanently changed.\n');
fprintf('All results are stored in:\n%s\n', resultsMatPath);

end

%% ========================== Local functions =============================

function scriptPath = findScriptFile(fileName)
%FINDSCRIPTFILE Find a script in the current folder or MATLAB path.

    scriptPath = which(fileName);

    if isempty(scriptPath)
        localPath = fullfile(pwd, fileName);

        if isfile(localPath)
            scriptPath = localPath;
        else
            error('Could not find required file:\n%s', fileName);
        end
    end
end

function createTemporaryB01(originalB01Path, tempB01Path)
%CREATETEMPORARYB01 Create a temporary B01 copy that loads B10_MWF_TEMP.mat.
%
% The original B01 file is not changed.

    txt = fileread(originalB01Path);

    if contains(txt, sprintf('\r\n'))
        newlineText = sprintf('\r\n');
    else
        newlineText = sprintf('\n');
    end

    lines = regexp(txt, '\r\n|\n|\r', 'split');

    mwfLoadBlock = { ...
        '% B10 temporary-copy override: load MWF saved by B10.'
        '% The original B01 file is unchanged.'
        'B10_MWF_file = fullfile(fileparts(mfilename(''fullpath'')), ''B10_MWF_TEMP.mat'');'
        'if isfile(B10_MWF_file)'
        '    load(B10_MWF_file, ''MWF'');'
        'end'
        'fprintf(''MWF used inside temporary B01 = %g\n'', MWF);'};

    % Replace the normal commented line:
    %   % load('MWF.mat');
    % with the temporary B10 load block.
    loadLineIdx = [];
    for iLine = 1:numel(lines)
        if ~isempty(regexp(lines{iLine}, '^\s*%\s*load\(''MWF\.mat''\)\s*;?\s*$', 'once'))
            loadLineIdx = iLine;
            break;
        end
    end

    if ~isempty(loadLineIdx)
        linesNew = [lines(1:loadLineIdx-1), mwfLoadBlock(:)', lines(loadLineIdx+1:end)];
    else
        % Fallback: insert after MWF = 1;
        mwfAssignIdx = [];
        for iLine = 1:numel(lines)
            if ~isempty(regexp(lines{iLine}, '^\s*MWF\s*=\s*1\s*;\s*$', 'once'))
                mwfAssignIdx = iLine;
                break;
            end
        end

        if isempty(mwfAssignIdx)
            error(['Could not find the MWF block in B01. Expected:' newline ...
                   'MWF = 1;' newline ...
                   '% load(''MWF.mat'');']);
        end

        linesNew = [lines(1:mwfAssignIdx), mwfLoadBlock(:)', lines(mwfAssignIdx+1:end)];
    end

    fid = fopen(tempB01Path, 'w');
    if fid < 0
        error('Could not create temporary B01 file:\n%s', tempB01Path);
    end

    fprintf(fid, '%s', strjoin(linesNew, newlineText));
    fclose(fid);
end

function runData = collectCurrentRunData(iMWF, MWF, storeDetailedVariables)
%COLLECTCURRENTRUNDATA Collect B03/B05 outputs for one MWF value.

    runData = struct();
    runData.Index = iMWF;
    runData.MWF = MWF;
    runData.TimeStamp = char(datetime('now'));

    % Error outputs from B05.
    runData.Error.meanTotalError = readBaseVariable('meanTotalError');
    runData.Error.stdTotalError  = readBaseVariable('stdTotalError');
    runData.Error.maxTotalError  = readBaseVariable('maxTotalError');

    runData.Error.rightMarkersData = readBaseVariable('rightMarkersData');
    runData.Error.leftMarkersData  = readBaseVariable('leftMarkersData');
    runData.Error.independentData  = readBaseVariable('independentData');

    % Keep the main stance summary in a clear structure.
    joints = {'hip', 'knee', 'ankle'};
    angles = {'alpha', 'betha', 'gamma'};

    for iJoint = 1:numel(joints)
        jointName = joints{iJoint};

        for iAngle = 1:numel(angles)
            angleName = angles{iAngle};

            runData.StanceROM.(jointName).(angleName).Right.ROM = ...
                meanIgnoreNaN(readBaseVariable(sprintf('%s_R%s_ROM_ST', angleName, jointName)));
            runData.StanceROM.(jointName).(angleName).Left.ROM = ...
                meanIgnoreNaN(readBaseVariable(sprintf('%s_L%s_ROM_ST', angleName, jointName)));

            runData.StanceROM.(jointName).(angleName).Right.max = ...
                meanIgnoreNaN(readBaseVariable(sprintf('max_%s_R%s_ST', angleName, jointName)));
            runData.StanceROM.(jointName).(angleName).Left.max = ...
                meanIgnoreNaN(readBaseVariable(sprintf('max_%s_L%s_ST', angleName, jointName)));

            runData.StanceROM.(jointName).(angleName).Right.min = ...
                meanIgnoreNaN(readBaseVariable(sprintf('min_%s_R%s_ST', angleName, jointName)));
            runData.StanceROM.(jointName).(angleName).Left.min = ...
                meanIgnoreNaN(readBaseVariable(sprintf('min_%s_L%s_ST', angleName, jointName)));

            runData.StanceROM.(jointName).(angleName).Right.mean = ...
                meanIgnoreNaN(readBaseVariable(sprintf('mean_%s_R%s_ST', angleName, jointName)));
            runData.StanceROM.(jointName).(angleName).Left.mean = ...
                meanIgnoreNaN(readBaseVariable(sprintf('mean_%s_L%s_ST', angleName, jointName)));
        end
    end

    if storeDetailedVariables
        runData.Details = collectDetailedVariablesFromBase();
    else
        runData.Details = struct();
    end
end

function details = collectDetailedVariablesFromBase()
%COLLECTDETAILEDVARIABLESFROMBASE Store useful B01/B03/B05 outputs.
%
% This avoids saving many separate .mat files while still keeping enough
% information for later analysis.

    varNames = { ...
        'TrialName', 'category', 'rat_gender', 'rat_number', 'procedure_time', ...
        'Speed', 'fileName', 'fileName_Xray', 'EulerSeq', ...
        'time', 'dt', 'Hz', 'CS', 'CE', ...
        'TL_CycleEvents', 'TR_CycleEvents', ...
        'Time_Nor', 'Trtime_CycR_Nor', 'Trtime_CycL_Nor', ...
        'T_BoneLandMarkers', 'T_TransformedKeyPoints', 'T_Angles', ...
        'T_Scale', 'T_Pelvic', 'T_Leg', 'T_CycR', 'T_CycL', ...
        'T_segment_length', ...
        'alpha_Rhip', 'betha_Rhip', 'gamma_Rhip', ...
        'alpha_Rknee', 'betha_Rknee', 'gamma_Rknee', ...
        'alpha_Rankle', 'betha_Rankle', 'gamma_Rankle', ...
        'alpha_Lhip', 'betha_Lhip', 'gamma_Lhip', ...
        'alpha_Lknee', 'betha_Lknee', 'gamma_Lknee', ...
        'alpha_Lankle', 'betha_Lankle', 'gamma_Lankle', ...
        'alpha_Rhip_Cyc_Nor_matrix', 'betha_Rhip_Cyc_Nor_matrix', 'gamma_Rhip_Cyc_Nor_matrix', ...
        'alpha_Rknee_Cyc_Nor_matrix', 'betha_Rknee_Cyc_Nor_matrix', 'gamma_Rknee_Cyc_Nor_matrix', ...
        'alpha_Rankle_Cyc_Nor_matrix', 'betha_Rankle_Cyc_Nor_matrix', 'gamma_Rankle_Cyc_Nor_matrix', ...
        'alpha_Lhip_Cyc_Nor_matrix', 'betha_Lhip_Cyc_Nor_matrix', 'gamma_Lhip_Cyc_Nor_matrix', ...
        'alpha_Lknee_Cyc_Nor_matrix', 'betha_Lknee_Cyc_Nor_matrix', 'gamma_Lknee_Cyc_Nor_matrix', ...
        'alpha_Lankle_Cyc_Nor_matrix', 'betha_Lankle_Cyc_Nor_matrix', 'gamma_Lankle_Cyc_Nor_matrix', ...
        'meanTotalError', 'stdTotalError', 'maxTotalError', ...
        'rightMarkersData', 'leftMarkersData', 'independentData'};

    details = struct();

    for iVar = 1:numel(varNames)
        varName = varNames{iVar};

        if variableExistsInBase(varName)
            details.(varName) = evalin('base', varName);
        end
    end
end

function summaryMatrices = fillSummaryMatrices(summaryMatrices, iMWF, MWF, runData)
%FILLSUMMARYMATRICES Fill B11-style summary rows.

    meanTotalError = runData.Error.meanTotalError;
    maxTotalError  = runData.Error.maxTotalError;

    joints = {'hip', 'knee', 'ankle'};
    angles = {'alpha', 'betha', 'gamma'};

    for iJoint = 1:numel(joints)
        jointName = joints{iJoint};

        for iAngle = 1:numel(angles)
            angleName = angles{iAngle};

            summaryName = sprintf('%s_%s', angleName, jointName);

            S = runData.StanceROM.(jointName).(angleName);

            row = [MWF, ...
                   meanTotalError, ...
                   maxTotalError, ...
                   meanIgnoreNaN([S.Right.ROM,  S.Left.ROM]), ...
                   meanIgnoreNaN([S.Right.max,  S.Left.max]), ...
                   meanIgnoreNaN([S.Right.min,  S.Left.min]), ...
                   meanIgnoreNaN([S.Right.mean, S.Left.mean])];

            summaryMatrices.(summaryName)(iMWF, :) = row;
        end
    end
end

function MWFResults = updateResultTables(MWFResults, summaryMatrices, summaryHeaders)
%UPDATERESULTTABLES Put matrices into clear tables inside MWFResults.

    joints = {'hip', 'knee', 'ankle'};
    angles = {'alpha', 'betha', 'gamma'};

    for iJoint = 1:numel(joints)
        jointName = joints{iJoint};

        for iAngle = 1:numel(angles)
            angleName = angles{iAngle};
            summaryName = sprintf('%s_%s', angleName, jointName);

            T = array2table(summaryMatrices.(summaryName), ...
                'VariableNames', summaryHeaders);

            MWFResults.Tables.(jointName).(angleName) = T;

            % Compatibility with old B11 variable names, but inside one
            % structure instead of many .mat files.
            oldName = sprintf('MWF_TotalError_%s_%s_ROM_ST_table', ...
                              angleName, jointName);
            MWFResults.B11Compatible.(oldName) = T;
        end
    end

    MWFResults.B11Compatible.MWF_TotalError = ...
        MWFResults.Tables.hip.alpha(:, {'WeightFactor', 'meanTotalError'});
end

function assignB11CompatibleTablesToBase(MWFResults)
%ASSIGNB11COMPATIBLETABLESTOBASE Optional workspace convenience.
%
% This does not create files. It only makes the old B11-style table
% variables visible in the MATLAB base workspace after B10 finishes.

    names = fieldnames(MWFResults.B11Compatible);

    for iName = 1:numel(names)
        assignin('base', names{iName}, MWFResults.B11Compatible.(names{iName}));
    end
end

function computeStanceSummaryVariablesInBase()
%COMPUTESTANCESUMMARYVARIABLESINBASE Compute stance max/min/mean values.
%
% B03 computes normalized cycle curves. This helper computes extra
% stance-phase max/min/mean values needed for MWF sensitivity plotting.

    joints = {'hip', 'knee', 'ankle'};
    angles = {'alpha', 'betha', 'gamma'};
    sides  = {'R', 'L'};

    for iJoint = 1:numel(joints)
        jointName = joints{iJoint};

        for iAngle = 1:numel(angles)
            angleName = angles{iAngle};

            for iSide = 1:numel(sides)
                sideName = sides{iSide};

                if strcmp(sideName, 'R')
                    transitionVar = 'Trtime_CycR_Nor';
                else
                    transitionVar = 'Trtime_CycL_Nor';
                end

                cycleVar = sprintf('%s_%s%s_Cyc_Nor', angleName, sideName, jointName);

                if variableExistsInBase(cycleVar) && variableExistsInBase(transitionVar)

                    cycleData       = evalin('base', cycleVar);
                    transitionTimes = evalin('base', transitionVar);

                    [maxVals, minVals, meanVals] = ...
                        computeOneStanceSummary(cycleData, transitionTimes);

                    assignin('base', sprintf('max_%s_%s%s_ST',  angleName, sideName, jointName), maxVals);
                    assignin('base', sprintf('min_%s_%s%s_ST',  angleName, sideName, jointName), minVals);
                    assignin('base', sprintf('mean_%s_%s%s_ST', angleName, sideName, jointName), meanVals);

                else
                    warning('Could not compute stance summary for %s. Missing %s or %s.', ...
                            [angleName '_' sideName jointName], cycleVar, transitionVar);
                end
            end
        end
    end
end

function [maxVals, minVals, meanVals] = computeOneStanceSummary(cycleData, transitionTimes)
%COMPUTEONESTANCESUMMARY Compute stance max/min/mean for each cycle.

    nCycles = numel(cycleData);

    maxVals  = nan(nCycles, 1);
    minVals  = nan(nCycles, 1);
    meanVals = nan(nCycles, 1);

    for iCycle = 1:nCycles
        y = cycleData{iCycle};
        y = y(:);

        if isempty(y) || all(~isfinite(y))
            continue;
        end

        if numel(transitionTimes) >= iCycle && isfinite(transitionTimes(iCycle))
            stanceEndIdx = round(transitionTimes(iCycle)) + 1; % index 1 = 0%
        else
            stanceEndIdx = numel(y);
        end

        stanceEndIdx = max(1, min(numel(y), stanceEndIdx));
        stanceData   = y(1:stanceEndIdx);
        stanceData   = stanceData(isfinite(stanceData));

        if isempty(stanceData)
            continue;
        end

        maxVals(iCycle)  = max(stanceData);
        minVals(iCycle)  = min(stanceData);
        meanVals(iCycle) = mean(stanceData);
    end
end

function plotMWFSensitivityResults(MWFResults, fontSize, lineWidth, plotColor)
%PLOTMWFSENSITIVITYRESULTS Plot only the original B11-style summary figures.
%
% The older B11 script created three useful summary figures:
%
%   Figure 1: 3x3 grid
%       x-axis = mean marker registration error
%       y-axis = mean stance angle
%       vertical bar = stance min-to-max angle range
%       text label = MWF value
%
%   Figure 2: combined frontal/transverse score versus mean marker error
%
%   Figure 3: mean marker error versus MWF
%
% This version keeps only those plots to avoid creating too many figures.

    EulerSeq = getEulerSequenceFromResults(MWFResults);

    jointNames  = {'hip', 'knee', 'ankle'};
    jointTitles = {'Hip', 'Knee', 'Ankle'};
    angleNames  = {'alpha', 'betha', 'gamma'};

    % Figure 1: same main 3x3 figure style as the original B11 script.
    plotMeanAngleRangeGrid(MWFResults, jointNames, jointTitles, angleNames, ...
        'meanTotalError', 'Mean Error, mm', ...
        'MWF sensitivity: error versus stance angle range', ...
        EulerSeq, fontSize, lineWidth, plotColor);

    % Figure 2: same concept as the original B11 combined score plot.
    % The score range is computed from cycle-level data when available, so
    % the vertical bars are not misleading.
    plotCombinedScore(MWFResults, 'meanTotalError', 'Mean Error, mm', ...
        'MWF sensitivity: frontal/transverse angle score', ...
        fontSize, lineWidth, plotColor);

    % Figure 3: same simple MWF-versus-error plot as the original B11 script.
    plotMeanErrorVsMWFOnly(MWFResults, fontSize, lineWidth);
end

function EulerSeq = getEulerSequenceFromResults(MWFResults)
%GETEULERSEQUENCEFROMRESULTS Get Euler sequence saved from the last run.

    EulerSeq = 'ZYX';

    if ~isfield(MWFResults, 'Runs') || isempty(MWFResults.Runs)
        return;
    end

    for iRun = numel(MWFResults.Runs):-1:1
        thisRun = MWFResults.Runs{iRun};

        if isempty(thisRun)
            continue;
        end

        if isfield(thisRun, 'Details') && isfield(thisRun.Details, 'EulerSeq')
            EulerSeq = thisRun.Details.EulerSeq;
            return;
        end
    end
end

function plotMeanAngleRangeGrid(MWFResults, jointNames, jointTitles, angleNames, ...
                                xField, xLabelText, figureName, ...
                                EulerSeq, fontSize, lineWidth, plotColor)
%PLOTMEANANGLERANGEGRID Plot mean angle with min/max range in 3-by-3 grid.

    figure('Name', figureName, 'Color', 'w');

    for iAngle = 1:numel(angleNames)
        angleName = angleNames{iAngle};

        for iJoint = 1:numel(jointNames)
            jointName = jointNames{iJoint};

            subplot(3, 3, (iAngle - 1) * 3 + iJoint);
            T = MWFResults.Tables.(jointName).(angleName);

            x = T.(xField);
            y = T.mean;
            yMin = T.min;
            yMax = T.max;
            weightFactors = T.WeightFactor;

            hold on;
            hMean = plot(x, y, '-', 'Color', plotColor, 'LineWidth', lineWidth);
            scatter(x, y, 35, 'filled', 'MarkerFaceColor', plotColor, ...
                'MarkerEdgeColor', plotColor);

            hRange = gobjects(1);
            for i = 1:numel(x)
                hRange = plotVerticalRange(x(i), yMin(i), yMax(i), lineWidth);
                addMWFTextLabel(x(i), y(i), weightFactors(i), yMin, yMax);
            end

            if iAngle == 1
                title(jointTitles{iJoint}, 'FontSize', fontSize);
            end

            if iJoint == 1
                ylabel(getAngleLabel(angleName, jointName, EulerSeq), 'FontSize', fontSize);
            end

            if iAngle == numel(angleNames)
                xlabel(xLabelText, 'FontSize', fontSize);
            end

            box on;
            grid on;

            if iAngle == 1 && iJoint == 1
                legend([hMean, hRange], {'Mean stance angle', 'Min-max stance range'}, ...
                    'Location', 'best');
            end
        end
    end
end

function plotSingleFieldGrid(MWFResults, jointNames, jointTitles, angleNames, ...
                             xField, xLabelText, yField, yLabelText, ...
                             figureName, EulerSeq, fontSize, lineWidth, plotColor)
%PLOTSINGLEFIELDGRID Plot one table field in a 3-by-3 joint/angle grid.

    figure('Name', figureName, 'Color', 'w');

    for iAngle = 1:numel(angleNames)
        angleName = angleNames{iAngle};

        for iJoint = 1:numel(jointNames)
            jointName = jointNames{iJoint};

            subplot(3, 3, (iAngle - 1) * 3 + iJoint);
            T = MWFResults.Tables.(jointName).(angleName);

            x = T.(xField);
            y = T.(yField);
            weightFactors = T.WeightFactor;

            hold on;
            plot(x, y, '-', 'Color', plotColor, 'LineWidth', lineWidth);
            scatter(x, y, 35, 'filled', 'MarkerFaceColor', plotColor, ...
                'MarkerEdgeColor', plotColor);

            for i = 1:numel(x)
                addMWFTextLabel(x(i), y(i), weightFactors(i), y, y);
            end

            if iAngle == 1
                title(jointTitles{iJoint}, 'FontSize', fontSize);
            end

            if iJoint == 1
                ylabel(sprintf('%s\n%s', yLabelText, getAngleLabel(angleName, jointName, EulerSeq)), ...
                    'FontSize', fontSize);
            end

            if iAngle == numel(angleNames)
                xlabel(xLabelText, 'FontSize', fontSize);
            end

            box on;
            grid on;
        end
    end
end

function plotMaxMinMeanGrid(MWFResults, jointNames, jointTitles, angleNames, ...
                            EulerSeq, fontSize, lineWidth)
%PLOTMAXMINMEANGRID Plot stance max, min, and mean versus MWF.

    figure('Name', 'MWF sensitivity: MWF vs stance max/min/mean', 'Color', 'w');

    colorMean = [0.20 0.35 0.95];
    colorMax  = [0.85 0.25 0.25];
    colorMin  = [0.15 0.55 0.20];

    for iAngle = 1:numel(angleNames)
        angleName = angleNames{iAngle};

        for iJoint = 1:numel(jointNames)
            jointName = jointNames{iJoint};

            subplot(3, 3, (iAngle - 1) * 3 + iJoint);
            T = MWFResults.Tables.(jointName).(angleName);

            x = T.WeightFactor;

            hold on;
            hMean = plot(x, T.mean, '-o', 'Color', colorMean, 'LineWidth', lineWidth, ...
                'MarkerFaceColor', colorMean);
            hMax = plot(x, T.max, '-o', 'Color', colorMax, 'LineWidth', lineWidth, ...
                'MarkerFaceColor', colorMax);
            hMin = plot(x, T.min, '-o', 'Color', colorMin, 'LineWidth', lineWidth, ...
                'MarkerFaceColor', colorMin);

            if iAngle == 1
                title(jointTitles{iJoint}, 'FontSize', fontSize);
            end

            if iJoint == 1
                ylabel(getAngleLabel(angleName, jointName, EulerSeq), 'FontSize', fontSize);
            end

            if iAngle == numel(angleNames)
                xlabel('Marker Weighting Factor', 'FontSize', fontSize);
            end

            box on;
            grid on;

            if iAngle == 1 && iJoint == 1
                legend([hMean, hMax, hMin], {'Mean', 'Max', 'Min'}, 'Location', 'best');
            end
        end
    end
end

function plotCombinedScore(MWFResults, xField, xLabelText, figureName, ...
                           fontSize, lineWidth, plotColor)
%PLOTCOMBINEDSCORE Plot combined frontal/transverse score.
%
% The previous version computed:
%
%   score(mean values), score(min values), and score(max values)
%
% separately from already-averaged summary tables. That is not a valid
% min/max range for a combined magnitude, and it can place the mean score
% outside the plotted range.
%
% This version first tries to compute the score from the saved normalized
% cycle data in MWFResults.Runs{i}.Details. For each MWF value, it computes:
%
%   one score per side/cycle = sqrt(betha_hip^2 + betha_knee^2 + ...
%                                  gamma_hip^2 + gamma_knee^2 + ...)
%
% using stance-phase mean values. The plotted range is then the true
% min/max across those side/cycle scores.
%
% If detailed cycle data were not stored, the code falls back to plotting
% only the summary-table mean score and does not draw a misleading range.

    [x, y, yMin, yMax, weightFactors, hasCycleRange] = ...
        computeCombinedScoreForPlot(MWFResults, xField);

    figure('Name', figureName, 'Color', 'w');
    hold on;

    hScore = plot(x, y, '-o', ...
        'Color', plotColor, ...
        'LineWidth', lineWidth, ...
        'MarkerFaceColor', plotColor, ...
        'MarkerEdgeColor', plotColor);

    hRange = gobjects(1);

    if hasCycleRange
        for i = 1:numel(x)
            hRange = plotVerticalRange(x(i), yMin(i), yMax(i), lineWidth);
            addMWFTextLabel(x(i), y(i), weightFactors(i), yMin, yMax);
        end
    else
        for i = 1:numel(x)
            addMWFTextLabel(x(i), y(i), weightFactors(i), y, y);
        end
    end

    box on;
    grid on;
    xlabel(xLabelText, 'FontSize', fontSize);
    ylabel('Combined frontal/transverse angle score, deg', 'FontSize', fontSize);

    if hasCycleRange
        legend([hScore, hRange], {'Mean side-cycle score', 'Side-cycle min-max range'}, ...
            'Location', 'best');
    else
        legend(hScore, {'Summary-table mean score'}, 'Location', 'best');
    end
end

function [x, y, yMin, yMax, weightFactors, hasCycleRange] = ...
    computeCombinedScoreForPlot(MWFResults, xField)
%COMPUTECOMBINEDSCOREFORPLOT Compute combined frontal/transverse score.
%
% Preferred method:
%   Use detailed normalized cycle data saved in MWFResults.Runs. This gives
%   one score per side/cycle and therefore a valid min/max range.
%
% Fallback method:
%   Use the summary tables only. In this case, only the mean score is
%   plotted because a true min/max score cannot be reconstructed from the
%   separate min/max columns of each angle.

    Tref = MWFResults.Tables.hip.betha;
    x = Tref.(xField);
    weightFactors = Tref.WeightFactor;

    y    = nan(size(x));
    yMin = nan(size(x));
    yMax = nan(size(x));

    hasCycleRange = false;

    if isfield(MWFResults, 'Runs') && ~isempty(MWFResults.Runs)
        for iRun = 1:numel(MWFResults.Runs)
            thisRun = MWFResults.Runs{iRun};

            if isempty(thisRun) || ~isfield(thisRun, 'Details')
                continue;
            end

            scores = computeSideCycleCombinedScores(thisRun.Details);
            scores = scores(isfinite(scores));

            if isempty(scores)
                continue;
            end

            y(iRun)    = mean(scores);
            yMin(iRun) = min(scores);
            yMax(iRun) = max(scores);
            hasCycleRange = true;
        end
    end

    % Fallback for any run where detailed scores are unavailable.
    missingMean = ~isfinite(y);
    if any(missingMean)
        TbetaHip   = MWFResults.Tables.hip.betha;
        TbetaKnee  = MWFResults.Tables.knee.betha;
        TbetaAnkle = MWFResults.Tables.ankle.betha;

        TgammaHip   = MWFResults.Tables.hip.gamma;
        TgammaKnee  = MWFResults.Tables.knee.gamma;
        TgammaAnkle = MWFResults.Tables.ankle.gamma;

        yFallback = sqrt(sum([TbetaHip.mean.^2,   TbetaKnee.mean.^2,   TbetaAnkle.mean.^2, ...
                              TgammaHip.mean.^2,  TgammaKnee.mean.^2,  TgammaAnkle.mean.^2], 2));

        y(missingMean) = yFallback(missingMean);
    end

    % Only keep range bars for rows where the range is valid and contains
    % the mean score. This prevents visually incorrect bars.
    validRange = isfinite(yMin) & isfinite(yMax) & isfinite(y) & ...
                 (yMin <= y) & (y <= yMax);

    if ~all(validRange)
        yMin(~validRange) = NaN;
        yMax(~validRange) = NaN;
    end

    hasCycleRange = any(validRange);
end

function scores = computeSideCycleCombinedScores(details)
%COMPUTESIDECYCLECOMBINEDSCORES Compute one score for each side/cycle.
%
% For each right and left gait cycle, the function computes the stance mean
% of these six frontal/transverse components:
%
%   betha hip, betha knee, betha ankle,
%   gamma hip, gamma knee, gamma ankle
%
% Then it combines them as an Euclidean magnitude:
%
%   score = sqrt(sum(component_mean.^2))

    scores = [];

    rightScore = computeOneSideCombinedScores(details, 'R');
    leftScore  = computeOneSideCombinedScores(details, 'L');

    scores = [rightScore(:); leftScore(:)];
end

function scores = computeOneSideCombinedScores(details, sideChar)
%COMPUTEONESIDECOMBINEDSCORES Compute combined scores for one side.

    scores = [];

    switch upper(sideChar)
        case 'R'
            transitionName = 'Trtime_CycR_Nor';
            matrixNames = {'betha_Rhip_Cyc_Nor_matrix',   'betha_Rknee_Cyc_Nor_matrix',   'betha_Rankle_Cyc_Nor_matrix', ...
                           'gamma_Rhip_Cyc_Nor_matrix',   'gamma_Rknee_Cyc_Nor_matrix',   'gamma_Rankle_Cyc_Nor_matrix'};
        case 'L'
            transitionName = 'Trtime_CycL_Nor';
            matrixNames = {'betha_Lhip_Cyc_Nor_matrix',   'betha_Lknee_Cyc_Nor_matrix',   'betha_Lankle_Cyc_Nor_matrix', ...
                           'gamma_Lhip_Cyc_Nor_matrix',   'gamma_Lknee_Cyc_Nor_matrix',   'gamma_Lankle_Cyc_Nor_matrix'};
        otherwise
            return;
    end

    if ~isfield(details, transitionName)
        return;
    end

    transitionPercent = details.(transitionName);
    transitionPercent = transitionPercent(:)';

    % Make sure all needed matrices exist.
    for iName = 1:numel(matrixNames)
        if ~isfield(details, matrixNames{iName})
            return;
        end
    end

    firstMatrix = details.(matrixNames{1});
    if isempty(firstMatrix) || size(firstMatrix, 1) < 2
        return;
    end

    nCycles = size(firstMatrix, 2);
    nCycles = min(nCycles, numel(transitionPercent));

    if nCycles == 0
        return;
    end

    scores = nan(nCycles, 1);

    for iCycle = 1:nCycles
        components = nan(1, numel(matrixNames));

        % Rows in normalized cycle matrices usually represent 0:100%.
        % Therefore, transition percentage P corresponds approximately to
        % row P + 1.
        stanceEndRow = round(transitionPercent(iCycle)) + 1;

        for iName = 1:numel(matrixNames)
            Y = details.(matrixNames{iName});

            if size(Y, 2) < iCycle
                continue;
            end

            stanceEndRowUse = max(1, min(size(Y, 1), stanceEndRow));
            yStance = Y(1:stanceEndRowUse, iCycle);
            yStance = yStance(isfinite(yStance));

            if ~isempty(yStance)
                components(iName) = mean(yStance);
            end
        end

        components = components(isfinite(components));

        if numel(components) == numel(matrixNames)
            scores(iCycle) = sqrt(sum(components.^2));
        end
    end
end

function plotMeanErrorVsMWFOnly(MWFResults, fontSize, lineWidth)
%PLOTMEANERRORVSMWFONLY Plot mean marker error versus MWF.
%
% This matches the third figure in the original B11 plotting script.

    T = MWFResults.Tables.hip.alpha;

    figure('Name', 'MWF sensitivity: mean error versus MWF', 'Color', 'w');
    hold on;

    plot(T.WeightFactor, T.meanTotalError, '-o', ...
        'Color', [0 0 0], ...
        'LineWidth', lineWidth, ...
        'MarkerFaceColor', [0 0 0]);

    box on;
    grid on;
    xlabel('Weighting Factor', 'FontSize', fontSize);
    ylabel('Mean Error, mm', 'FontSize', fontSize);
end

function hRange = plotVerticalRange(x, yMin, yMax, lineWidth)
%PLOTVERTICALRANGE Plot range vertical bar with small T caps.

    hRange = gobjects(1);

    if ~isfinite(x) || ~isfinite(yMin) || ~isfinite(yMax)
        return;
    end

    capWidth = max(0.005 * max(abs(x), 1), 0.005);

    hRange = line([x, x], [yMin, yMax], 'Color', 'k', 'LineWidth', lineWidth);
    line([x - capWidth, x + capWidth], [yMin, yMin], 'Color', 'k', 'LineWidth', lineWidth);
    line([x - capWidth, x + capWidth], [yMax, yMax], 'Color', 'k', 'LineWidth', lineWidth);
end

function addMWFTextLabel(x, y, MWF, yMinAll, yMaxAll)
%ADDMWFTEXTLABEL Add MWF number beside a plotted point.

    if ~isfinite(x) || ~isfinite(y)
        return;
    end

    yRange = max(yMaxAll(:)) - min(yMinAll(:));

    if ~isfinite(yRange) || yRange == 0
        yRange = 1;
    end

    text(x, y - 0.04 * yRange, num2str(MWF), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontSize', 9);
end

function labelText = getAngleLabel(angleName, jointName, EulerSeq)
%GETANGLELABEL Return anatomical label for the angle.

    switch angleName
        case 'alpha'
            if strcmp(jointName, 'ankle')
                labelText = 'Plantarflexion(-)-Dorsiflexion(+), deg';
            else
                labelText = 'Extension(-)-Flexion(+), deg';
            end

        case 'betha'
            if strcmp(EulerSeq, 'XYZ')
                labelText = 'Adduction(-)-Abduction(+), deg';
            else
                labelText = 'Abduction(-)-Adduction(+), deg';
            end

        case 'gamma'
            if strcmp(EulerSeq, 'XYZ')
                labelText = 'External(-)-Internal(+) Rotation, deg';
            else
                labelText = 'Internal(-)-External(+) Rotation, deg';
            end

        otherwise
            labelText = 'Angle, deg';
    end
end

function value = readBaseVariable(varName)
%READBASEVARIABLE Read a variable from the base workspace.
%
% Missing variables return NaN.

    if variableExistsInBase(varName)
        value = evalin('base', varName);
    else
        warning('Variable "%s" was not found in the base workspace. Using NaN.', varName);
        value = NaN;
    end
end

function tf = variableExistsInBase(varName)
%VARIABLEEXISTSINBASE True if variable exists in base workspace.

    tf = evalin('base', sprintf('exist(''%s'', ''var'')', varName)) == 1;
end

function value = meanIgnoreNaN(x)
%MEANIGNORENAN Mean value while ignoring NaNs.

    x = x(:);
    x = x(isfinite(x));

    if isempty(x)
        value = NaN;
    else
        value = mean(x);
    end
end

function safePath = escapePathForEval(pathText)
%ESCAPEPATHFOREVAL Escape single quotes for eval/evalin command strings.

    safePath = strrep(pathText, '''', '''''');
end

function deleteFileIfItExists(filePath)
%DELETEFILEIFITEXISTS Delete a file only if it exists.

    if isfile(filePath)
        delete(filePath);
    end
end

function deleteOldMWFResultFiles()
%DELETEOLDMWFRESULTFILES Delete separate old-version MWF result files.

    oldFiles = dir('MWF_TotalError*.mat');

    for iFile = 1:numel(oldFiles)
        delete(oldFiles(iFile).name);
    end
end
