% -------------------------------------------------------------------------
% Constraint_Function.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Optional nonlinear constraints for optimization.
% -------------------------------------------------------------------------

function [c, ceq] = Constraint_Function(xopt)
%CONSTRAINT_FUNCTION Nonlinear constraints for landmark optimization.
%
%   [c, ceq] = Constraint_Function(xopt)
%
%   This optional constraint function runs the same bone-marker generation
%   and kinematic pipeline as the cost function, then limits the average hip
%   abduction/adduction angle. The optimizer uses:
%
%       c <= 0
%       ceq = []
%
%   Current constraint:
%       abs(mean hip beta angle) <= hipBetaLimit_deg
%
%   Required scripts/files:
%       Right_Left_Femur.m
%       Right_Left_Tibia.m
%       Right_Left_Foot.m
%       Right_left_Pelvis.m
%       B01_Registration_WithoutFlow_3DScale_WithMWF.m
%       B03_Kinematics_3D_And_Cycles_R1_MLaxis.m
%
%   Note:
%       This constraint is computationally expensive because it reruns the
%       full registration and kinematics pipeline.

    %% Generate optimized bone landmarks and transformed kinematics
    Right_Left_Femur;
    Right_Left_Tibia;
    Right_Left_Foot;
    Right_left_Pelvis;

    B01_Registration_WithoutFlow_3DScale_WithMWF;

    % Do not create B03 diagnostic figures during optimization.
    % This greatly reduces runtime and prevents figures such as 103 from
    % being generated at every objective-function evaluation.
    plotB03Figures = false;
    try
        if evalin('base', 'exist(''O01_ShowB03FiguresDuringOptimization'', ''var'')')
            plotB03Figures = evalin('base', 'O01_ShowB03FiguresDuringOptimization');
        end
    catch
        plotB03Figures = false;
    end

    B03_Kinematics_3D_And_Cycles_R1_MLaxis;

    %% User parameter
    % Important:
    %   B01 starts with clear; clc. When B01 is called inside this function,
    %   that clear command removes local variables that were defined before
    %   B01. Therefore, constraint parameters must be defined after B01/B03.
    hipBetaLimit_deg = 10;     % Maximum allowed mean hip beta angle

    %% Inequality constraints: c <= 0
    mean_betha_Rhip = mean(betha_Rhip_Cyc_Nor_matrix, 2, 'omitnan');
    mean_betha_Lhip = mean(betha_Lhip_Cyc_Nor_matrix, 2, 'omitnan');

    c_right = abs(mean_betha_Rhip) - hipBetaLimit_deg;
    c_left  = abs(mean_betha_Lhip) - hipBetaLimit_deg;

    c = [c_right; c_left];

    %% No equality constraints
    ceq = [];

end
