% -------------------------------------------------------------------------
% Cost_Function.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Objective function for optimized anatomical landmark placement.
% -------------------------------------------------------------------------

function Distance = Cost_Function(xopt)
%COST_FUNCTION Objective function for optimized bone-marker placement.
%
%   Distance = Cost_Function(xopt)
%
%   xopt is a 42-by-1 vector. Each anatomical point is described by three
%   spherical parameters:
%
%       [radius, theta, phi]
%
%   The scripts Right_Left_Femur, Right_Left_Tibia, Right_Left_Foot, and
%   Right_left_Pelvis use xopt to update the virtual bone landmarks. Then
%   B01 registers the bones to the marker data, and B03 computes joint
%   kinematics. The cost is the sum of:
%
%       1) mean marker-registration errors, in cm
%       2) right-left kinematic asymmetry terms, converted from deg to rad
%
%   Lower Distance means better agreement between labeled markers, STL
%   landmarks, and right-left joint-angle symmetry.

    %% Generate optimized bone landmarks and transformed kinematics
    Right_Left_Femur;
    Right_Left_Tibia;
    Right_Left_Foot;
    Right_left_Pelvis;

    B01_Registration_WithoutFlow_3DScale_WithMWF;

    % Do not create B03 diagnostic figures during optimization.
    % This greatly reduces runtime and prevents figures such as 103 from
    % being generated at every objective-function evaluation.
    plotB03Figures = false;
    try
        if evalin('base', 'exist(''O01_ShowB03FiguresDuringOptimization'', ''var'')')
            plotB03Figures = evalin('base', 'O01_ShowB03FiguresDuringOptimization');
        end
    catch
        plotB03Figures = false;
    end

    B03_Kinematics_3D_And_Cycles_R1_MLaxis;

    %% Objective weights
    % Important:
    %   B01 starts with clear; clc. When B01 is called inside this function,
    %   that clear command removes local variables that were defined before
    %   B01. Therefore, objective weights must be defined after B01/B03.
    markerErrorWeight   = 1;   % Weight for marker registration error
    symmetryErrorWeight = 0;   % Weight for right-left kinematic asymmetry

    %% Marker registration error, in cm
    markerError_cm = ...
        meanPointError(RFT_transformed,  F_FRT_S) + ...
        meanPointError(LFT_transformed,  F_FLT_S) + ...
        meanPointError(RFE_transformed,  F_FRC_S) + ...
        meanPointError(LFE_transformed,  F_FLC_S) + ...
        meanPointError(RTP_transformed,  F_TRP_S) + ...
        meanPointError(LTP_transformed,  F_TLP_S) + ...
        meanPointError(RTH_transformed,  F_TRH_S) + ...
        meanPointError(LTH_transformed,  F_TLH_S) + ...
        meanPointError(RTD_transformed,  F_TRD_S) + ...
        meanPointError(LTD_transformed,  F_TLD_S) + ...
        meanPointError(RCal_transformed, F_CR_S)  + ...
        meanPointError(LCal_transformed, F_CL_S)  + ...
        meanPointError(RMet_transformed, F_MR_S)  + ...
        meanPointError(LMet_transformed, F_ML_S);

    %% Right-left kinematic asymmetry, converted from degrees to radians
    symmetryError_rad = ...
        meanCycleDifference(alpha_Rhip_Cyc_Nor_matrix,   alpha_Lhip_Cyc_Nor_matrix)   + ...
        meanCycleDifference(alpha_Rknee_Cyc_Nor_matrix,  alpha_Lknee_Cyc_Nor_matrix)  + ...
        meanCycleDifference(alpha_Rankle_Cyc_Nor_matrix, alpha_Lankle_Cyc_Nor_matrix) + ...
        meanCycleDifference(betha_Rhip_Cyc_Nor_matrix,   betha_Lhip_Cyc_Nor_matrix)   + ...
        meanCycleDifference(betha_Rknee_Cyc_Nor_matrix,  betha_Lknee_Cyc_Nor_matrix)  + ...
        meanCycleDifference(betha_Rankle_Cyc_Nor_matrix, betha_Lankle_Cyc_Nor_matrix) + ...
        meanCycleDifference(gamma_Rhip_Cyc_Nor_matrix,   gamma_Lhip_Cyc_Nor_matrix)   + ...
        meanCycleDifference(gamma_Rknee_Cyc_Nor_matrix,  gamma_Lknee_Cyc_Nor_matrix)  + ...
        meanCycleDifference(gamma_Rankle_Cyc_Nor_matrix, gamma_Lankle_Cyc_Nor_matrix);

    %% Final objective value
    Distance = markerErrorWeight   * markerError_cm + ...
               symmetryErrorWeight * symmetryError_rad;

    if ~isfinite(Distance)
        Distance = realmax('double');
    end

end

%% ------------------------------------------------------------------------
function err = meanPointError(A, B)
% Mean Euclidean distance between two Nx3 trajectories.

    err = mean(sqrt(sum((A - B).^2, 2)), 'omitnan');
end

%% ------------------------------------------------------------------------
function err_rad = meanCycleDifference(rightCycles, leftCycles)
% Mean absolute difference between right and left normalized cycle means.

    rightMean = mean(rightCycles, 2, 'omitnan');
    leftMean  = mean(leftCycles,  2, 'omitnan');

    err_deg = mean(abs(rightMean - leftMean), 'omitnan');
    err_rad = err_deg * pi / 180;
end
