% -------------------------------------------------------------------------
% fit_and_plot_sphere.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Fits a sphere to manually selected femoral-head surface points.
% -------------------------------------------------------------------------

function [center, radius, fitError] = fit_and_plot_sphere(points, doPlot)
%FIT_AND_PLOT_SPHERE Fit a sphere to 3D points.
%
%   [center, radius] = fit_and_plot_sphere(points)
%   [center, radius, fitError] = fit_and_plot_sphere(points, doPlot)
%
%   points : Nx3 matrix of points on/near a spherical surface.
%   doPlot : true/false. If true, plots the fitted sphere.
%
%   The function uses lsqnonlin when available. If the Optimization Toolbox
%   is not available, it falls back to fminsearch.

    if nargin < 2 || isempty(doPlot)
        doPlot = false;
    end

    validateattributes(points, {'numeric'}, {'2d', 'ncols', 3, 'finite'});

    if size(points, 1) < 4
        error('At least four 3D points are required to fit a sphere.');
    end

    %% Initial guess
    center0 = mean(points, 1);
    radius0 = mean(vecnorm(points - center0, 2, 2));
    params0 = [center0, radius0];

    %% Fit sphere
    if exist('lsqnonlin', 'file') == 2
        options = optimset('Display', 'off');
        params = lsqnonlin(@sphereResidual, params0, [], [], options, points);
    else
        objective = @(p) sum(sphereResidual(p, points).^2);
        params = fminsearch(objective, params0);
    end

    center = params(1:3);
    radius = abs(params(4));
    residual = sphereResidual([center, radius], points);
    fitError = sqrt(mean(residual.^2));

    %% Optional visualization
    if doPlot
        figure;
        hold on;
        axis equal;
        grid on;
        box on;

        scatter3(points(:,1), points(:,2), points(:,3), 35, 'filled');

        [xs, ys, zs] = sphere(60);
        surf(xs * radius + center(1), ...
             ys * radius + center(2), ...
             zs * radius + center(3), ...
             'FaceColor', 'none', 'EdgeColor', [0.2 0.6 0.2]);

        xlabel('X'); ylabel('Y'); zlabel('Z');
        title(sprintf('Fitted sphere | radius = %.4f | RMS error = %.4f', radius, fitError));
    end
end

%% ------------------------------------------------------------------------
function err = sphereResidual(params, points)
% Difference between point-to-center distance and fitted radius.

    center = params(1:3);
    radius = abs(params(4));

    distances = vecnorm(points - center, 2, 2);
    err = distances - radius;
end
