% -------------------------------------------------------------------------
% IPGenerateCode.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   fmincon wrapper for landmark optimization.
% -------------------------------------------------------------------------

function [x, fval, exitflag, output, lambda, grad, hessian] = IPGenerateCode( ...
    x0, lb, ub, MaxFunctionEvaluations_Data, MaxIterations_Data, ...
    OptimalityTolerance_Data, StepTolerance_Data, ObjectiveLimit_Data, ...
    ConstraintTolerance_Data, useNonlinearConstraints, useParallel, showPlots)
%IPGENERATECODE Run fmincon for anatomical-landmark optimization.
%
%   This is a cleaned wrapper around fmincon. The original function name is
%   preserved for compatibility with older scripts.

    if nargin < 10 || isempty(useNonlinearConstraints)
        useNonlinearConstraints = false;
    end

    if nargin < 11 || isempty(useParallel)
        useParallel = true;
    end

    if nargin < 12 || isempty(showPlots)
        showPlots = true;
    end

    %% Optimizer options
    options = optimoptions('fmincon', ...
        'Display', 'off', ...
        'MaxFunctionEvaluations', MaxFunctionEvaluations_Data, ...
        'MaxIterations', MaxIterations_Data, ...
        'OptimalityTolerance', OptimalityTolerance_Data, ...
        'FunctionTolerance', OptimalityTolerance_Data, ...
        'StepTolerance', StepTolerance_Data, ...
        'ObjectiveLimit', ObjectiveLimit_Data, ...
        'ConstraintTolerance', ConstraintTolerance_Data, ...
        'UseParallel', useParallel);

    if showPlots
        options = optimoptions(options, 'PlotFcn', ...
            {@optimplotx, @optimplotfval, @optimplotconstrviolation});
    end

    %% Optional nonlinear constraints
    if useNonlinearConstraints
        nonlcon = @Constraint_Function;
    else
        nonlcon = [];
    end

    %% Run optimization
    [x, fval, exitflag, output, lambda, grad, hessian] = fmincon( ...
        @Cost_Function, x0, [], [], [], [], lb, ub, nonlcon, options);
end
