% -------------------------------------------------------------------------
% O01_Optimization_Pattern.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Runs pattern-search optimization for anatomical landmark placement.
%   The MATLAB patternsearch plot window already has Stop and Pause buttons.
%   If the user presses Stop, the optimizer stops cleanly and this script
%   saves the best result returned by patternsearch.
%
%   Only one optimization result file is written:
%
%       O01_OptimizationResults.mat
%
%   This file contains xopt, x0, bounds, optimizer output, progress, and
%   history inside one structure named OptimizationResults.
% -------------------------------------------------------------------------

clear; clc;

%% -------------------------- User parameters -----------------------------
numOptimizationPasses = 2;       % Number of repeated pattern-search runs
maxIterationsPerPass  = 25;      % Pattern-search iterations per pass
resumeFromSavedResult = true;    % true = continue from O01_OptimizationResults.mat if it exists
showOptimizerPlots    = true;    % Shows MATLAB patternsearch figure with Stop/Pause buttons
useNonlinearConstraints = false; % true uses Constraint_Function.m

% During optimization, B03 figures are usually unnecessary and slow.
% Keep this false to prevent diagnostic figures from being created at every
% objective-function evaluation.
showB03FiguresDuringOptimization = false;

% Single output file used by O02_Results.m
optimizationResultsFile = 'O01_OptimizationResults.mat';

% Old separate result files from earlier versions are no longer used.
% Set true only if you want this script to delete old copies at startup.
deleteOldSeparateResultFiles = false;
oldSeparateResultFiles = {'x0.mat', 'OptimizationHistory.mat', 'O01_OptimizationProgress.mat'};

useParallelPool = false;         % true starts a local parallel pool
numWorkers      = 16;            % Used only when useParallelPool = true
randomSeed      = [];            % Example: 1 for repeatable random x0

%% -------------------------- Setup ---------------------------------------
assignin('base', 'O01_ShowB03FiguresDuringOptimization', showB03FiguresDuringOptimization);

if deleteOldSeparateResultFiles
    for fileIdx = 1:numel(oldSeparateResultFiles)
        if isfile(oldSeparateResultFiles{fileIdx})
            delete(oldSeparateResultFiles{fileIdx});
        end
    end
end

%% -------------------------- Optional parallel pool -----------------------
if useParallelPool
    poolObj = gcp('nocreate');
    if isempty(poolObj)
        parpool('local', numWorkers);
    end
end

%% -------------------------- Bounds and initial guess ---------------------
if ~isempty(randomSeed)
    rng(randomSeed);
end

cof  = 1;
cof2 = 1.3;

[lb, ub] = createOptimizationBounds(cof, cof2);
x0 = createInitialGuess();

% These files are still written because the Right_Left_* scripts read
% ub.mat directly when generating optimized landmarks. They are model input
% files, not optimization result files.
save('lb.mat', 'lb');
save('ub.mat', 'ub');

if resumeFromSavedResult && isfile(optimizationResultsFile)
    loaded = load(optimizationResultsFile, 'OptimizationResults');
    if isfield(loaded, 'OptimizationResults')
        previous = loaded.OptimizationResults;
        if isfield(previous, 'xopt') && ~isempty(previous.xopt)
            x0 = previous.xopt;
            fprintf('Loaded previous xopt from %s.\n', optimizationResultsFile);
        elseif isfield(previous, 'x0') && ~isempty(previous.x0)
            x0 = previous.x0;
            fprintf('Loaded previous x0 from %s.\n', optimizationResultsFile);
        elseif isfield(previous, 'Progress') && isfield(previous.Progress, 'x') && ~isempty(previous.Progress.x)
            x0 = previous.Progress.x;
            fprintf('Loaded previous progress x from %s.\n', optimizationResultsFile);
        end
    end
end

%% -------------------------- Pattern-search loop --------------------------
OptimizationHistory = struct([]);

x = x0;
fval = NaN;
exitflag = NaN;
output = struct();
completedPasses = 0;
stoppedByUser = false;

% Save an initial one-file result so partial information exists even before
% the first optimizer iteration finishes.
saveOptimizationResults(optimizationResultsFile, x, fval, exitflag, output, ...
    OptimizationHistory, completedPasses, stoppedByUser, lb, ub, false, []);

try
    for passIdx = 1:numOptimizationPasses

        fprintf('\n============================================================\n');
        fprintf('Pattern-search pass %d of %d\n', passIdx, numOptimizationPasses);
        fprintf('Use the built-in Stop button in the Pattern Search figure to stop and save.\n');
        fprintf('============================================================\n');

        [x, fval, exitflag, output] = PatternSearch( ...
            x0, lb, ub, maxIterationsPerPass, ...
            useNonlinearConstraints, showOptimizerPlots, optimizationResultsFile);

        completedPasses = passIdx;
        x0 = x;
        xopt = x; %#ok<NASGU>

        OptimizationHistory(passIdx).x = x;
        OptimizationHistory(passIdx).fval = fval;
        OptimizationHistory(passIdx).exitflag = exitflag;
        OptimizationHistory(passIdx).output = output;
        OptimizationHistory(passIdx).stoppedByUser = optimizerWasStopped(exitflag, output);

        stoppedByUser = optimizerWasStopped(exitflag, output);

        saveOptimizationResults(optimizationResultsFile, x, fval, exitflag, output, ...
            OptimizationHistory, completedPasses, stoppedByUser, lb, ub, false, []);

        fprintf('Pass %d done. fval = %.6f\n', passIdx, fval);

        if stoppedByUser
            fprintf('\nOptimization stopped by user. Results saved to %s.\n', optimizationResultsFile);
            break;
        end
    end

catch ME
    % Save the best information available before rethrowing the error.
    [x, fval] = loadProgressIfUseful(optimizationResultsFile, x, fval);
    x0 = x; %#ok<NASGU>
    xopt = x; %#ok<NASGU>

    saveOptimizationResults(optimizationResultsFile, x, fval, exitflag, output, ...
        OptimizationHistory, completedPasses, false, lb, ub, true, ME);

    fprintf('\nOptimization interrupted or failed. Partial results saved to %s.\n', optimizationResultsFile);
    rethrow(ME);
end

fprintf('\nOptimization finished. Results saved to %s.\n', optimizationResultsFile);
fprintf('O02_Results.m can read %s automatically.\n', optimizationResultsFile);

%% -------------------------- Helper functions ----------------------------
function [lb, ub] = createOptimizationBounds(cof, cof2)
% Bound vector for the 42 optimization parameters.
%
% Each anatomical point has [R, theta, phi]. R controls how far the point is
% allowed to move from a predefined center. theta and phi are spherical
% angles.

    ub = [cof*0.2;  pi; 2*pi; ...   % RFT
          cof2*0.25; pi; 2*pi; ...  % RFE
          cof*0.2;  pi; 2*pi; ...   % LFT
          cof2*0.25; pi; 2*pi; ...  % LFE
          cof2*0.2;  pi; 2*pi; ...  % RTP
          cof2*0.09; pi; 2*pi; ...  % RTH
          cof2*0.1;  pi; 2*pi; ...  % RTD
          cof2*0.2;  pi; 2*pi; ...  % LTP
          cof2*0.09; pi; 2*pi; ...  % LTH
          cof2*0.1;  pi; 2*pi; ...  % LTD
          cof*0.13; pi; 2*pi; ...   % RCal
          cof*0.08; pi; 2*pi; ...   % RMet
          cof*0.13; pi; 2*pi; ...   % LCal
          cof*0.08; pi; 2*pi];      % LMet

    lb = -ub;
end

function x0 = createInitialGuess()
% Initial guess for all 42 parameters.

    x0 = [0.2;  rand(1)*pi; rand(1)*2*pi; ...
          0.25; rand(1)*pi; rand(1)*2*pi; ...
          0.2;  rand(1)*pi; rand(1)*2*pi; ...
          0.25; rand(1)*pi; rand(1)*2*pi; ...
          0.2;  rand(1)*pi; rand(1)*2*pi; ...
          0.09; rand(1)*pi; rand(1)*2*pi; ...
          0.1;  rand(1)*pi; rand(1)*2*pi; ...
          0.2;  rand(1)*pi; rand(1)*2*pi; ...
          0.09; rand(1)*pi; rand(1)*2*pi; ...
          0.1;  rand(1)*pi; rand(1)*2*pi; ...
          0.13; rand(1)*pi; rand(1)*2*pi; ...
          0.08; rand(1)*pi; rand(1)*2*pi; ...
          0.13; rand(1)*pi; rand(1)*2*pi; ...
          0.08; rand(1)*pi; rand(1)*2*pi];
end

function tf = optimizerWasStopped(exitflag, output)
% True when patternsearch was stopped by the user from the plot window.

    tf = false;

    if isnumeric(exitflag) && exitflag == -1
        tf = true;
        return;
    end

    try
        if isfield(output, 'message') && contains(lower(string(output.message)), 'stop')
            tf = true;
        end
    catch
    end
end

function [x, fval] = loadProgressIfUseful(resultsFile, x, fval)
% Use the last saved patternsearch progress if it has a valid x vector.

    if ~isfile(resultsFile)
        return;
    end

    try
        loaded = load(resultsFile, 'OptimizationResults');
        if isfield(loaded, 'OptimizationResults') && ...
           isfield(loaded.OptimizationResults, 'Progress') && ...
           isfield(loaded.OptimizationResults.Progress, 'x') && ...
           ~isempty(loaded.OptimizationResults.Progress.x)

            x = loaded.OptimizationResults.Progress.x;

            if isfield(loaded.OptimizationResults.Progress, 'fval')
                fval = loaded.OptimizationResults.Progress.fval;
            end
        end
    catch
    end
end

function saveOptimizationResults(resultsFile, x, fval, exitflag, output, ...
                                 OptimizationHistory, completedPasses, stoppedByUser, ...
                                 lb, ub, interrupted, ME)
% Save all optimization outputs in one MAT file.

    OptimizationResults = struct();

    % Preserve last progress saved by PatternSearch.m if it exists.
    if isfile(resultsFile)
        try
            old = load(resultsFile, 'OptimizationResults');
            if isfield(old, 'OptimizationResults') && isfield(old.OptimizationResults, 'Progress')
                OptimizationResults.Progress = old.OptimizationResults.Progress;
            end
        catch
        end
    end

    OptimizationResults.xopt = x;
    OptimizationResults.x0 = x;
    OptimizationResults.fval = fval;
    OptimizationResults.exitflag = exitflag;
    OptimizationResults.output = output;
    OptimizationResults.history = OptimizationHistory;
    OptimizationResults.completedPasses = completedPasses;
    OptimizationResults.stoppedByUser = stoppedByUser;
    OptimizationResults.interruptedOrFailed = interrupted;
    OptimizationResults.lb = lb;
    OptimizationResults.ub = ub;
    OptimizationResults.savedAt = datetime('now');

    if nargin >= 12 && ~isempty(ME)
        OptimizationResults.errorMessage = ME.message;
        OptimizationResults.errorReport = getReport(ME, 'extended', 'hyperlinks', 'off');
    end

    save(resultsFile, 'OptimizationResults', '-v7.3');
end
