% -------------------------------------------------------------------------
% PatternSearch.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Simple wrapper around MATLAB patternsearch for anatomical landmark
%   optimization. The MATLAB patternsearch plot window already has Stop and
%   Pause buttons; when Stop is pressed, O01 saves the returned result.
% -------------------------------------------------------------------------

function [x, fval, exitflag, output] = PatternSearch(x0, lb, ub, maxIterations, useNonlinearConstraints, showPlots, resultsFile)
%PATTERNSEARCH Run pattern search for anatomical-landmark optimization.
%
%   [x, fval, exitflag, output] = PatternSearch(x0, lb, ub, maxIterations)
%
%   Optional inputs:
%       useNonlinearConstraints : true/false, default = false
%       showPlots               : true/false, default = true
%       resultsFile             : one MAT-file used to save progress/results
%
%   Notes:
%       If showPlots = true, MATLAB opens the standard patternsearch plot
%       window. Use its built-in Stop button to stop the run. O01 will save
%       the latest optimizer result automatically after patternsearch returns.

    if nargin < 5 || isempty(useNonlinearConstraints)
        useNonlinearConstraints = false;
    end

    if nargin < 6 || isempty(showPlots)
        showPlots = true;
    end

    if nargin < 7 || isempty(resultsFile)
        resultsFile = 'O01_OptimizationResults.mat';
    end

    %% Optimizer options
    options = optimoptions('patternsearch', ...
        'Display', 'off', ...
        'MaxIterations', maxIterations, ...
        'OutputFcn', @(optimValues, options, state) savePatternSearchProgress(optimValues, options, state, resultsFile));

    if showPlots
        % The patternsearch figure includes built-in Stop and Pause buttons.
        options = optimoptions(options, 'PlotFcn', {@psplotbestf, @psplotbestx});
    end

    %% Optional nonlinear constraints
    if useNonlinearConstraints
        nonlcon = @Constraint_Function;
    else
        nonlcon = [];
    end

    %% Run optimization
    [x, fval, exitflag, output] = patternsearch( ...
        @Cost_Function, x0, [], [], [], [], lb, ub, nonlcon, options);
end

%% ------------------------------------------------------------------------
function [stop, options, optchanged] = savePatternSearchProgress(optimValues, options, state, resultsFile)
%SAVEPATTERNSEARCHPROGRESS Save current optimizer state in the single result file.
%
% This function does not stop the optimizer. It only updates the Progress
% field inside O01_OptimizationResults.mat so O01 has useful information if
% the optimization is interrupted.

    stop = false;
    optchanged = false;

    try
        Progress = struct();
        Progress.state = state;
        Progress.optimValues = optimValues;
        Progress.savedAt = datetime('now');

        if isfield(optimValues, 'x')
            Progress.x = optimValues.x;
        else
            Progress.x = [];
        end

        if isfield(optimValues, 'fval')
            Progress.fval = optimValues.fval;
        else
            Progress.fval = NaN;
        end

        if isfield(optimValues, 'iteration')
            Progress.iteration = optimValues.iteration;
        else
            Progress.iteration = NaN;
        end

        OptimizationResults = struct();

        if isfile(resultsFile)
            try
                loaded = load(resultsFile, 'OptimizationResults');
                if isfield(loaded, 'OptimizationResults')
                    OptimizationResults = loaded.OptimizationResults;
                end
            catch
                OptimizationResults = struct();
            end
        end

        OptimizationResults.Progress = Progress;
        OptimizationResults.savedAt = datetime('now');

        save(resultsFile, 'OptimizationResults', '-v7.3');
    catch
        % Do not interrupt the optimizer just because progress saving failed.
    end
end
