% -------------------------------------------------------------------------
% Right_Left_Foot.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Generates optimized foot landmarks and foot STL MAT files.
% -------------------------------------------------------------------------

% This script generates right/left foot bone landmarks and STL MAT files.
% It expects xopt in the workspace, ub.mat in the current folder, and
% RTibiaBoneMarks.mat from Right_Left_Tibia.m.

%% -------------------------- Checks and input files -----------------------
assert(exist('xopt', 'var') == 1, 'Right_Left_Foot requires xopt in the workspace.');
assert(numel(xopt) >= 42, 'xopt must contain 42 values for foot parameters.');

if exist('ub', 'var') ~= 1
    load('ub.mat', 'ub');
end

load('RTibiaBoneMarks.mat', 'RTibiaBoneMarks');

stlData = stlread('foot_r_pose.stl');
baseRightVertices = stlData.Points * 100;   % Convert m to cm
baseFaces = stlData.ConnectivityList;

%% -------------------------- Optimization parameters ---------------------
R_RCal = xopt(31);  Theta_RCal = xopt(32);  Phi_RCal = xopt(33);
R_RMet = xopt(34);  Theta_RMet = xopt(35);  Phi_RMet = xopt(36);
R_LCal = xopt(37);  Theta_LCal = xopt(38);  Phi_LCal = xopt(39);
R_LMet = xopt(40);  Theta_LMet = xopt(41);  Phi_LMet = xopt(42);

%% -------------------------- Landmark centers ----------------------------
RCal_Cen = ([0.426374608259269  -4.16480406993333  1.65163580384981] + ...
            [0.413828214656927  -4.16446468828930  1.40112927767940]) / 2;
RMet_Cen = ([2.55366787314415   -4.73832115530968  1.11845778301358] + ...
            [2.59705893695354   -4.72958236932755  1.29822986200452]) / 2;

%% -------------------------- Right foot landmarks ------------------------
RCal = sphericalPoint(R_RCal, Theta_RCal, Phi_RCal, RCal_Cen);
RMet = sphericalPoint(R_RMet, Theta_RMet, Phi_RMet, RMet_Cen);

RFAnk = [0.816234853118658  -4.01129089295864  1.40458317473531];
RFAM  = RTibiaBoneMarks.RTMAM;
RFAL  = RTibiaBoneMarks.RTMAL;

[right_vertices, right_F] = appendMarkerVertices(baseRightVertices, baseFaces, ...
    [RCal; RMet; RFAM; RFAL]);

RFootBoneMarks = struct('RCal', RCal, 'RMet', RMet, 'RFAnk', RFAnk, ...
                        'RFAM', RFAM, 'RFAL', RFAL, ...
                        'RRFAM', RFAM, 'RRFAL', RFAL);
RFoot_STL = struct('Points', right_vertices, 'ConnectivityList', right_F);

save('RFootBoneMarks.mat', 'RFootBoneMarks');
save('RFoot_STL.mat', 'RFoot_STL');

%% -------------------------- Left foot landmarks -------------------------
LCal_Cen = mirrorZ(RCal_Cen);
LMet_Cen = mirrorZ(RMet_Cen);

LCal = sphericalPoint(R_LCal, Theta_LCal, Phi_LCal, LCal_Cen);
LMet = sphericalPoint(R_LMet, Theta_LMet, Phi_LMet, LMet_Cen);

LFAnk = mirrorZ(RFAnk);
LTFCM = mirrorZ(RFAM);
LTFCL = mirrorZ(RFAL);

baseLeftVertices = mirrorZ(baseRightVertices);
[left_vertices, left_F] = appendMarkerVertices(baseLeftVertices, baseFaces, ...
    [LCal; LMet; LTFCM; LTFCL]);

LFootBoneMarks = struct('LCal', LCal, 'LMet', LMet, 'LFAnk', LFAnk, ...
                        'LTFCM', LTFCM, 'LTFCL', LTFCL, ...
                        'LTMAM', LTFCM, 'LTMAL', LTFCL);
LFoot_STL = struct('Points', left_vertices, 'ConnectivityList', left_F);

save('LFootBoneMarks.mat', 'LFootBoneMarks');
save('LFoot_STL.mat', 'LFoot_STL');

%% -------------------------- Helper functions ----------------------------
function point = sphericalPoint(radius, theta, phi, center)
    point = [radius * sin(theta) * cos(phi) + center(1), ...
             radius * sin(theta) * sin(phi) + center(2), ...
             radius * cos(theta)            + center(3)];
end

function mirrored = mirrorZ(points)
    mirrored = points;
    mirrored(:, 3) = -mirrored(:, 3);
end

function [verticesOut, facesOut] = appendMarkerVertices(verticesIn, facesIn, markers)
    n0 = size(verticesIn, 1);
    nMarkers = size(markers, 1);
    extraFaces = [(n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)'];

    verticesOut = [verticesIn; markers];
    facesOut = [facesIn; extraFaces];
end
