% -------------------------------------------------------------------------
% Right_Left_Femur.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Generates optimized femur landmarks and femur STL MAT files.
% -------------------------------------------------------------------------

% This script generates right/left femur bone landmarks and STL MAT files.
% It expects xopt in the workspace and ub.mat in the current folder.

%% -------------------------- Checks and input files -----------------------
assert(exist('xopt', 'var') == 1, 'Right_Left_Femur requires xopt in the workspace.');
assert(numel(xopt) >= 12, 'xopt must contain at least 12 values for femur parameters.');

if exist('ub', 'var') ~= 1
    load('ub.mat', 'ub');
end

stlData = stlread('femur_r_pose.stl');
baseRightVertices = stlData.Points * 100;   % Convert m to cm
baseFaces = stlData.ConnectivityList;

%% -------------------------- Optimization parameters ---------------------
R_RFT     = xopt(1);   Theta_RFT = xopt(2);   Phi_RFT = xopt(3);
R_RFE     = xopt(4);   Theta_RFE = xopt(5);   Phi_RFE = xopt(6);
R_LFT     = xopt(7);   Theta_LFT = xopt(8);   Phi_LFT = xopt(9);
R_LFE     = xopt(10);  Theta_LFE = xopt(11);  Phi_LFE = xopt(12);

%% -------------------------- Landmark centers ----------------------------
RFT_Cen = ([0.453058169368997  0.0456732664552253  1.67428098287425] + ...
           [0.446557417696759  0.0528216835201860  1.41085594536920]) / 2;

RFE_Cen = ([3.44496518373489  -0.893738925009966  1.82663314044476] + ...
           [3.43127995729446  -0.895564579665661  1.15275941789150]) / 2;

%% -------------------------- Right femur landmarks -----------------------
RFHNodes = [0.473593128845096,  0.103827624116093,   1.00590223446488;
            0.585383968427777, -0.107853289227933,   0.969875976443291;
            0.616033188998699, -0.135900150053203,   0.993466842919588;
            0.700947968289256,  0.141776225063950,   1.23720057308674;
            0.737857492640615, -0.0363110651960596,  0.983657687902451;
            0.675106048583984,  0.0497954199090600,  0.929478369653225;
            0.715530477464199, -0.0184063042979687,  0.952735263854265;
            0.648210383951664,  0.223668641410768,   1.09535045921803;
            0.601609796285629,  0.195587915368378,   1.01431673392653;
            0.567709095776081,  0.116057868581265,   0.958638545125723;
            0.517359282821417,  0.0912944960873574,  0.967827066779137;
            0.561253307387233,  0.211900868453085,   1.05412881821394;
            0.538222957402468,  0.221889559179544,   1.13999629393220;
            0.482013216242194,  0.161292427219450,   1.04488106444478;
            0.502240424975753, -0.0368660956155509,  0.967860314995050;
            0.451635196805000,  0.0671029672957957,  1.01308310404420;
            0.449216598644853,  0.153635651804507,   1.12468004226685;
            0.443179626017809,  0.138137745670974,   1.19220092892647;
            0.418968591839075,  0.0846878683660179,  1.09263248741627;
            0.428975699469447, -0.00741744079277851, 1.04311723262072;
            0.418658507987857, -0.0475212204037234,  1.11012030392885;
            0.411530118435621,  0.0486677570734173,  1.17137925699353;
            0.408684136345983, -0.00368475157301873, 1.15538211539388];

RFH = fit_and_plot_sphere(RFHNodes);
RFT = sphericalPoint(R_RFT, Theta_RFT, Phi_RFT, RFT_Cen);
RFE = sphericalPoint(R_RFE, Theta_RFE, Phi_RFE, RFE_Cen);

RFKne = [3.45160737633705  -1.15038147196174  1.45533466711640];
RFEL  = [3.45149496594233  -1.0727128515584   1.83574412161213];
RFEM  = [3.45149496594233  -1.1227128515584   1.15373533685618];

[right_vertices, right_F] = appendMarkerVertices(baseRightVertices, baseFaces, [RFH; RFT; RFE]);

RFemurBoneMarks = struct('RFH', RFH, 'RFT', RFT, 'RFE', RFE, ...
                         'RFKne', RFKne, 'RFEL', RFEL, 'RFEM', RFEM);
RFemur_STL = struct('Points', right_vertices, 'ConnectivityList', right_F);

save('RFemurBoneMarks.mat', 'RFemurBoneMarks');
save('RFemur_STL.mat', 'RFemur_STL');

%% -------------------------- Left femur landmarks ------------------------
LFT_Cen = mirrorZ(RFT_Cen);
LFE_Cen = mirrorZ(RFE_Cen);

LFH = mirrorZ(RFH);
LFT = sphericalPoint(R_LFT, Theta_LFT, Phi_LFT, LFT_Cen);
LFE = sphericalPoint(R_LFE, Theta_LFE, Phi_LFE, LFE_Cen);

LFKne = mirrorZ(RFKne);
LFEL  = mirrorZ(RFEL);
LFEM  = mirrorZ(RFEM);

baseLeftVertices = mirrorZ(baseRightVertices);
[left_vertices, left_F] = appendMarkerVertices(baseLeftVertices, baseFaces, [LFH; LFT; LFE]);

LFemurBoneMarks = struct('LFH', LFH, 'LFT', LFT, 'LFE', LFE, ...
                         'LFKne', LFKne, 'LFEL', LFEL, 'LFEM', LFEM);
LFemur_STL = struct('Points', left_vertices, 'ConnectivityList', left_F);

save('LFemurBoneMarks.mat', 'LFemurBoneMarks');
save('LFemur_STL.mat', 'LFemur_STL');

%% -------------------------- Helper functions ----------------------------
function point = sphericalPoint(radius, theta, phi, center)
    point = [radius * sin(theta) * cos(phi) + center(1), ...
             radius * sin(theta) * sin(phi) + center(2), ...
             radius * cos(theta)            + center(3)];
end

function mirrored = mirrorZ(points)
    mirrored = points;
    mirrored(:, 3) = -mirrored(:, 3);
end

function [verticesOut, facesOut] = appendMarkerVertices(verticesIn, facesIn, markers)
    n0 = size(verticesIn, 1);
    nMarkers = size(markers, 1);
    extraFaces = [(n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)'];

    verticesOut = [verticesIn; markers];
    facesOut = [facesIn; extraFaces];
end
