% -------------------------------------------------------------------------
% Right_Left_Tibia.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Generates optimized tibia landmarks and tibia STL MAT files.
% -------------------------------------------------------------------------

% This script generates right/left tibia bone landmarks and STL MAT files.
% It expects xopt in the workspace, ub.mat in the current folder, and
% RFemurBoneMarks.mat from Right_Left_Femur.m.

%% -------------------------- Checks and input files -----------------------
assert(exist('xopt', 'var') == 1, 'Right_Left_Tibia requires xopt in the workspace.');
assert(numel(xopt) >= 30, 'xopt must contain at least 30 values for tibia parameters.');

if exist('ub', 'var') ~= 1
    load('ub.mat', 'ub');
end

load('RFemurBoneMarks.mat', 'RFemurBoneMarks');

stlData = stlread('tibia_r_pose.stl');
baseRightVertices = stlData.Points * 100;   % Convert m to cm
baseFaces = stlData.ConnectivityList;

%% -------------------------- Optimization parameters ---------------------
R_RTP = xopt(13);  Theta_RTP = xopt(14);  Phi_RTP = xopt(15);
R_RTH = xopt(16);  Theta_RTH = xopt(17);  Phi_RTH = xopt(18);
R_RTD = xopt(19);  Theta_RTD = xopt(20);  Phi_RTD = xopt(21);

R_LTP = xopt(22);  Theta_LTP = xopt(23);  Phi_LTP = xopt(24);
R_LTH = xopt(25);  Theta_LTH = xopt(26);  Phi_LTH = xopt(27);
R_LTD = xopt(28);  Theta_LTD = xopt(29);  Phi_LTD = xopt(30);

%% -------------------------- Landmark centers ----------------------------
RTP_Cen = ([3.36064929970613  -1.53397863773839  1.86647469254660] + ...
           [3.37920593942895  -1.53121876850029  1.14050595497555]) / 2;
RTH_Cen = ([1.73960675808883  -3.02737013511598  1.39600560808229] + ...
           [1.73145113993318  -3.02196993965596  1.50569923192499]) / 2;
RTD_Cen = ([0.997516978369288 -3.92337737325861  1.09720060064015] + ...
           [1.00305887221275  -3.92324590966815  1.63478060876803]) / 2;

%% -------------------------- Right tibia landmarks -----------------------
RTP = sphericalPoint(R_RTP, Theta_RTP, Phi_RTP, RTP_Cen);
RTH = sphericalPoint(R_RTH, Theta_RTH, Phi_RTH, RTH_Cen);
RTD = sphericalPoint(R_RTD, Theta_RTD, Phi_RTD, RTD_Cen);

RTMAM = [0.810127705335617  -3.95617783069611  1.12023763358593];
RTMAL = [0.855118222534657  -3.94003242254257  1.67827904224396];
RTKne = [3.44076034391562   -1.28759129416991  1.44935422828625];
RTAnk = [0.816234853118658  -4.01129089295864  1.41258317473531];
RTPAL = RFemurBoneMarks.RFEL;
RTPAM = RFemurBoneMarks.RFEM;

[right_vertices, right_F] = appendMarkerVertices(baseRightVertices, baseFaces, ...
    [RTP; RTH; RTD; RTPAL; RTPAM]);

RTibiaBoneMarks = struct('RTP', RTP, 'RTH', RTH, 'RTD', RTD, ...
                         'RTMAM', RTMAM, 'RTMAL', RTMAL, ...
                         'RTKne', RTKne, 'RTAnk', RTAnk, ...
                         'RTPAL', RTPAL, 'RTPAM', RTPAM);
RTibia_STL = struct('Points', right_vertices, 'ConnectivityList', right_F);

save('RTibiaBoneMarks.mat', 'RTibiaBoneMarks');
save('RTibia_STL.mat', 'RTibia_STL');

%% -------------------------- Left tibia landmarks ------------------------
LTP_Cen = mirrorZ(RTP_Cen);
LTH_Cen = mirrorZ(RTH_Cen);
LTD_Cen = mirrorZ(RTD_Cen);

LTP = sphericalPoint(R_LTP, Theta_LTP, Phi_LTP, LTP_Cen);
LTH = sphericalPoint(R_LTH, Theta_LTH, Phi_LTH, LTH_Cen);
LTD = sphericalPoint(R_LTD, Theta_LTD, Phi_LTD, LTD_Cen);

LTMAM = mirrorZ(RTMAM);
LTMAL = mirrorZ(RTMAL);
LTKne = mirrorZ(RTKne);
LTAnk = mirrorZ(RTAnk);
LTPAL = mirrorZ(RTPAL);
LTPAM = mirrorZ(RTPAM);

baseLeftVertices = mirrorZ(baseRightVertices);
[left_vertices, left_F] = appendMarkerVertices(baseLeftVertices, baseFaces, ...
    [LTP; LTH; LTD; LTPAL; LTPAM]);

LTibiaBoneMarks = struct('LTP', LTP, 'LTH', LTH, 'LTD', LTD, ...
                         'LTMAM', LTMAM, 'LTMAL', LTMAL, ...
                         'LTKne', LTKne, 'LTAnk', LTAnk, ...
                         'LTPAL', LTPAL, 'LTPAM', LTPAM);
LTibia_STL = struct('Points', left_vertices, 'ConnectivityList', left_F);

save('LTibiaBoneMarks.mat', 'LTibiaBoneMarks');
save('LTibia_STL.mat', 'LTibia_STL');

%% -------------------------- Helper functions ----------------------------
function point = sphericalPoint(radius, theta, phi, center)
    point = [radius * sin(theta) * cos(phi) + center(1), ...
             radius * sin(theta) * sin(phi) + center(2), ...
             radius * cos(theta)            + center(3)];
end

function mirrored = mirrorZ(points)
    mirrored = points;
    mirrored(:, 3) = -mirrored(:, 3);
end

function [verticesOut, facesOut] = appendMarkerVertices(verticesIn, facesIn, markers)
    n0 = size(verticesIn, 1);
    nMarkers = size(markers, 1);
    extraFaces = [(n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)'];

    verticesOut = [verticesIn; markers];
    facesOut = [facesIn; extraFaces];
end
