% -------------------------------------------------------------------------
% Right_left_Pelvis.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Generates pelvis landmarks and pelvis STL MAT file.
% -------------------------------------------------------------------------

% This script generates pelvis landmarks and the pelvis STL MAT file.
% It expects RFemurBoneMarks.mat and LFemurBoneMarks.mat from
% Right_Left_Femur.m.

%% -------------------------- Input files ---------------------------------
load('RFemurBoneMarks.mat', 'RFemurBoneMarks');
load('LFemurBoneMarks.mat', 'LFemurBoneMarks');

stlData = stlread('pelvis_rl_pose.stl');
V = stlData.Points * 100;     % Convert m to cm
F = stlData.ConnectivityList;

%% -------------------------- Pelvis landmarks ----------------------------
RASI = [2.57688909769058  1.62046644836664   1.26270083710551];
LASI = [2.57688909769058  1.62046644836664  -1.26270083710551];

% Hip centers are taken from the fitted femoral-head centers.
RPHip = RFemurBoneMarks.RFH;
LPHip = LFemurBoneMarks.LFH;

PS = [0.227679475210607  -1.34201366454363  0];

% Add hip centers as extra STL vertices so they are exactly available for
% later registration and visualization.
[V, F] = appendMarkerVertices(V, F, [RPHip; LPHip]);

%% -------------------------- Use closest STL vertices --------------------
[~, I_RASI]  = closestVertex(V, RASI);
[~, I_LASI]  = closestVertex(V, LASI);
[~, I_RPHip] = closestVertex(V, RPHip);
[~, I_LPHip] = closestVertex(V, LPHip);
[~, I_PS]    = closestVertex(V, PS);

PelvisBoneMarks.RASI  = V(I_RASI,  :);
PelvisBoneMarks.LASI  = V(I_LASI,  :);
PelvisBoneMarks.RPHip = V(I_RPHip, :);
PelvisBoneMarks.LPHip = V(I_LPHip, :);
PelvisBoneMarks.PS    = V(I_PS,    :);

Pelvis_STL.Points = V;
Pelvis_STL.ConnectivityList = F;

save('PelvisBoneMarks.mat', 'PelvisBoneMarks');
save('Pelvis_STL.mat', 'Pelvis_STL');

%% -------------------------- Helper functions ----------------------------
function [minDistance, index] = closestVertex(vertices, point)
    distances = vecnorm(vertices - point, 2, 2);
    [minDistance, index] = min(distances);
end

function [verticesOut, facesOut] = appendMarkerVertices(verticesIn, facesIn, markers)
    n0 = size(verticesIn, 1);
    nMarkers = size(markers, 1);
    extraFaces = [(n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)', (n0+1:n0+nMarkers)'];

    verticesOut = [verticesIn; markers];
    facesOut = [facesIn; extraFaces];
end
