% -------------------------------------------------------------------------
% rigid_transform_3D_MA.m
%
% Generated by: Seyed Mohammadali Rahmati
% Affiliation : Comparative Neuromechanics Lab,
%               School of Biological Sciences,
%               Georgia Institute of Technology, Atlanta, GA, USA
% Email       : smarahmati@gmail.com
%
% Description:
%   Estimates the rotation, translation, and anisotropic scale that align
%   a selected set of 3D source points B to target points A.
%
% Notes:
%   This function is used for bone/mesh registration from selected
%   anatomical landmarks. The output order is:
%       [R, t, s]
%   where R is rotation, t is translation, and s is the 3D scale matrix.
% -------------------------------------------------------------------------

function [R, t, s] = rigid_transform_3D_MA(A, B)
%RIGID_TRANSFORM_3D_MA Estimate rotation, translation, and 3D scale.
%
%   B is transformed to A using:
%       B_new = (B - mean(B_selected)) * s * R + t
%
%   Default max_iter = 1.
%   For mesh registration from a few selected landmarks, one iteration is
%   recommended to avoid overfitting the landmarks and drifting the mesh.


    max_iter = 1;


    assert(isequal(size(A), size(B)), 'A and B must have the same size.');
    assert(size(A, 2) == 3, 'A and B must be Nx3 matrices.');

    % User-set parameters
    threshold = 1e-6;
    min_scale = 0.7;
    max_scale = 1.3;

    % Centroids of the selected corresponding points
    centroid_A = mean(A, 1);
    centroid_B = mean(B, 1);

    % Center selected points
    Ac = A - centroid_A;
    Bc = B - centroid_B;

    % Initialize transform
    R = eye(3);
    s = eye(3);
    t = centroid_A;

    % Scale-rotation estimation
    for iter = 1:max_iter

        % Estimate rotation
        H = s * Bc' * Ac;
        [U, ~, V] = svd(H);
        R = V * U';

        % Prevent reflection
        if det(R) < 0
            V(:, 3) = -V(:, 3);
            R = V * U';
        end

        % Estimate anisotropic scale
        Nom = Bc' * Ac * R;
        Deno = Bc' * Bc;

        s_new = diag([
            Nom(1,1) / Deno(1,1)
            Nom(2,2) / Deno(2,2)
            Nom(3,3) / Deno(3,3)
        ]);

        % Limit scaling
        s_new(1,1) = max(min(s_new(1,1), max_scale), min_scale);
        s_new(2,2) = max(min(s_new(2,2), max_scale), min_scale);
        s_new(3,3) = max(min(s_new(3,3), max_scale), min_scale);

        % Stop if scale barely changes
        if norm(s_new - s, 'fro') < threshold
            s = s_new;
            break;
        end

        s = s_new;
    end

end